'use strict';

const { generateShareKey } = require('./bearpit-backups');

const MAX_ENTRIES = 80;
const MAX_NAME_LEN = 12;
const KEY_RE = /^[A-Za-z0-9]{16}$/;
const TOKEN_RE = /^[A-Za-z0-9]{24}$/;

const COLLECT_FIELD_DEFS = [
  { id: 'heroPower', label: '英雄总实力', placeholder: '例如 1250万', kind: 'power' },
  { id: 'personalPower', label: '个人实力', placeholder: '例如 800万', kind: 'power' },
  { id: 'earthPower', label: '地心战力', placeholder: '例如 300万', kind: 'power' },
  { id: 'petPower', label: '宠物', placeholder: '例如 200万', kind: 'power' },
  { id: 'expertPower', label: '专家', placeholder: '例如 150万', kind: 'power' },
  { id: 'bearDamage', label: '打熊伤害', placeholder: '例如 1.2亿', kind: 'power' },
  { id: 'expedition', label: '探险关卡数', placeholder: '例如 120', kind: 'stage' }
];

const COLLECT_FIELD_IDS = COLLECT_FIELD_DEFS.map((item) => item.id);
const DEFAULT_COLLECT_FIELDS = ['heroPower'];

const BEARPIT_COLLECT_FORMS_DDL_MYSQL = `
  CREATE TABLE IF NOT EXISTS bearpit_collect_forms (
    collect_key VARCHAR(16) PRIMARY KEY,
    host_token VARCHAR(32) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    KEY idx_bearpit_collect_forms_created (created_at)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
`;

const BEARPIT_COLLECT_FORMS_DDL_PG = `
  CREATE TABLE IF NOT EXISTS bearpit_collect_forms (
    collect_key varchar(16) PRIMARY KEY,
    host_token varchar(32) NOT NULL,
    created_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
  );
  CREATE INDEX IF NOT EXISTS idx_bearpit_collect_forms_created ON bearpit_collect_forms (created_at DESC);
`;

const BEARPIT_COLLECT_ENTRIES_DDL_MYSQL = `
  CREATE TABLE IF NOT EXISTS bearpit_collect_entries (
    id INT AUTO_INCREMENT PRIMARY KEY,
    collect_key VARCHAR(16) NOT NULL,
    name VARCHAR(12) NOT NULL,
    power BIGINT NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    UNIQUE KEY uniq_bearpit_collect_name (collect_key, name),
    KEY idx_bearpit_collect_entries_key (collect_key, power)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
`;

const BEARPIT_COLLECT_ENTRIES_DDL_PG = `
  CREATE TABLE IF NOT EXISTS bearpit_collect_entries (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collect_key varchar(16) NOT NULL,
    name varchar(12) NOT NULL,
    power bigint NOT NULL,
    created_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
  );
  CREATE UNIQUE INDEX IF NOT EXISTS uniq_bearpit_collect_name ON bearpit_collect_entries (collect_key, name);
  CREATE INDEX IF NOT EXISTS idx_bearpit_collect_entries_key ON bearpit_collect_entries (collect_key, power DESC);
`;

function generateHostToken() {
  return generateShareKey() + generateShareKey().slice(0, 8);
}

function normalizeCollectName(value) {
  const name = Array.from(String(value || '').trim().replace(/\s+/g, ' ')).slice(0, MAX_NAME_LEN).join('');
  return name || null;
}

function parseHeroPower(raw) {
  const s = String(raw == null ? '' : raw).trim().replace(/,/g, '').replace(/，/g, '').replace(/\s+/g, '');
  const m = s.match(/^(\d+(?:\.\d+)?)(万|亿|w|W)?$/);
  if (!m) return null;
  let n = Number(m[1]);
  if (!Number.isFinite(n) || n < 0) return null;
  const unit = m[2];
  if (unit === '亿') n *= 1e8;
  else if (unit === '万' || unit === 'w' || unit === 'W') n *= 1e4;
  n = Math.round(n);
  if (n < 1 || n > 1e15) return null;
  return n;
}

function parseStageCount(raw) {
  const s = String(raw == null ? '' : raw).trim().replace(/,/g, '').replace(/，/g, '');
  if (!/^\d+$/.test(s)) return null;
  const n = Number(s);
  if (!Number.isFinite(n) || n < 1 || n > 9999) return null;
  return n;
}

function collectFieldDef(id) {
  return COLLECT_FIELD_DEFS.find((item) => item.id === id) || null;
}

function normalizeCollectFields(value) {
  const raw = Array.isArray(value)
    ? value
    : (typeof value === 'string' ? (() => { try { return JSON.parse(value); } catch (_err) { return []; } })() : []);
  const seen = {};
  const out = [];
  raw.forEach((item) => {
    const id = String(item || '').trim();
    if (!COLLECT_FIELD_IDS.includes(id) || seen[id]) return;
    seen[id] = 1;
    out.push(id);
  });
  return out.length ? out : DEFAULT_COLLECT_FIELDS.slice();
}

function normalizeRankField(fields, rankField) {
  const list = normalizeCollectFields(fields);
  const id = String(rankField || '').trim();
  return list.includes(id) ? id : list[0];
}

function parseCollectValue(fieldId, raw) {
  const def = collectFieldDef(fieldId);
  if (!def) return null;
  return def.kind === 'stage' ? parseStageCount(raw) : parseHeroPower(raw);
}

function parseJsonValue(value, fallback) {
  if (value == null || value === '') return fallback;
  if (typeof value === 'object') return value;
  try { return JSON.parse(String(value)); } catch (_err) { return fallback; }
}

function stringifyJson(value) {
  return JSON.stringify(value == null ? {} : value);
}

function parseEntryStats(row) {
  const stats = parseJsonValue(row && row.stats_json, {}) || {};
  const out = {};
  COLLECT_FIELD_IDS.forEach((id) => {
    const n = Number(stats[id]);
    if (Number.isFinite(n) && n > 0) out[id] = n;
  });
  if (!out.heroPower && Number(row && row.power) > 0) out.heroPower = Number(row.power);
  return out;
}

function parseSubmittedStats(body, fields) {
  const source = (body && typeof body.stats === 'object' && body.stats) ? body.stats : (body || {});
  const stats = {};
  for (let i = 0; i < fields.length; i++) {
    const id = fields[i];
    const raw = source[id] != null ? source[id] : (id === 'heroPower' ? body.power : null);
    const value = parseCollectValue(id, raw);
    if (!value) return { error: id };
    stats[id] = value;
  }
  return { stats };
}

function mapFormConfig(row) {
  const fields = normalizeCollectFields(row && row.fields_json);
  const rankField = normalizeRankField(fields, row && row.rank_field);
  return { fields, rankField };
}

function mapEntry(row, rankField) {
  if (!row) return null;
  const stats = parseEntryStats(row);
  const rank = rankField || 'heroPower';
  const power = Number(stats[rank] || row.power || 0);
  return {
    id: Number(row.id),
    name: String(row.name || ''),
    power,
    stats,
    createdAt: row.created_at
  };
}

function mountBearpitCollectRoutes(deps) {
  const { app, queryRows, queryOne, execute, pgDatabase } = deps;
  let tablesReady = false;

  async function addColumn(table, mysqlDdl, pgDdl) {
    if (pgDatabase) {
      await execute(`ALTER TABLE ${table} ADD COLUMN IF NOT EXISTS ${pgDdl}`);
      return;
    }
    try {
      await execute(`ALTER TABLE ${table} ADD COLUMN ${mysqlDdl}`);
    } catch (_err) {}
  }

  async function ensureTables() {
    if (tablesReady) return;
    await execute(pgDatabase ? BEARPIT_COLLECT_FORMS_DDL_PG : BEARPIT_COLLECT_FORMS_DDL_MYSQL);
    await execute(pgDatabase ? BEARPIT_COLLECT_ENTRIES_DDL_PG : BEARPIT_COLLECT_ENTRIES_DDL_MYSQL);
    await addColumn(
      'bearpit_collect_forms',
      "fields_json TEXT NULL",
      "fields_json jsonb"
    );
    await addColumn(
      'bearpit_collect_forms',
      "rank_field VARCHAR(32) NOT NULL DEFAULT 'heroPower'",
      "rank_field varchar(32) NOT NULL DEFAULT 'heroPower'"
    );
    await addColumn(
      'bearpit_collect_entries',
      'stats_json TEXT NULL',
      'stats_json jsonb'
    );
    tablesReady = true;
  }

  async function getForm(key) {
    return queryOne(
      'SELECT collect_key, host_token, created_at, fields_json, rank_field FROM bearpit_collect_forms WHERE collect_key = ? LIMIT 1',
      [key]
    );
  }

  async function saveFormConfig(key, fields, rankField) {
    const json = stringifyJson(fields);
    await execute(
      'UPDATE bearpit_collect_forms SET fields_json = ?, rank_field = ? WHERE collect_key = ?',
      [json, rankField, key]
    );
  }

  function tokenOk(form, token) {
    return Boolean(form && token && String(form.host_token) === String(token));
  }

  app.post('/api/bearpit/collect', async (req, res) => {
    try {
      await ensureTables();
      const hasConfig = Array.isArray(req.body?.fields);
      const fields = hasConfig ? normalizeCollectFields(req.body?.fields) : DEFAULT_COLLECT_FIELDS.slice();
      const rankField = hasConfig
        ? normalizeRankField(fields, req.body?.rankField || req.body?.rank_field)
        : 'heroPower';
      const existingKey = String(req.body?.collectKey || '').trim();
      const existingToken = String(req.body?.hostToken || '').trim();
      if (KEY_RE.test(existingKey) && TOKEN_RE.test(existingToken)) {
        const form = await getForm(existingKey);
        if (form && tokenOk(form, existingToken)) {
          if (hasConfig) await saveFormConfig(existingKey, fields, rankField);
          const config = hasConfig ? { fields, rankField } : mapFormConfig(form);
          return res.json({ ok: true, collectKey: existingKey, hostToken: existingToken, ...config });
        }
      }
      let collectKey = null;
      const hostToken = generateHostToken();
      const createFields = hasConfig ? fields : DEFAULT_COLLECT_FIELDS.slice();
      const createRank = hasConfig ? rankField : 'heroPower';
      for (let attempt = 0; attempt < 5; attempt += 1) {
        const candidate = generateShareKey();
        try {
          await execute(
            'INSERT INTO bearpit_collect_forms (collect_key, host_token, created_at, fields_json, rank_field) VALUES (?, ?, CURRENT_TIMESTAMP(3), ?, ?)',
            [candidate, hostToken, stringifyJson(createFields), createRank]
          );
          collectKey = candidate;
          break;
        } catch (err) {
          if (!String(err?.message || '').toLowerCase().includes('duplicate') && !String(err?.code || '').toUpperCase().includes('DUP')) throw err;
        }
      }
      if (!collectKey) return res.status(503).json({ error: 'COLLECT_KEY_UNAVAILABLE' });
      return res.json({ ok: true, collectKey, hostToken, fields: createFields, rankField: createRank });
    } catch (err) {
      console.error('bearpit collect create failed:', err);
      return res.status(500).json({ error: 'INTERNAL_ERROR' });
    }
  });

  app.get('/api/bearpit/collect/:key', async (req, res) => {
    try {
      await ensureTables();
      const key = String(req.params.key || '').trim();
      if (!KEY_RE.test(key)) return res.status(400).json({ error: 'BAD_KEY' });
      const form = await getForm(key);
      if (!form) return res.status(404).json({ error: 'NOT_FOUND' });
      const config = mapFormConfig(form);
      const token = String(req.query?.token || req.query?.hostToken || '').trim();
      if (!tokenOk(form, token)) {
        const countRow = await queryOne(
          'SELECT COUNT(*) AS n FROM bearpit_collect_entries WHERE collect_key = ?',
          [key]
        );
        return res.json({
          ok: true,
          open: true,
          count: Number(countRow && countRow.n) || 0,
          fields: config.fields,
          rankField: config.rankField
        });
      }
      const rows = await queryRows(
        `
        SELECT id, name, power, stats_json, created_at
        FROM bearpit_collect_entries
        WHERE collect_key = ?
        ORDER BY power DESC, created_at ASC, id ASC
        `,
        [key]
      );
      return res.json({
        ok: true,
        collectKey: key,
        fields: config.fields,
        rankField: config.rankField,
        entries: rows.map((row) => mapEntry(row, config.rankField))
      });
    } catch (err) {
      console.error('bearpit collect get failed:', err);
      return res.status(500).json({ error: 'INTERNAL_ERROR' });
    }
  });

  app.post('/api/bearpit/collect/:key/entries', async (req, res) => {
    try {
      await ensureTables();
      const key = String(req.params.key || '').trim();
      if (!KEY_RE.test(key)) return res.status(400).json({ error: 'BAD_KEY' });
      const form = await getForm(key);
      if (!form) return res.status(404).json({ error: 'NOT_FOUND' });
      const config = mapFormConfig(form);
      const name = normalizeCollectName(req.body?.name);
      if (!name) return res.status(400).json({ error: 'BAD_NAME' });
      const parsed = parseSubmittedStats(req.body, config.fields);
      if (parsed.error) return res.status(400).json({ error: 'BAD_POWER', field: parsed.error });
      const power = parsed.stats[config.rankField];
      const existing = await queryOne(
        'SELECT id FROM bearpit_collect_entries WHERE collect_key = ? AND name = ? LIMIT 1',
        [key, name]
      );
      if (!existing) {
        const countRow = await queryOne(
          'SELECT COUNT(*) AS n FROM bearpit_collect_entries WHERE collect_key = ?',
          [key]
        );
        if ((Number(countRow && countRow.n) || 0) >= MAX_ENTRIES) {
          return res.status(400).json({ error: 'FULL' });
        }
      }
      const statsJson = stringifyJson(parsed.stats);
      if (pgDatabase) {
        await execute(
          `
          INSERT INTO bearpit_collect_entries (collect_key, name, power, stats_json, created_at)
          VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP(3))
          ON CONFLICT (collect_key, name) DO UPDATE SET power = EXCLUDED.power, stats_json = EXCLUDED.stats_json
          `,
          [key, name, power, statsJson]
        );
      } else {
        await execute(
          `
          INSERT INTO bearpit_collect_entries (collect_key, name, power, stats_json, created_at)
          VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP(3))
          ON DUPLICATE KEY UPDATE power = VALUES(power), stats_json = VALUES(stats_json)
          `,
          [key, name, power, statsJson]
        );
      }
      const row = await queryOne(
        'SELECT id, name, power, stats_json, created_at FROM bearpit_collect_entries WHERE collect_key = ? AND name = ? LIMIT 1',
        [key, name]
      );
      return res.json({ ok: true, updated: Boolean(existing), entry: mapEntry(row, config.rankField) });
    } catch (err) {
      console.error('bearpit collect submit failed:', err);
      return res.status(500).json({ error: 'INTERNAL_ERROR' });
    }
  });

  app.post('/api/bearpit/collect/:key/entries/:id/delete', async (req, res) => {
    try {
      await ensureTables();
      const key = String(req.params.key || '').trim();
      const id = Number(req.params.id);
      const token = String(req.body?.hostToken || req.body?.token || '').trim();
      if (!KEY_RE.test(key) || !Number.isFinite(id) || id <= 0) return res.status(400).json({ error: 'BAD_REQUEST' });
      const form = await getForm(key);
      if (!form) return res.status(404).json({ error: 'NOT_FOUND' });
      if (!tokenOk(form, token)) return res.status(403).json({ error: 'FORBIDDEN' });
      await execute('DELETE FROM bearpit_collect_entries WHERE id = ? AND collect_key = ?', [id, key]);
      return res.json({ ok: true });
    } catch (err) {
      console.error('bearpit collect delete failed:', err);
      return res.status(500).json({ error: 'INTERNAL_ERROR' });
    }
  });

  app.post('/api/bearpit/collect/:key/clear', async (req, res) => {
    try {
      await ensureTables();
      const key = String(req.params.key || '').trim();
      const token = String(req.body?.hostToken || req.body?.token || '').trim();
      if (!KEY_RE.test(key)) return res.status(400).json({ error: 'BAD_KEY' });
      const form = await getForm(key);
      if (!form) return res.status(404).json({ error: 'NOT_FOUND' });
      if (!tokenOk(form, token)) return res.status(403).json({ error: 'FORBIDDEN' });
      await execute('DELETE FROM bearpit_collect_entries WHERE collect_key = ?', [key]);
      return res.json({ ok: true });
    } catch (err) {
      console.error('bearpit collect clear failed:', err);
      return res.status(500).json({ error: 'INTERNAL_ERROR' });
    }
  });
}

module.exports = {
  MAX_ENTRIES,
  MAX_NAME_LEN,
  KEY_RE,
  TOKEN_RE,
  COLLECT_FIELD_DEFS,
  COLLECT_FIELD_IDS,
  DEFAULT_COLLECT_FIELDS,
  BEARPIT_COLLECT_FORMS_DDL_MYSQL,
  BEARPIT_COLLECT_FORMS_DDL_PG,
  BEARPIT_COLLECT_ENTRIES_DDL_MYSQL,
  BEARPIT_COLLECT_ENTRIES_DDL_PG,
  generateHostToken,
  normalizeCollectName,
  parseHeroPower,
  parseStageCount,
  parseCollectValue,
  normalizeCollectFields,
  normalizeRankField,
  mountBearpitCollectRoutes
};
