'use strict';

const { generateShareKey } = require('./bearpit-backups');

const MAX_ENTRIES = 80;
const MAX_NAME_LEN = 12;
const KEY_RE = /^[A-Za-z0-9]{16}$/;
const TOKEN_RE = /^[A-Za-z0-9]{24}$/;

const BEARPIT_COLLECT_FORMS_DDL_MYSQL = `
  CREATE TABLE IF NOT EXISTS bearpit_collect_forms (
    collect_key VARCHAR(16) PRIMARY KEY,
    host_token VARCHAR(32) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    KEY idx_bearpit_collect_forms_created (created_at)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
`;

const BEARPIT_COLLECT_FORMS_DDL_PG = `
  CREATE TABLE IF NOT EXISTS bearpit_collect_forms (
    collect_key varchar(16) PRIMARY KEY,
    host_token varchar(32) NOT NULL,
    created_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
  );
  CREATE INDEX IF NOT EXISTS idx_bearpit_collect_forms_created ON bearpit_collect_forms (created_at DESC);
`;

const BEARPIT_COLLECT_ENTRIES_DDL_MYSQL = `
  CREATE TABLE IF NOT EXISTS bearpit_collect_entries (
    id INT AUTO_INCREMENT PRIMARY KEY,
    collect_key VARCHAR(16) NOT NULL,
    name VARCHAR(12) NOT NULL,
    power BIGINT NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    UNIQUE KEY uniq_bearpit_collect_name (collect_key, name),
    KEY idx_bearpit_collect_entries_key (collect_key, power)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
`;

const BEARPIT_COLLECT_ENTRIES_DDL_PG = `
  CREATE TABLE IF NOT EXISTS bearpit_collect_entries (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collect_key varchar(16) NOT NULL,
    name varchar(12) NOT NULL,
    power bigint NOT NULL,
    created_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
  );
  CREATE UNIQUE INDEX IF NOT EXISTS uniq_bearpit_collect_name ON bearpit_collect_entries (collect_key, name);
  CREATE INDEX IF NOT EXISTS idx_bearpit_collect_entries_key ON bearpit_collect_entries (collect_key, power DESC);
`;

function generateHostToken() {
  return generateShareKey() + generateShareKey().slice(0, 8);
}

function normalizeCollectName(value) {
  const name = Array.from(String(value || '').trim().replace(/\s+/g, ' ')).slice(0, MAX_NAME_LEN).join('');
  return name || null;
}

function parseHeroPower(raw) {
  const s = String(raw == null ? '' : raw).trim().replace(/,/g, '').replace(/，/g, '').replace(/\s+/g, '');
  const m = s.match(/^(\d+(?:\.\d+)?)(万|亿|w|W)?$/);
  if (!m) return null;
  let n = Number(m[1]);
  if (!Number.isFinite(n) || n < 0) return null;
  const unit = m[2];
  if (unit === '亿') n *= 1e8;
  else if (unit === '万' || unit === 'w' || unit === 'W') n *= 1e4;
  n = Math.round(n);
  if (n < 1 || n > 1e15) return null;
  return n;
}

function mapEntry(row) {
  if (!row) return null;
  return {
    id: Number(row.id),
    name: String(row.name || ''),
    power: Number(row.power || 0),
    createdAt: row.created_at
  };
}

function mountBearpitCollectRoutes(deps) {
  const { app, queryRows, queryOne, execute, pgDatabase } = deps;
  let tablesReady = false;

  async function ensureTables() {
    if (tablesReady) return;
    await execute(pgDatabase ? BEARPIT_COLLECT_FORMS_DDL_PG : BEARPIT_COLLECT_FORMS_DDL_MYSQL);
    await execute(pgDatabase ? BEARPIT_COLLECT_ENTRIES_DDL_PG : BEARPIT_COLLECT_ENTRIES_DDL_MYSQL);
    tablesReady = true;
  }

  async function getForm(key) {
    return queryOne(
      'SELECT collect_key, host_token, created_at FROM bearpit_collect_forms WHERE collect_key = ? LIMIT 1',
      [key]
    );
  }

  function tokenOk(form, token) {
    return Boolean(form && token && String(form.host_token) === String(token));
  }

  app.post('/api/bearpit/collect', async (req, res) => {
    try {
      await ensureTables();
      const existingKey = String(req.body?.collectKey || '').trim();
      const existingToken = String(req.body?.hostToken || '').trim();
      if (KEY_RE.test(existingKey) && TOKEN_RE.test(existingToken)) {
        const form = await getForm(existingKey);
        if (form && tokenOk(form, existingToken)) {
          return res.json({ ok: true, collectKey: existingKey, hostToken: existingToken });
        }
      }
      let collectKey = null;
      const hostToken = generateHostToken();
      for (let attempt = 0; attempt < 5; attempt += 1) {
        const candidate = generateShareKey();
        try {
          await execute(
            'INSERT INTO bearpit_collect_forms (collect_key, host_token, created_at) VALUES (?, ?, CURRENT_TIMESTAMP(3))',
            [candidate, hostToken]
          );
          collectKey = candidate;
          break;
        } catch (err) {
          if (!String(err?.message || '').toLowerCase().includes('duplicate') && !String(err?.code || '').toUpperCase().includes('DUP')) throw err;
        }
      }
      if (!collectKey) return res.status(503).json({ error: 'COLLECT_KEY_UNAVAILABLE' });
      return res.json({ ok: true, collectKey, hostToken });
    } catch (err) {
      console.error('bearpit collect create failed:', err);
      return res.status(500).json({ error: 'INTERNAL_ERROR' });
    }
  });

  app.get('/api/bearpit/collect/:key', async (req, res) => {
    try {
      await ensureTables();
      const key = String(req.params.key || '').trim();
      if (!KEY_RE.test(key)) return res.status(400).json({ error: 'BAD_KEY' });
      const form = await getForm(key);
      if (!form) return res.status(404).json({ error: 'NOT_FOUND' });
      const token = String(req.query?.token || req.query?.hostToken || '').trim();
      if (!tokenOk(form, token)) {
        const countRow = await queryOne(
          'SELECT COUNT(*) AS n FROM bearpit_collect_entries WHERE collect_key = ?',
          [key]
        );
        return res.json({ ok: true, open: true, count: Number(countRow && countRow.n) || 0 });
      }
      const rows = await queryRows(
        `
        SELECT id, name, power, created_at
        FROM bearpit_collect_entries
        WHERE collect_key = ?
        ORDER BY power DESC, created_at ASC, id ASC
        `,
        [key]
      );
      return res.json({ ok: true, collectKey: key, entries: rows.map(mapEntry) });
    } catch (err) {
      console.error('bearpit collect get failed:', err);
      return res.status(500).json({ error: 'INTERNAL_ERROR' });
    }
  });

  app.post('/api/bearpit/collect/:key/entries', async (req, res) => {
    try {
      await ensureTables();
      const key = String(req.params.key || '').trim();
      if (!KEY_RE.test(key)) return res.status(400).json({ error: 'BAD_KEY' });
      const form = await getForm(key);
      if (!form) return res.status(404).json({ error: 'NOT_FOUND' });
      const name = normalizeCollectName(req.body?.name);
      const power = parseHeroPower(req.body?.power);
      if (!name) return res.status(400).json({ error: 'BAD_NAME' });
      if (!power) return res.status(400).json({ error: 'BAD_POWER' });
      const existing = await queryOne(
        'SELECT id FROM bearpit_collect_entries WHERE collect_key = ? AND name = ? LIMIT 1',
        [key, name]
      );
      if (!existing) {
        const countRow = await queryOne(
          'SELECT COUNT(*) AS n FROM bearpit_collect_entries WHERE collect_key = ?',
          [key]
        );
        if ((Number(countRow && countRow.n) || 0) >= MAX_ENTRIES) {
          return res.status(400).json({ error: 'FULL' });
        }
      }
      if (pgDatabase) {
        await execute(
          `
          INSERT INTO bearpit_collect_entries (collect_key, name, power, created_at)
          VALUES (?, ?, ?, CURRENT_TIMESTAMP(3))
          ON CONFLICT (collect_key, name) DO UPDATE SET power = EXCLUDED.power
          `,
          [key, name, power]
        );
      } else {
        await execute(
          `
          INSERT INTO bearpit_collect_entries (collect_key, name, power, created_at)
          VALUES (?, ?, ?, CURRENT_TIMESTAMP(3))
          ON DUPLICATE KEY UPDATE power = VALUES(power)
          `,
          [key, name, power]
        );
      }
      const row = await queryOne(
        'SELECT id, name, power, created_at FROM bearpit_collect_entries WHERE collect_key = ? AND name = ? LIMIT 1',
        [key, name]
      );
      return res.json({ ok: true, updated: Boolean(existing), entry: mapEntry(row) });
    } catch (err) {
      console.error('bearpit collect submit failed:', err);
      return res.status(500).json({ error: 'INTERNAL_ERROR' });
    }
  });

  app.post('/api/bearpit/collect/:key/entries/:id/delete', async (req, res) => {
    try {
      await ensureTables();
      const key = String(req.params.key || '').trim();
      const id = Number(req.params.id);
      const token = String(req.body?.hostToken || req.body?.token || '').trim();
      if (!KEY_RE.test(key) || !Number.isFinite(id) || id <= 0) return res.status(400).json({ error: 'BAD_REQUEST' });
      const form = await getForm(key);
      if (!form) return res.status(404).json({ error: 'NOT_FOUND' });
      if (!tokenOk(form, token)) return res.status(403).json({ error: 'FORBIDDEN' });
      await execute('DELETE FROM bearpit_collect_entries WHERE id = ? AND collect_key = ?', [id, key]);
      return res.json({ ok: true });
    } catch (err) {
      console.error('bearpit collect delete failed:', err);
      return res.status(500).json({ error: 'INTERNAL_ERROR' });
    }
  });

  app.post('/api/bearpit/collect/:key/clear', async (req, res) => {
    try {
      await ensureTables();
      const key = String(req.params.key || '').trim();
      const token = String(req.body?.hostToken || req.body?.token || '').trim();
      if (!KEY_RE.test(key)) return res.status(400).json({ error: 'BAD_KEY' });
      const form = await getForm(key);
      if (!form) return res.status(404).json({ error: 'NOT_FOUND' });
      if (!tokenOk(form, token)) return res.status(403).json({ error: 'FORBIDDEN' });
      await execute('DELETE FROM bearpit_collect_entries WHERE collect_key = ?', [key]);
      return res.json({ ok: true });
    } catch (err) {
      console.error('bearpit collect clear failed:', err);
      return res.status(500).json({ error: 'INTERNAL_ERROR' });
    }
  });
}

module.exports = {
  MAX_ENTRIES,
  MAX_NAME_LEN,
  KEY_RE,
  TOKEN_RE,
  BEARPIT_COLLECT_FORMS_DDL_MYSQL,
  BEARPIT_COLLECT_FORMS_DDL_PG,
  BEARPIT_COLLECT_ENTRIES_DDL_MYSQL,
  BEARPIT_COLLECT_ENTRIES_DDL_PG,
  generateHostToken,
  normalizeCollectName,
  parseHeroPower,
  mountBearpitCollectRoutes
};
