'use strict';

const { generateShareKey } = require('./bearpit-backups');

const MAX_ENTRIES = 80;
const MAX_NAME_LEN = 12;
const MAX_TITLE_LEN = 16;
const MAX_FORMS_PER_USER = 20;
const DEFAULT_COLLECT_TITLE = '收集名单';
const KEY_RE = /^[A-Za-z0-9]{16}$/;
const TOKEN_RE = /^[A-Za-z0-9]{24}$/;

const COLLECT_FIELD_DEFS = [
  { id: 'heroPower', label: '英雄总实力', placeholder: '例如 1250万', kind: 'power' },
  { id: 'personalPower', label: '个人实力', placeholder: '例如 800万', kind: 'power' },
  { id: 'earthPower', label: '地心战力', placeholder: '例如 300万', kind: 'power' },
  { id: 'petPower', label: '宠物', placeholder: '例如 200万', kind: 'power' },
  { id: 'expertPower', label: '专家', placeholder: '例如 150万', kind: 'power' },
  { id: 'bearDamage', label: '打熊伤害', placeholder: '例如 1.2亿', kind: 'power' },
  { id: 'expedition', label: '探险关卡数', placeholder: '例如 120', kind: 'stage' }
];

const COLLECT_FIELD_IDS = COLLECT_FIELD_DEFS.map((item) => item.id);
const DEFAULT_COLLECT_FIELDS = ['heroPower'];

const BEARPIT_COLLECT_FORMS_DDL_MYSQL = `
  CREATE TABLE IF NOT EXISTS bearpit_collect_forms (
    collect_key VARCHAR(16) PRIMARY KEY,
    host_token VARCHAR(32) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    KEY idx_bearpit_collect_forms_created (created_at)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
`;

const BEARPIT_COLLECT_FORMS_DDL_PG = `
  CREATE TABLE IF NOT EXISTS bearpit_collect_forms (
    collect_key varchar(16) PRIMARY KEY,
    host_token varchar(32) NOT NULL,
    created_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
  );
  CREATE INDEX IF NOT EXISTS idx_bearpit_collect_forms_created ON bearpit_collect_forms (created_at DESC);
`;

const BEARPIT_COLLECT_ENTRIES_DDL_MYSQL = `
  CREATE TABLE IF NOT EXISTS bearpit_collect_entries (
    id INT AUTO_INCREMENT PRIMARY KEY,
    collect_key VARCHAR(16) NOT NULL,
    name VARCHAR(12) NOT NULL,
    power BIGINT NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    UNIQUE KEY uniq_bearpit_collect_name (collect_key, name),
    KEY idx_bearpit_collect_entries_key (collect_key, power)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
`;

const BEARPIT_COLLECT_ENTRIES_DDL_PG = `
  CREATE TABLE IF NOT EXISTS bearpit_collect_entries (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collect_key varchar(16) NOT NULL,
    name varchar(12) NOT NULL,
    power bigint NOT NULL,
    created_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
  );
  CREATE UNIQUE INDEX IF NOT EXISTS uniq_bearpit_collect_name ON bearpit_collect_entries (collect_key, name);
  CREATE INDEX IF NOT EXISTS idx_bearpit_collect_entries_key ON bearpit_collect_entries (collect_key, power DESC);
`;

function generateHostToken() {
  return generateShareKey() + generateShareKey().slice(0, 8);
}

function normalizeCollectName(value) {
  const name = Array.from(String(value || '').trim().replace(/\s+/g, ' ')).slice(0, MAX_NAME_LEN).join('');
  return name || null;
}

function normalizeCollectTitle(value) {
  const title = Array.from(String(value || '').trim().replace(/\s+/g, ' ')).slice(0, MAX_TITLE_LEN).join('');
  return title || DEFAULT_COLLECT_TITLE;
}

function parseHeroPower(raw) {
  const s = String(raw == null ? '' : raw).trim().replace(/,/g, '').replace(/，/g, '').replace(/\s+/g, '');
  const m = s.match(/^(\d+(?:\.\d+)?)(万|亿|w|W)?$/);
  if (!m) return null;
  let n = Number(m[1]);
  if (!Number.isFinite(n) || n < 0) return null;
  const unit = m[2];
  if (unit === '亿') n *= 1e8;
  else if (unit === '万' || unit === 'w' || unit === 'W') n *= 1e4;
  n = Math.round(n);
  if (n < 1 || n > 1e15) return null;
  return n;
}

function parseStageCount(raw) {
  const s = String(raw == null ? '' : raw).trim().replace(/,/g, '').replace(/，/g, '');
  if (!/^\d+$/.test(s)) return null;
  const n = Number(s);
  if (!Number.isFinite(n) || n < 1 || n > 9999) return null;
  return n;
}

function collectFieldDef(id) {
  return COLLECT_FIELD_DEFS.find((item) => item.id === id) || null;
}

function normalizeCollectFields(value) {
  const raw = Array.isArray(value)
    ? value
    : (typeof value === 'string' ? (() => { try { return JSON.parse(value); } catch (_err) { return []; } })() : []);
  const seen = {};
  const out = [];
  raw.forEach((item) => {
    const id = String(item || '').trim();
    if (!COLLECT_FIELD_IDS.includes(id) || seen[id]) return;
    seen[id] = 1;
    out.push(id);
  });
  return out.length ? out : DEFAULT_COLLECT_FIELDS.slice();
}

function normalizeRankField(fields, rankField) {
  const list = normalizeCollectFields(fields);
  const id = String(rankField || '').trim();
  return list.includes(id) ? id : list[0];
}

function parseCollectValue(fieldId, raw) {
  const def = collectFieldDef(fieldId);
  if (!def) return null;
  return def.kind === 'stage' ? parseStageCount(raw) : parseHeroPower(raw);
}

function parseJsonValue(value, fallback) {
  if (value == null || value === '') return fallback;
  if (typeof value === 'object') return value;
  try { return JSON.parse(String(value)); } catch (_err) { return fallback; }
}

function stringifyJson(value) {
  return JSON.stringify(value == null ? {} : value);
}

function parseEntryStats(row) {
  const stats = parseJsonValue(row && row.stats_json, {}) || {};
  const out = {};
  COLLECT_FIELD_IDS.forEach((id) => {
    const n = Number(stats[id]);
    if (Number.isFinite(n) && n > 0) out[id] = n;
  });
  if (!out.heroPower && Number(row && row.power) > 0) out.heroPower = Number(row.power);
  return out;
}

function parseSubmittedStats(body, fields) {
  const source = (body && typeof body.stats === 'object' && body.stats) ? body.stats : (body || {});
  const stats = {};
  for (let i = 0; i < fields.length; i++) {
    const id = fields[i];
    const raw = source[id] != null ? source[id] : (id === 'heroPower' ? body.power : null);
    const value = parseCollectValue(id, raw);
    if (!value) return { error: id };
    stats[id] = value;
  }
  return { stats };
}

function mapFormConfig(row) {
  const fields = normalizeCollectFields(row && row.fields_json);
  const rankField = normalizeRankField(fields, row && row.rank_field);
  return {
    fields,
    rankField,
    title: normalizeCollectTitle(row && row.title)
  };
}

function mapEntry(row, rankField) {
  if (!row) return null;
  const stats = parseEntryStats(row);
  const rank = rankField || 'heroPower';
  const power = Number(stats[rank] || row.power || 0);
  return {
    id: Number(row.id),
    name: String(row.name || ''),
    power,
    stats,
    createdAt: row.created_at
  };
}

function mountBearpitCollectRoutes(deps) {
  const { app, queryRows, queryOne, execute, pgDatabase, currentUserFromRequest, requireAuth } = deps;
  let tablesReady = false;

  async function addColumn(table, mysqlDdl, pgDdl) {
    if (pgDatabase) {
      await execute(`ALTER TABLE ${table} ADD COLUMN IF NOT EXISTS ${pgDdl}`);
      return;
    }
    try {
      await execute(`ALTER TABLE ${table} ADD COLUMN ${mysqlDdl}`);
    } catch (_err) {}
  }

  async function ensureTables() {
    if (tablesReady) return;
    await execute(pgDatabase ? BEARPIT_COLLECT_FORMS_DDL_PG : BEARPIT_COLLECT_FORMS_DDL_MYSQL);
    await execute(pgDatabase ? BEARPIT_COLLECT_ENTRIES_DDL_PG : BEARPIT_COLLECT_ENTRIES_DDL_MYSQL);
    await addColumn(
      'bearpit_collect_forms',
      "fields_json TEXT NULL",
      "fields_json jsonb"
    );
    await addColumn(
      'bearpit_collect_forms',
      "rank_field VARCHAR(32) NOT NULL DEFAULT 'heroPower'",
      "rank_field varchar(32) NOT NULL DEFAULT 'heroPower'"
    );
    await addColumn(
      'bearpit_collect_entries',
      'stats_json TEXT NULL',
      'stats_json jsonb'
    );
    await addColumn(
      'bearpit_collect_forms',
      'user_id INT NULL',
      'user_id integer NULL'
    );
    await addColumn(
      'bearpit_collect_forms',
      "title VARCHAR(16) NOT NULL DEFAULT '收集名单'",
      "title varchar(16) NOT NULL DEFAULT '收集名单'"
    );
    if (pgDatabase) {
      await execute('CREATE INDEX IF NOT EXISTS idx_bearpit_collect_forms_user ON bearpit_collect_forms (user_id, created_at DESC)');
    } else {
      try {
        await execute('CREATE INDEX idx_bearpit_collect_forms_user ON bearpit_collect_forms (user_id, created_at)');
      } catch (_err) {}
    }
    tablesReady = true;
  }

  async function getForm(key) {
    return queryOne(
      'SELECT collect_key, host_token, created_at, fields_json, rank_field, title, user_id FROM bearpit_collect_forms WHERE collect_key = ? LIMIT 1',
      [key]
    );
  }

  function ownerOk(form, user) {
    return Boolean(form && user && form.user_id != null && Number(form.user_id) === Number(user.id));
  }

  async function hostOk(form, token, req) {
    if (tokenOk(form, token)) return true;
    if (!currentUserFromRequest) return false;
    const user = await currentUserFromRequest(req);
    return ownerOk(form, user);
  }

  async function countUserForms(userId) {
    const row = await queryOne(
      'SELECT COUNT(*) AS n FROM bearpit_collect_forms WHERE user_id = ?',
      [userId]
    );
    return Number(row && row.n) || 0;
  }

  async function insertForm(fields, rankField, title, userId) {
    const hostToken = generateHostToken();
    for (let attempt = 0; attempt < 5; attempt += 1) {
      const candidate = generateShareKey();
      try {
        await execute(
          'INSERT INTO bearpit_collect_forms (collect_key, host_token, created_at, fields_json, rank_field, title, user_id) VALUES (?, ?, CURRENT_TIMESTAMP(3), ?, ?, ?, ?)',
          [candidate, hostToken, stringifyJson(fields), rankField, title, userId == null ? null : Number(userId)]
        );
        return { collectKey: candidate, hostToken };
      } catch (err) {
        if (!String(err?.message || '').toLowerCase().includes('duplicate') && !String(err?.code || '').toUpperCase().includes('DUP')) throw err;
      }
    }
    return null;
  }

  function mapOwnedForm(row, count) {
    const config = mapFormConfig(row);
    return {
      collectKey: String(row.collect_key),
      hostToken: String(row.host_token),
      title: config.title,
      fields: config.fields,
      rankField: config.rankField,
      count: Number(count) || 0,
      createdAt: row.created_at
    };
  }

  async function saveFormConfig(key, fields, rankField) {
    const json = stringifyJson(fields);
    await execute(
      'UPDATE bearpit_collect_forms SET fields_json = ?, rank_field = ? WHERE collect_key = ?',
      [json, rankField, key]
    );
  }

  function tokenOk(form, token) {
    return Boolean(form && token && String(form.host_token) === String(token));
  }

  app.post('/api/bearpit/collect', async (req, res) => {
    try {
      await ensureTables();
      const user = currentUserFromRequest ? await currentUserFromRequest(req) : null;
      const hasConfig = Array.isArray(req.body?.fields);
      const fields = hasConfig ? normalizeCollectFields(req.body?.fields) : DEFAULT_COLLECT_FIELDS.slice();
      const rankField = hasConfig
        ? normalizeRankField(fields, req.body?.rankField || req.body?.rank_field)
        : 'heroPower';
      const title = req.body?.title != null ? normalizeCollectTitle(req.body.title) : null;
      const createNew = Boolean(req.body?.createNew);
      const existingKey = String(req.body?.collectKey || '').trim();
      const existingToken = String(req.body?.hostToken || '').trim();
      if (!createNew && KEY_RE.test(existingKey) && TOKEN_RE.test(existingToken)) {
        const form = await getForm(existingKey);
        if (form && tokenOk(form, existingToken)) {
          const ownerId = form.user_id == null || form.user_id === '' ? null : Number(form.user_id);
          if (user && ownerId && ownerId !== Number(user.id)) {
            return res.status(403).json({ error: 'FORBIDDEN' });
          }
          if (user && !ownerId) {
            await execute(
              'UPDATE bearpit_collect_forms SET user_id = ?, title = ? WHERE collect_key = ?',
              [Number(user.id), title || normalizeCollectTitle(form.title), existingKey]
            );
          } else if (title) {
            await execute('UPDATE bearpit_collect_forms SET title = ? WHERE collect_key = ?', [title, existingKey]);
          }
          if (hasConfig) await saveFormConfig(existingKey, fields, rankField);
          const latest = await getForm(existingKey);
          const config = mapFormConfig(latest || form);
          return res.json({
            ok: true,
            collectKey: existingKey,
            hostToken: existingToken,
            title: config.title,
            fields: hasConfig ? fields : config.fields,
            rankField: hasConfig ? rankField : config.rankField
          });
        }
      }
      const createFields = hasConfig ? fields : DEFAULT_COLLECT_FIELDS.slice();
      const createRank = hasConfig ? rankField : 'heroPower';
      const createTitle = title || DEFAULT_COLLECT_TITLE;
      if (user && (await countUserForms(user.id)) >= MAX_FORMS_PER_USER) {
        return res.status(400).json({ error: 'FORM_LIMIT' });
      }
      const created = await insertForm(createFields, createRank, createTitle, user ? user.id : null);
      if (!created) return res.status(503).json({ error: 'COLLECT_KEY_UNAVAILABLE' });
      return res.json({
        ok: true,
        collectKey: created.collectKey,
        hostToken: created.hostToken,
        title: createTitle,
        fields: createFields,
        rankField: createRank
      });
    } catch (err) {
      console.error('bearpit collect create failed:', err);
      return res.status(500).json({ error: 'INTERNAL_ERROR' });
    }
  });

  app.get('/api/bearpit/collect/mine', async (req, res) => {
    try {
      if (!requireAuth) return res.status(401).json({ error: 'UNAUTHORIZED' });
      const user = await requireAuth(req, res);
      if (!user) return;
      await ensureTables();
      const rows = await queryRows(
        `
        SELECT collect_key, host_token, created_at, fields_json, rank_field, title, user_id
        FROM bearpit_collect_forms
        WHERE user_id = ?
        ORDER BY created_at DESC, collect_key DESC
        `,
        [Number(user.id)]
      );
      const forms = [];
      for (let i = 0; i < rows.length; i++) {
        const row = rows[i];
        const countRow = await queryOne(
          'SELECT COUNT(*) AS n FROM bearpit_collect_entries WHERE collect_key = ?',
          [row.collect_key]
        );
        forms.push(mapOwnedForm(row, countRow && countRow.n));
      }
      return res.json({ ok: true, forms });
    } catch (err) {
      console.error('bearpit collect mine failed:', err);
      return res.status(500).json({ error: 'INTERNAL_ERROR' });
    }
  });

  app.get('/api/bearpit/collect/:key', async (req, res) => {
    try {
      await ensureTables();
      const key = String(req.params.key || '').trim();
      if (!KEY_RE.test(key)) return res.status(400).json({ error: 'BAD_KEY' });
      const form = await getForm(key);
      if (!form) return res.status(404).json({ error: 'NOT_FOUND' });
      const config = mapFormConfig(form);
      const token = String(req.query?.token || req.query?.hostToken || '').trim();
      if (!(await hostOk(form, token, req))) {
        const countRow = await queryOne(
          'SELECT COUNT(*) AS n FROM bearpit_collect_entries WHERE collect_key = ?',
          [key]
        );
        return res.json({
          ok: true,
          open: true,
          count: Number(countRow && countRow.n) || 0,
          fields: config.fields,
          rankField: config.rankField
        });
      }
      const rows = await queryRows(
        `
        SELECT id, name, power, stats_json, created_at
        FROM bearpit_collect_entries
        WHERE collect_key = ?
        ORDER BY power DESC, created_at ASC, id ASC
        `,
        [key]
      );
      return res.json({
        ok: true,
        collectKey: key,
        title: config.title,
        fields: config.fields,
        rankField: config.rankField,
        entries: rows.map((row) => mapEntry(row, config.rankField))
      });
    } catch (err) {
      console.error('bearpit collect get failed:', err);
      return res.status(500).json({ error: 'INTERNAL_ERROR' });
    }
  });

  app.post('/api/bearpit/collect/:key/entries', async (req, res) => {
    try {
      await ensureTables();
      const key = String(req.params.key || '').trim();
      if (!KEY_RE.test(key)) return res.status(400).json({ error: 'BAD_KEY' });
      const form = await getForm(key);
      if (!form) return res.status(404).json({ error: 'NOT_FOUND' });
      const config = mapFormConfig(form);
      const name = normalizeCollectName(req.body?.name);
      if (!name) return res.status(400).json({ error: 'BAD_NAME' });
      const parsed = parseSubmittedStats(req.body, config.fields);
      if (parsed.error) return res.status(400).json({ error: 'BAD_POWER', field: parsed.error });
      const power = parsed.stats[config.rankField];
      const existing = await queryOne(
        'SELECT id FROM bearpit_collect_entries WHERE collect_key = ? AND name = ? LIMIT 1',
        [key, name]
      );
      if (!existing) {
        const countRow = await queryOne(
          'SELECT COUNT(*) AS n FROM bearpit_collect_entries WHERE collect_key = ?',
          [key]
        );
        if ((Number(countRow && countRow.n) || 0) >= MAX_ENTRIES) {
          return res.status(400).json({ error: 'FULL' });
        }
      }
      const statsJson = stringifyJson(parsed.stats);
      if (pgDatabase) {
        await execute(
          `
          INSERT INTO bearpit_collect_entries (collect_key, name, power, stats_json, created_at)
          VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP(3))
          ON CONFLICT (collect_key, name) DO UPDATE SET power = EXCLUDED.power, stats_json = EXCLUDED.stats_json
          `,
          [key, name, power, statsJson]
        );
      } else {
        await execute(
          `
          INSERT INTO bearpit_collect_entries (collect_key, name, power, stats_json, created_at)
          VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP(3))
          ON DUPLICATE KEY UPDATE power = VALUES(power), stats_json = VALUES(stats_json)
          `,
          [key, name, power, statsJson]
        );
      }
      const row = await queryOne(
        'SELECT id, name, power, stats_json, created_at FROM bearpit_collect_entries WHERE collect_key = ? AND name = ? LIMIT 1',
        [key, name]
      );
      return res.json({ ok: true, updated: Boolean(existing), entry: mapEntry(row, config.rankField) });
    } catch (err) {
      console.error('bearpit collect submit failed:', err);
      return res.status(500).json({ error: 'INTERNAL_ERROR' });
    }
  });

  app.post('/api/bearpit/collect/:key/entries/:id/delete', async (req, res) => {
    try {
      await ensureTables();
      const key = String(req.params.key || '').trim();
      const id = Number(req.params.id);
      const token = String(req.body?.hostToken || req.body?.token || '').trim();
      if (!KEY_RE.test(key) || !Number.isFinite(id) || id <= 0) return res.status(400).json({ error: 'BAD_REQUEST' });
      const form = await getForm(key);
      if (!form) return res.status(404).json({ error: 'NOT_FOUND' });
      if (!(await hostOk(form, token, req))) return res.status(403).json({ error: 'FORBIDDEN' });
      await execute('DELETE FROM bearpit_collect_entries WHERE id = ? AND collect_key = ?', [id, key]);
      return res.json({ ok: true });
    } catch (err) {
      console.error('bearpit collect delete failed:', err);
      return res.status(500).json({ error: 'INTERNAL_ERROR' });
    }
  });

  app.post('/api/bearpit/collect/:key/clear', async (req, res) => {
    try {
      await ensureTables();
      const key = String(req.params.key || '').trim();
      const token = String(req.body?.hostToken || req.body?.token || '').trim();
      if (!KEY_RE.test(key)) return res.status(400).json({ error: 'BAD_KEY' });
      const form = await getForm(key);
      if (!form) return res.status(404).json({ error: 'NOT_FOUND' });
      if (!(await hostOk(form, token, req))) return res.status(403).json({ error: 'FORBIDDEN' });
      await execute('DELETE FROM bearpit_collect_entries WHERE collect_key = ?', [key]);
      return res.json({ ok: true });
    } catch (err) {
      console.error('bearpit collect clear failed:', err);
      return res.status(500).json({ error: 'INTERNAL_ERROR' });
    }
  });

  app.post('/api/bearpit/collect/:key/rename', async (req, res) => {
    try {
      await ensureTables();
      const key = String(req.params.key || '').trim();
      const token = String(req.body?.hostToken || req.body?.token || '').trim();
      if (!KEY_RE.test(key)) return res.status(400).json({ error: 'BAD_KEY' });
      const form = await getForm(key);
      if (!form) return res.status(404).json({ error: 'NOT_FOUND' });
      if (!(await hostOk(form, token, req))) return res.status(403).json({ error: 'FORBIDDEN' });
      const title = normalizeCollectTitle(req.body?.title);
      await execute('UPDATE bearpit_collect_forms SET title = ? WHERE collect_key = ?', [title, key]);
      return res.json({ ok: true, title });
    } catch (err) {
      console.error('bearpit collect rename failed:', err);
      return res.status(500).json({ error: 'INTERNAL_ERROR' });
    }
  });

  app.post('/api/bearpit/collect/:key/destroy', async (req, res) => {
    try {
      await ensureTables();
      const key = String(req.params.key || '').trim();
      const token = String(req.body?.hostToken || req.body?.token || '').trim();
      if (!KEY_RE.test(key)) return res.status(400).json({ error: 'BAD_KEY' });
      const form = await getForm(key);
      if (!form) return res.status(404).json({ error: 'NOT_FOUND' });
      if (!(await hostOk(form, token, req))) return res.status(403).json({ error: 'FORBIDDEN' });
      await execute('DELETE FROM bearpit_collect_entries WHERE collect_key = ?', [key]);
      await execute('DELETE FROM bearpit_collect_forms WHERE collect_key = ?', [key]);
      return res.json({ ok: true });
    } catch (err) {
      console.error('bearpit collect destroy failed:', err);
      return res.status(500).json({ error: 'INTERNAL_ERROR' });
    }
  });
}

module.exports = {
  MAX_ENTRIES,
  MAX_NAME_LEN,
  MAX_TITLE_LEN,
  MAX_FORMS_PER_USER,
  DEFAULT_COLLECT_TITLE,
  KEY_RE,
  TOKEN_RE,
  COLLECT_FIELD_DEFS,
  COLLECT_FIELD_IDS,
  DEFAULT_COLLECT_FIELDS,
  BEARPIT_COLLECT_FORMS_DDL_MYSQL,
  BEARPIT_COLLECT_FORMS_DDL_PG,
  BEARPIT_COLLECT_ENTRIES_DDL_MYSQL,
  BEARPIT_COLLECT_ENTRIES_DDL_PG,
  generateHostToken,
  normalizeCollectName,
  normalizeCollectTitle,
  parseHeroPower,
  parseStageCount,
  parseCollectValue,
  normalizeCollectFields,
  normalizeRankField,
  mountBearpitCollectRoutes
};
