'use strict';

const crypto = require('crypto');

const MAX_BACKUPS_PER_USER = 50;
const MAX_TITLE_LEN = 120;
const SHARE_KEY_ALPHABET = 'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789';

function generateShareKey() {
  const bytes = crypto.randomBytes(16);
  let key = '';
  for (const byte of bytes) key += SHARE_KEY_ALPHABET[byte % SHARE_KEY_ALPHABET.length];
  return key;
}

const BEARPIT_BACKUPS_DDL_MYSQL = `
  CREATE TABLE IF NOT EXISTS bearpit_layout_backups (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    title VARCHAR(120) NOT NULL,
    data_json JSON NOT NULL,
    item_count INT NOT NULL DEFAULT 0,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    KEY idx_bearpit_backups_user_created (user_id, created_at)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
`;

const BEARPIT_BACKUPS_DDL_PG = `
  CREATE TABLE IF NOT EXISTS bearpit_layout_backups (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL,
    title varchar(120) NOT NULL,
    data_json jsonb NOT NULL,
    item_count integer NOT NULL DEFAULT 0,
    created_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
  );
  CREATE INDEX IF NOT EXISTS idx_bearpit_backups_user_created ON bearpit_layout_backups (user_id, created_at DESC);
`;

const BEARPIT_SHARES_DDL_MYSQL = `
  CREATE TABLE IF NOT EXISTS bearpit_share_links (
    share_key VARCHAR(16) PRIMARY KEY,
    data_json JSON NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    KEY idx_bearpit_shares_created (created_at)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
`;

const BEARPIT_SHARES_DDL_PG = `
  CREATE TABLE IF NOT EXISTS bearpit_share_links (
    share_key varchar(16) PRIMARY KEY,
    data_json jsonb NOT NULL,
    created_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
  );
  CREATE INDEX IF NOT EXISTS idx_bearpit_shares_created ON bearpit_share_links (created_at DESC);
`;

const BEARPIT_SIMPLE_BACKUPS_DDL_MYSQL = `
  CREATE TABLE IF NOT EXISTS bearpit_simple_layout_backups (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    title VARCHAR(120) NOT NULL,
    data_json JSON NOT NULL,
    item_count INT NOT NULL DEFAULT 0,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    KEY idx_bearpit_simple_backups_user_created (user_id, created_at)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
`;

const BEARPIT_SIMPLE_BACKUPS_DDL_PG = `
  CREATE TABLE IF NOT EXISTS bearpit_simple_layout_backups (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL,
    title varchar(120) NOT NULL,
    data_json jsonb NOT NULL,
    item_count integer NOT NULL DEFAULT 0,
    created_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
  );
  CREATE INDEX IF NOT EXISTS idx_bearpit_simple_backups_user_created ON bearpit_simple_layout_backups (user_id, created_at DESC);
`;

function countLayoutItems(data) {
  if (Array.isArray(data?.items)) return data.items.length;
  if (Array.isArray(data?.placements)) return data.placements.length;
  return Array.isArray(data?.members) ? data.members.length : 0;
}

function normalizeBackupTitle(value) {
  const title = String(value || '').trim();
  if (!title) return null;
  return title.length > MAX_TITLE_LEN ? title.slice(0, MAX_TITLE_LEN) : title;
}

function defaultBackupTitle(date) {
  const d = date instanceof Date ? date : new Date();
  const pad = (n) => String(n).padStart(2, '0');
  return `存档 ${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}`;
}

function parseBackupRow(row) {
  if (!row) return null;
  const data =
    row.data_json && typeof row.data_json === 'object'
      ? row.data_json
      : safeJsonParse(String(row.data_json || 'null'), null);
  return {
    id: Number(row.id),
    title: String(row.title || ''),
    itemCount: Number(row.item_count || 0),
    createdAt: row.created_at,
    data: data || null
  };
}

function safeJsonParse(raw, fallback) {
  try {
    return JSON.parse(raw);
  } catch {
    return fallback;
  }
}

function mountBearpitBackupRoutes(deps) {
  const { app, queryRows, queryOne, execute, requireAuth, pgDatabase } = deps;
  let shareTableReady = false;
  let simpleBackupTableReady = false;

  async function ensureShareTable() {
    if (shareTableReady) return;
    await execute(pgDatabase ? BEARPIT_SHARES_DDL_PG : BEARPIT_SHARES_DDL_MYSQL);
    shareTableReady = true;
  }

  async function ensureSimpleBackupTable() {
    if (simpleBackupTableReady) return;
    await execute(pgDatabase ? BEARPIT_SIMPLE_BACKUPS_DDL_PG : BEARPIT_SIMPLE_BACKUPS_DDL_MYSQL);
    simpleBackupTableReady = true;
  }

  async function trimOldBackups(userId) {
    const rows = await queryRows(
      `
      SELECT id
      FROM bearpit_layout_backups
      WHERE user_id = ?
      ORDER BY created_at DESC, id DESC
      `,
      [Number(userId)]
    );
    if (rows.length <= MAX_BACKUPS_PER_USER) return;
    const stale = rows.slice(MAX_BACKUPS_PER_USER);
    for (const row of stale) {
      await execute('DELETE FROM bearpit_layout_backups WHERE id = ? AND user_id = ?', [
        Number(row.id),
        Number(userId)
      ]);
    }
  }

  async function insertBackup(userId, title, data) {
    const safeTitle = normalizeBackupTitle(title) || defaultBackupTitle();
    const itemCount = countLayoutItems(data);
    if (pgDatabase) {
      await execute(
        `
        INSERT INTO bearpit_layout_backups (user_id, title, data_json, item_count, created_at)
        VALUES (?, ?, ?::jsonb, ?, CURRENT_TIMESTAMP(3))
        `,
        [Number(userId), safeTitle, JSON.stringify(data), itemCount]
      );
    } else {
      await execute(
        `
        INSERT INTO bearpit_layout_backups (user_id, title, data_json, item_count, created_at)
        VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP(3))
        `,
        [Number(userId), safeTitle, JSON.stringify(data), itemCount]
      );
    }
    await trimOldBackups(userId);
    const created = await queryOne(
      `
      SELECT id, title, item_count, created_at
      FROM bearpit_layout_backups
      WHERE user_id = ?
      ORDER BY created_at DESC, id DESC
      LIMIT 1
      `,
      [Number(userId)]
    );
    return created;
  }

  app.get('/api/bearpit/backups', async (req, res) => {
    try {
      const user = await requireAuth(req, res);
      if (!user) return;
      const rows = await queryRows(
        `
        SELECT id, title, item_count, created_at
        FROM bearpit_layout_backups
        WHERE user_id = ?
        ORDER BY created_at DESC, id DESC
        LIMIT ?
        `,
        [Number(user.id), MAX_BACKUPS_PER_USER]
      );
      const backups = rows.map((row) => ({
        id: Number(row.id),
        title: String(row.title || ''),
        itemCount: Number(row.item_count || 0),
        createdAt: row.created_at
      }));
      return res.json({ backups });
    } catch (err) {
      console.error('bearpit backups list failed:', err);
      return res.status(500).json({ error: 'INTERNAL_ERROR' });
    }
  });

  app.post('/api/bearpit/backups', async (req, res) => {
    try {
      const user = await requireAuth(req, res);
      if (!user) return;
      const data = req.body?.data;
      if (!data || typeof data !== 'object') return res.status(400).json({ error: 'BAD_DATA' });
      const title = normalizeBackupTitle(req.body?.title);
      if (!title) return res.status(400).json({ error: 'BAD_TITLE' });
      const created = await insertBackup(user.id, title, data);
      return res.json({
        ok: true,
        backup: {
          id: Number(created.id),
          title: String(created.title || ''),
          itemCount: Number(created.item_count || 0),
          createdAt: created.created_at
        }
      });
    } catch (err) {
      console.error('bearpit backup create failed:', err);
      return res.status(500).json({ error: 'INTERNAL_ERROR' });
    }
  });

  app.get('/api/bearpit/backups/:id', async (req, res) => {
    try {
      const user = await requireAuth(req, res);
      if (!user) return;
      const id = Number(req.params.id);
      if (!Number.isFinite(id) || id <= 0) return res.status(400).json({ error: 'BAD_ID' });
      const row = await queryOne(
        `
        SELECT id, title, data_json, item_count, created_at
        FROM bearpit_layout_backups
        WHERE id = ? AND user_id = ?
        LIMIT 1
        `,
        [id, Number(user.id)]
      );
      if (!row) return res.status(404).json({ error: 'NOT_FOUND' });
      const backup = parseBackupRow(row);
      return res.json({ backup });
    } catch (err) {
      console.error('bearpit backup get failed:', err);
      return res.status(500).json({ error: 'INTERNAL_ERROR' });
    }
  });

  app.delete('/api/bearpit/backups/:id', async (req, res) => {
    try {
      const user = await requireAuth(req, res);
      if (!user) return;
      const id = Number(req.params.id);
      if (!Number.isFinite(id) || id <= 0) return res.status(400).json({ error: 'BAD_ID' });
      const result = await execute(
        'DELETE FROM bearpit_layout_backups WHERE id = ? AND user_id = ?',
        [id, Number(user.id)]
      );
      const deleted = pgDatabase ? result?.rowCount > 0 : result?.affectedRows > 0;
      if (!deleted) return res.status(404).json({ error: 'NOT_FOUND' });
      return res.json({ ok: true });
    } catch (err) {
      console.error('bearpit backup delete failed:', err);
      return res.status(500).json({ error: 'INTERNAL_ERROR' });
    }
  });

  app.get('/api/bearpit-simple/backups', async (req, res) => {
    try {
      const user = await requireAuth(req, res);
      if (!user) return;
      await ensureSimpleBackupTable();
      const rows = await queryRows('SELECT id, title, item_count, created_at FROM bearpit_simple_layout_backups WHERE user_id = ? ORDER BY created_at DESC, id DESC LIMIT ?', [Number(user.id), MAX_BACKUPS_PER_USER]);
      return res.json({ backups: rows.map((row) => ({ id: Number(row.id), title: String(row.title || ''), itemCount: Number(row.item_count || 0), createdAt: row.created_at })) });
    } catch (err) {
      console.error('bearpit simple backups list failed:', err);
      return res.status(500).json({ error: 'INTERNAL_ERROR' });
    }
  });

  app.post('/api/bearpit-simple/backups', async (req, res) => {
    try {
      const user = await requireAuth(req, res);
      if (!user) return;
      await ensureSimpleBackupTable();
      const data = req.body?.data;
      const title = normalizeBackupTitle(req.body?.title);
      if (!data || typeof data !== 'object' || !data.grid || !Array.isArray(data.placements)) return res.status(400).json({ error: 'BAD_DATA' });
      if (!title) return res.status(400).json({ error: 'BAD_TITLE' });
      const itemCount = countLayoutItems(data);
      await execute(
        pgDatabase
          ? 'INSERT INTO bearpit_simple_layout_backups (user_id, title, data_json, item_count, created_at) VALUES (?, ? , ?::jsonb, ?, CURRENT_TIMESTAMP(3))'
          : 'INSERT INTO bearpit_simple_layout_backups (user_id, title, data_json, item_count, created_at) VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP(3))',
        [Number(user.id), title, JSON.stringify(data), itemCount]
      );
      const created = await queryOne('SELECT id, title, item_count, created_at FROM bearpit_simple_layout_backups WHERE user_id = ? ORDER BY created_at DESC, id DESC LIMIT 1', [Number(user.id)]);
      return res.json({ ok: true, backup: { id: Number(created.id), title: String(created.title || title), itemCount: Number(created.item_count || itemCount), createdAt: created.created_at } });
    } catch (err) {
      console.error('bearpit simple backup create failed:', err);
      return res.status(500).json({ error: 'INTERNAL_ERROR' });
    }
  });

  app.get('/api/bearpit-simple/backups/:id', async (req, res) => {
    try {
      const user = await requireAuth(req, res);
      if (!user) return;
      await ensureSimpleBackupTable();
      const id = Number(req.params.id);
      if (!Number.isFinite(id) || id <= 0) return res.status(400).json({ error: 'BAD_ID' });
      const row = await queryOne('SELECT id, title, data_json, item_count, created_at FROM bearpit_simple_layout_backups WHERE id = ? AND user_id = ? LIMIT 1', [id, Number(user.id)]);
      if (!row) return res.status(404).json({ error: 'NOT_FOUND' });
      const data = row.data_json && typeof row.data_json === 'object' ? row.data_json : safeJsonParse(String(row.data_json || 'null'), null);
      return res.json({ backup: { id: Number(row.id), title: String(row.title || ''), data, itemCount: Number(row.item_count || 0), createdAt: row.created_at } });
    } catch (err) {
      console.error('bearpit simple backup get failed:', err);
      return res.status(500).json({ error: 'INTERNAL_ERROR' });
    }
  });

  app.post('/api/bearpit/shares', async (req, res) => {
    try {
      const user = await requireAuth(req, res);
      if (!user) return;
      await ensureShareTable();
      const data = req.body?.data;
      if (!data || typeof data !== 'object' || !data.grid || !Array.isArray(data.placements)) {
        return res.status(400).json({ error: 'BAD_DATA' });
      }
      let shareKey = null;
      for (let attempt = 0; attempt < 5; attempt += 1) {
        const candidate = generateShareKey();
        try {
          await execute(
            pgDatabase
              ? 'INSERT INTO bearpit_share_links (share_key, data_json, created_at) VALUES (?, ?::jsonb, CURRENT_TIMESTAMP(3))'
              : 'INSERT INTO bearpit_share_links (share_key, data_json, created_at) VALUES (?, ?, CURRENT_TIMESTAMP(3))',
            [candidate, JSON.stringify(data)]
          );
          shareKey = candidate;
          break;
        } catch (err) {
          if (!String(err?.message || '').toLowerCase().includes('duplicate') && !String(err?.code || '').toUpperCase().includes('DUP')) throw err;
        }
      }
      if (!shareKey) return res.status(503).json({ error: 'SHARE_KEY_UNAVAILABLE' });
      return res.json({ ok: true, shareKey });
    } catch (err) {
      console.error('bearpit share create failed:', err);
      return res.status(500).json({ error: 'INTERNAL_ERROR' });
    }
  });

  app.get('/api/bearpit/shares/:key', async (req, res) => {
    try {
      await ensureShareTable();
      const key = String(req.params.key || '').trim();
      if (!/^[A-Za-z0-9]{16}$/.test(key)) return res.status(400).json({ error: 'BAD_KEY' });
      const row = await queryOne('SELECT share_key, data_json FROM bearpit_share_links WHERE share_key = ? LIMIT 1', [key]);
      if (!row) return res.status(404).json({ error: 'NOT_FOUND' });
      const data = row.data_json && typeof row.data_json === 'object' ? row.data_json : safeJsonParse(String(row.data_json || 'null'), null);
      if (!data) return res.status(410).json({ error: 'BAD_DATA' });
      return res.json({ data });
    } catch (err) {
      console.error('bearpit share get failed:', err);
      return res.status(500).json({ error: 'INTERNAL_ERROR' });
    }
  });

  return { insertBackup, defaultBackupTitle };
}

module.exports = {
  BEARPIT_BACKUPS_DDL_MYSQL,
  BEARPIT_BACKUPS_DDL_PG,
  BEARPIT_SHARES_DDL_MYSQL,
  BEARPIT_SHARES_DDL_PG,
  BEARPIT_SIMPLE_BACKUPS_DDL_MYSQL,
  BEARPIT_SIMPLE_BACKUPS_DDL_PG,
  mountBearpitBackupRoutes,
  generateShareKey,
  countLayoutItems,
  normalizeBackupTitle,
  defaultBackupTitle
};
