'use strict';

const { addDays, compareDates } = require('./calendar-domain');

const PRESET_CATEGORIES = [
  { code: 'regular', name: '常规', color: '#f1c995', sortOrder: 10 },
  { code: 'kingdom', name: '王国活动', color: '#edb28d', sortOrder: 20 },
  { code: 'leaderboard', name: '小榜', color: '#d7b3cf', sortOrder: 30 },
  { code: 'cross-server', name: '跨服活动', color: '#9fc7c0', sortOrder: 40 },
  { code: 'limited', name: '限定活动', color: '#e9a3a3', sortOrder: 50 }
];

const CALENDAR_DDL_MYSQL = [
  `CREATE TABLE IF NOT EXISTS calendar_categories (
    id INT AUTO_INCREMENT PRIMARY KEY,
    code VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(80) NOT NULL UNIQUE,
    color VARCHAR(16) NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
  `CREATE TABLE IF NOT EXISTS calendar_schedule_definitions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    legacy_original_id VARCHAR(64) NULL UNIQUE,
    category_id INT NOT NULL,
    name VARCHAR(120) NOT NULL,
    schedule_type VARCHAR(24) NOT NULL,
    composite_layout VARCHAR(24) NULL,
    start_date VARCHAR(10) NOT NULL,
    end_date VARCHAR(10) NOT NULL,
    legacy_dates_json MEDIUMTEXT NULL,
    start_time VARCHAR(10) NULL,
    end_time VARCHAR(10) NULL,
    color VARCHAR(16) NULL,
    description TEXT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    font_bold TINYINT(1) NOT NULL DEFAULT 0,
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    recurrence_unit VARCHAR(16) NULL,
    recurrence_interval INT NULL,
    weekdays_json TEXT NULL,
    month_day INT NULL,
    recurrence_end_type VARCHAR(16) NULL,
    recurrence_until VARCHAR(10) NULL,
    recurrence_count INT NULL,
    created_by INT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    KEY idx_calendar_definition_range (start_date,end_date),
    KEY idx_calendar_definition_category (category_id,enabled),
    KEY idx_calendar_definition_updated (updated_at)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
  `CREATE TABLE IF NOT EXISTS calendar_schedule_items (
    id INT AUTO_INCREMENT PRIMARY KEY,
    schedule_id INT NOT NULL,
    name VARCHAR(120) NOT NULL,
    description TEXT NULL,
    color VARCHAR(16) NULL,
    sort_order INT NOT NULL DEFAULT 0,
    highlighted TINYINT(1) NOT NULL DEFAULT 0,
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    date_mode VARCHAR(24) NOT NULL,
    start_offset_days INT NULL,
    end_offset_days INT NULL,
    selected_offsets_json TEXT NULL,
    duration_days INT NULL,
    start_time VARCHAR(10) NULL,
    end_time VARCHAR(10) NULL,
    recurrence_unit VARCHAR(16) NULL,
    recurrence_interval INT NULL,
    weekdays_json TEXT NULL,
    month_day INT NULL,
    recurrence_end_type VARCHAR(16) NULL,
    recurrence_until_offset INT NULL,
    recurrence_count INT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    KEY idx_calendar_item_schedule (schedule_id,sort_order,id)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
  `CREATE TABLE IF NOT EXISTS calendar_schedule_exceptions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    schedule_id INT NOT NULL,
    occurrence_date VARCHAR(10) NOT NULL,
    scope VARCHAR(16) NOT NULL,
    name VARCHAR(120) NOT NULL,
    color VARCHAR(16) NULL,
    font_bold TINYINT(1) NOT NULL DEFAULT 0,
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    UNIQUE KEY uq_calendar_exception (schedule_id,occurrence_date,scope),
    KEY idx_calendar_exception_schedule (schedule_id,occurrence_date)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`
];

const CALENDAR_DDL_PG = [
  `CREATE TABLE IF NOT EXISTS calendar_categories (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(64) NOT NULL UNIQUE,
    name varchar(80) NOT NULL UNIQUE,
    color varchar(16) NOT NULL,
    sort_order integer NOT NULL DEFAULT 0,
    enabled boolean NOT NULL DEFAULT true,
    created_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
  )`,
  `CREATE TABLE IF NOT EXISTS calendar_schedule_definitions (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_original_id varchar(64) NULL UNIQUE,
    category_id integer NOT NULL,
    name varchar(120) NOT NULL,
    schedule_type varchar(24) NOT NULL,
    composite_layout varchar(24) NULL,
    start_date varchar(10) NOT NULL,
    end_date varchar(10) NOT NULL,
    legacy_dates_json text NULL,
    start_time varchar(10) NULL,
    end_time varchar(10) NULL,
    color varchar(16) NULL,
    description text NULL,
    sort_order integer NOT NULL DEFAULT 0,
    font_bold boolean NOT NULL DEFAULT false,
    enabled boolean NOT NULL DEFAULT true,
    recurrence_unit varchar(16) NULL,
    recurrence_interval integer NULL,
    weekdays_json text NULL,
    month_day integer NULL,
    recurrence_end_type varchar(16) NULL,
    recurrence_until varchar(10) NULL,
    recurrence_count integer NULL,
    created_by integer NULL,
    created_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
  )`,
  'CREATE INDEX IF NOT EXISTS idx_calendar_definition_range ON calendar_schedule_definitions (start_date,end_date)',
  'CREATE INDEX IF NOT EXISTS idx_calendar_definition_category ON calendar_schedule_definitions (category_id,enabled)',
  'CREATE INDEX IF NOT EXISTS idx_calendar_definition_updated ON calendar_schedule_definitions (updated_at)',
  `CREATE TABLE IF NOT EXISTS calendar_schedule_items (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_id integer NOT NULL,
    name varchar(120) NOT NULL,
    description text NULL,
    color varchar(16) NULL,
    sort_order integer NOT NULL DEFAULT 0,
    highlighted boolean NOT NULL DEFAULT false,
    enabled boolean NOT NULL DEFAULT true,
    date_mode varchar(24) NOT NULL,
    start_offset_days integer NULL,
    end_offset_days integer NULL,
    selected_offsets_json text NULL,
    duration_days integer NULL,
    start_time varchar(10) NULL,
    end_time varchar(10) NULL,
    recurrence_unit varchar(16) NULL,
    recurrence_interval integer NULL,
    weekdays_json text NULL,
    month_day integer NULL,
    recurrence_end_type varchar(16) NULL,
    recurrence_until_offset integer NULL,
    recurrence_count integer NULL,
    created_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
  )`,
  'CREATE INDEX IF NOT EXISTS idx_calendar_item_schedule ON calendar_schedule_items (schedule_id,sort_order,id)',
  `CREATE TABLE IF NOT EXISTS calendar_schedule_exceptions (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_id integer NOT NULL,
    occurrence_date varchar(10) NOT NULL,
    scope varchar(16) NOT NULL,
    name varchar(120) NOT NULL,
    color varchar(16) NULL,
    font_bold boolean NOT NULL DEFAULT false,
    enabled boolean NOT NULL DEFAULT true,
    created_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    UNIQUE (schedule_id,occurrence_date,scope)
  )`,
  'CREATE INDEX IF NOT EXISTS idx_calendar_exception_schedule ON calendar_schedule_exceptions (schedule_id,occurrence_date)'
];

const ULID_ALPHABET = '0123456789abcdefghjkmnpqrstvwxyz';

function createCustomCategoryCode(random, now) {
  const rng = typeof random === 'function' ? random : Math.random;
  let time = Number(typeof now === 'function' ? now() : Date.now());
  let encodedTime = '';
  for (let index = 0; index < 10; index += 1) {
    encodedTime = ULID_ALPHABET[time % 32] + encodedTime;
    time = Math.floor(time / 32);
  }
  let entropy = '';
  for (let index = 0; index < 16; index += 1) entropy += ULID_ALPHABET[Math.floor(rng() * 32) % 32];
  return `custom-${encodedTime}${entropy}`;
}

function jsonParse(value, fallback) {
  if (Array.isArray(value) || value && typeof value === 'object') return value;
  try { return JSON.parse(value); } catch (_error) { return fallback; }
}

function bool(value) {
  return value === true || value === 1 || value === '1';
}

function mapLegacyGroup(rows) {
  const list = (Array.isArray(rows) ? rows : []).slice().sort((a, b) => String(a.date).localeCompare(String(b.date)));
  const dates = Array.from(new Set(list.map((row) => String(row.date))));
  let scheduleType = dates.length === 1 ? 'single' : 'continuous';
  for (let index = 1; index < dates.length; index += 1) {
    if (dates[index] !== addDays(dates[index - 1], 1)) scheduleType = 'date-list';
  }
  const first = list[0] || {};
  return {
    legacyOriginalId: first.original_id || first.originalId || null,
    name: first.name || '未命名日程',
    scheduleType,
    startDate: dates[0],
    endDate: dates[dates.length - 1],
    legacyDates: scheduleType === 'date-list' ? dates : null,
    startTime: first.start_time || first.startTime || '',
    endTime: first.end_time || first.endTime || '',
    color: first.color || null,
    description: first.description || '',
    createdBy: first.created_by || first.createdBy || null
  };
}

async function seedCategories(adapter) {
  for (const category of PRESET_CATEGORIES) {
    if (adapter.pgDatabase) {
      await adapter.execute(
        `INSERT INTO calendar_categories (code,name,color,sort_order,enabled,updated_at)
         VALUES (?,?,?,?,true,CURRENT_TIMESTAMP(3)) ON CONFLICT (code) DO NOTHING`,
        [category.code, category.name, category.color, category.sortOrder]
      );
    } else {
      await adapter.execute(
        `INSERT IGNORE INTO calendar_categories (code,name,color,sort_order,enabled,updated_at)
         VALUES (?,?,?,?,1,CURRENT_TIMESTAMP(3))`,
        [category.code, category.name, category.color, category.sortOrder]
      );
    }
  }
}

async function migrateLegacyCalendarSchedules(adapter) {
  const regular = await adapter.queryOne('SELECT id,code FROM calendar_categories WHERE code = ? LIMIT 1', ['regular']);
  if (!regular) throw new Error('REGULAR_CATEGORY_MISSING');
  let rows = [];
  try {
    rows = await adapter.queryRows(
      `SELECT original_id,name,date,start_time,end_time,color,description,created_by
       FROM calendar_schedules ORDER BY original_id,date,id`
    );
  } catch (error) {
    if (/does not exist|doesn't exist|no such table/i.test(String(error && error.message || error))) return;
    throw error;
  }
  const groups = new Map();
  for (const row of rows) {
    const key = String(row.original_id || '');
    if (!groups.has(key)) groups.set(key, []);
    groups.get(key).push(row);
  }
  for (const [legacyId, groupRows] of groups) {
    if (!legacyId) continue;
    const exists = await adapter.queryOne('SELECT id FROM calendar_schedule_definitions WHERE legacy_original_id = ? LIMIT 1', [legacyId]);
    if (exists) continue;
    const value = mapLegacyGroup(groupRows);
    await adapter.runInTransaction(async (tx) => {
      await tx.execute(
        `INSERT INTO calendar_schedule_definitions
         (legacy_original_id,category_id,name,schedule_type,composite_layout,start_date,end_date,legacy_dates_json,start_time,end_time,color,description,enabled,created_by,updated_at)
         VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?, ?,CURRENT_TIMESTAMP(3))`,
        [legacyId, Number(regular.id), value.name, value.scheduleType, null, value.startDate, value.endDate,
          value.legacyDates ? JSON.stringify(value.legacyDates) : null, value.startTime || null, value.endTime || null,
          value.color, value.description || null, adapter.pgDatabase ? true : 1, value.createdBy]
      );
    });
  }
}

async function ensureCalendarSchema(adapter) {
  for (const sql of adapter.pgDatabase ? CALENDAR_DDL_PG : CALENDAR_DDL_MYSQL) await adapter.execute(sql);
  for (const column of [
    `sort_order ${adapter.pgDatabase ? 'integer' : 'INT'} NOT NULL DEFAULT 0`,
    `font_bold ${adapter.pgDatabase ? 'boolean' : 'TINYINT(1)'} NOT NULL DEFAULT ${adapter.pgDatabase ? 'false' : '0'}`
  ]) {
    try {
      await adapter.execute(`ALTER TABLE calendar_schedule_definitions ADD COLUMN ${column}`);
    } catch (error) {
      if (!/duplicate|already exists|column .* exists/i.test(String(error && error.message || error))) throw error;
    }
  }
  await seedCategories(adapter);
  await migrateLegacyCalendarSchedules(adapter);
}

function mapCategoryRow(row) {
  return {
    id: Number(row.id),
    code: row.code,
    name: row.name,
    color: row.color,
    sortOrder: Number(row.sort_order || 0),
    enabled: bool(row.enabled)
  };
}

function mapItemRow(row) {
  return {
    id: Number(row.id),
    scheduleId: Number(row.schedule_id),
    name: row.name,
    description: row.description || '',
    color: row.color || null,
    sortOrder: Number(row.sort_order || 0),
    highlighted: bool(row.highlighted),
    enabled: bool(row.enabled),
    dateMode: row.date_mode,
    startOffsetDays: row.start_offset_days === null ? null : Number(row.start_offset_days),
    endOffsetDays: row.end_offset_days === null ? null : Number(row.end_offset_days),
    selectedOffsets: jsonParse(row.selected_offsets_json, []),
    durationDays: row.duration_days === null ? null : Number(row.duration_days),
    startTime: row.start_time || '',
    endTime: row.end_time || '',
    recurrenceUnit: row.recurrence_unit || null,
    recurrenceInterval: row.recurrence_interval === null ? null : Number(row.recurrence_interval),
    weekdays: jsonParse(row.weekdays_json, []),
    monthDay: row.month_day === null ? null : Number(row.month_day),
    recurrenceEndType: row.recurrence_end_type || null,
    recurrenceUntilOffset: row.recurrence_until_offset === null ? null : Number(row.recurrence_until_offset),
    recurrenceCount: row.recurrence_count === null ? null : Number(row.recurrence_count)
  };
}

function mapDefinitionRow(row, category, items) {
  return {
    id: Number(row.id),
    legacyOriginalId: row.legacy_original_id || null,
    originalId: row.legacy_original_id || String(row.id),
    category,
    categoryId: Number(row.category_id),
    name: row.name,
    scheduleType: row.schedule_type,
    compositeLayout: row.composite_layout || null,
    startDate: row.start_date,
    endDate: row.end_date,
    legacyDates: jsonParse(row.legacy_dates_json, []),
    startTime: row.start_time || '',
    endTime: row.end_time || '',
    color: row.color || null,
    description: row.description || '',
    sortOrder: Number(row.sort_order || 0),
    fontBold: bool(row.font_bold),
    enabled: bool(row.enabled),
    recurrenceUnit: row.recurrence_unit || null,
    recurrenceInterval: row.recurrence_interval === null ? null : Number(row.recurrence_interval),
    weekdays: jsonParse(row.weekdays_json, []),
    monthDay: row.month_day === null ? null : Number(row.month_day),
    recurrenceEndType: row.recurrence_end_type || null,
    recurrenceUntil: row.recurrence_until || null,
    recurrenceCount: row.recurrence_count === null ? null : Number(row.recurrence_count),
    items: items || [],
    exceptions: []
  };
}

function createCalendarStore(adapter) {
  async function listCategories() {
    const rows = await adapter.queryRows('SELECT id,code,name,color,sort_order,enabled FROM calendar_categories ORDER BY sort_order,name,id');
    return rows.map(mapCategoryRow);
  }

  async function getCategoryById(id) {
    const row = await adapter.queryOne('SELECT id,code,name,color,sort_order,enabled FROM calendar_categories WHERE id = ? LIMIT 1', [id]);
    return row ? mapCategoryRow(row) : null;
  }

  async function listDefinitions(includeDisabled) {
    const enabledValue = adapter.pgDatabase ? 'true' : '1';
    const where = includeDisabled ? '' : `WHERE d.enabled = ${enabledValue} AND c.enabled = ${enabledValue}`;
    const rows = await adapter.queryRows(
      `SELECT d.*,c.code AS category_code,c.name AS category_name,c.color AS category_color,c.sort_order AS category_sort_order,c.enabled AS category_enabled
       FROM calendar_schedule_definitions d JOIN calendar_categories c ON c.id=d.category_id ${where}
       ORDER BY c.sort_order,d.sort_order,d.start_date,d.id`
    );
    const ids = rows.map((row) => Number(row.id));
    const itemRows = ids.length ? await adapter.queryRows(`SELECT * FROM calendar_schedule_items WHERE schedule_id IN (${ids.map(() => '?').join(',')}) ORDER BY schedule_id,sort_order,id`, ids) : [];
    const exceptionRows = ids.length ? await adapter.queryRows(`SELECT * FROM calendar_schedule_exceptions WHERE schedule_id IN (${ids.map(() => '?').join(',')}) ORDER BY schedule_id,occurrence_date,id`, ids) : [];
    const itemMap = new Map();
    for (const row of itemRows) {
      const key = Number(row.schedule_id);
      if (!itemMap.has(key)) itemMap.set(key, []);
      itemMap.get(key).push(mapItemRow(row));
    }
    const exceptionMap = new Map();
    for (const row of exceptionRows) {
      const key = Number(row.schedule_id);
      if (!exceptionMap.has(key)) exceptionMap.set(key, []);
      exceptionMap.get(key).push({ id: Number(row.id), scheduleId: key, occurrenceDate: row.occurrence_date, scope: row.scope, name: row.name, color: row.color || null, fontBold: bool(row.font_bold), enabled: bool(row.enabled) });
    }
    return rows.map((row) => {
      const definition = mapDefinitionRow(row, mapCategoryRow({
      id: row.category_id,
      code: row.category_code,
      name: row.category_name,
      color: row.category_color,
      sort_order: row.category_sort_order,
      enabled: row.category_enabled
      }), itemMap.get(Number(row.id)) || []);
      definition.exceptions = exceptionMap.get(Number(row.id)) || [];
      return definition;
    });
  }

  async function createCategory(input, meta) {
    const existing = await adapter.queryOne('SELECT id FROM calendar_categories WHERE name = ? LIMIT 1', [input.name]);
    if (existing) return { error: 'CATEGORY_NAME_EXISTS' };
    for (let attempt = 0; attempt < 5; attempt += 1) {
      const code = createCustomCategoryCode(meta && meta.random, meta && meta.now);
      try {
        const params = [code, input.name, input.color, Number(input.sortOrder || 0)];
        const result = adapter.pgDatabase
          ? await adapter.queryOne('INSERT INTO calendar_categories (code,name,color,sort_order,enabled,updated_at) VALUES (?,?,?,?,true,CURRENT_TIMESTAMP(3)) RETURNING id', params)
          : await adapter.execute('INSERT INTO calendar_categories (code,name,color,sort_order,enabled,updated_at) VALUES (?,?,?,?,1,CURRENT_TIMESTAMP(3))', params);
        return getCategoryById(Number(result.id || result.insertId));
      } catch (error) {
        const message = String(error && (error.code || error.message) || error);
        if (/name|category.*name/i.test(message)) return { error: 'CATEGORY_NAME_EXISTS' };
        if (!/duplicate|unique|23505|ER_DUP_ENTRY/i.test(message)) throw error;
      }
    }
    return { error: 'CATEGORY_CODE_GENERATION_FAILED' };
  }

  async function getCategoryByCode(code) {
    const row = await adapter.queryOne('SELECT id,code,name,color,sort_order,enabled FROM calendar_categories WHERE code = ? LIMIT 1', [code]);
    return row ? mapCategoryRow(row) : null;
  }

  async function updateCategory(id, input) {
    const duplicate = await adapter.queryOne('SELECT id FROM calendar_categories WHERE name = ? AND id <> ? LIMIT 1', [input.name, id]);
    if (duplicate) return { error: 'CATEGORY_NAME_EXISTS' };
    const result = await adapter.execute('UPDATE calendar_categories SET name=?,color=?,updated_at=CURRENT_TIMESTAMP(3) WHERE id=?', [input.name, input.color, id]);
    if (!Number(result.affectedRows === undefined ? 1 : result.affectedRows)) return null;
    return getCategoryById(id);
  }

  async function reorderCategories(ids) {
    const categories = await listCategories();
    if (ids.length !== categories.length || new Set(ids).size !== ids.length || categories.some((category) => !ids.includes(category.id))) return { error: 'BAD_CATEGORY_ORDER' };
    await adapter.runInTransaction(async (tx) => {
      for (let index = 0; index < ids.length; index += 1) {
        await tx.execute('UPDATE calendar_categories SET sort_order=?,updated_at=CURRENT_TIMESTAMP(3) WHERE id=?', [(index + 1) * 10, ids[index]]);
      }
    });
    return listCategories();
  }

  async function setCategoryStatus(id, enabled) {
    const result = await adapter.execute('UPDATE calendar_categories SET enabled=?,updated_at=CURRENT_TIMESTAMP(3) WHERE id=?', [adapter.pgDatabase ? !!enabled : enabled ? 1 : 0, id]);
    if (!Number(result.affectedRows === undefined ? 1 : result.affectedRows)) return null;
    return getCategoryById(id);
  }

  function definitionParams(value, actorId) {
    const recurrence = value.recurrence || {};
    return [
      value.legacyOriginalId || null,
      value.categoryId,
      value.name,
      value.scheduleType,
      value.compositeLayout || null,
      value.startDate,
      value.endDate,
      value.legacyDates && value.legacyDates.length ? JSON.stringify(value.legacyDates) : null,
      value.startTime || null,
      value.endTime || null,
      value.color || null,
      value.description || null,
      Number(value.sortOrder || 0),
      adapter.pgDatabase ? value.fontBold === true : value.fontBold === true ? 1 : 0,
      adapter.pgDatabase ? value.enabled !== false : value.enabled === false ? 0 : 1,
      value.recurrenceUnit || recurrence.unit || null,
      value.recurrenceInterval || recurrence.interval || null,
      value.weekdays && value.weekdays.length ? JSON.stringify(value.weekdays) : recurrence.weekdays && recurrence.weekdays.length ? JSON.stringify(recurrence.weekdays) : null,
      value.monthDay || recurrence.monthDay || null,
      value.recurrenceEndType || recurrence.endType || null,
      value.recurrenceUntil || recurrence.until || null,
      value.recurrenceCount || recurrence.count || null,
      actorId || null
    ];
  }

  function itemParams(scheduleId, item) {
    const recurrence = item.recurrence || {};
    return [
      scheduleId,
      item.name,
      item.description || null,
      item.color || null,
      Number(item.sortOrder || 0),
      adapter.pgDatabase ? item.highlighted === true : item.highlighted === true ? 1 : 0,
      adapter.pgDatabase ? item.enabled !== false : item.enabled === false ? 0 : 1,
      item.dateMode,
      item.startOffsetDays === undefined ? null : item.startOffsetDays,
      item.endOffsetDays === undefined ? null : item.endOffsetDays,
      item.selectedOffsets && item.selectedOffsets.length ? JSON.stringify(item.selectedOffsets) : null,
      item.durationDays || null,
      item.startTime || null,
      item.endTime || null,
      item.recurrenceUnit || recurrence.unit || null,
      item.recurrenceInterval || recurrence.interval || null,
      item.weekdays && item.weekdays.length ? JSON.stringify(item.weekdays) : recurrence.weekdays && recurrence.weekdays.length ? JSON.stringify(recurrence.weekdays) : null,
      item.monthDay || recurrence.monthDay || null,
      item.recurrenceEndType || recurrence.endType || null,
      item.recurrenceUntilOffset === undefined || item.recurrenceUntilOffset === null ? recurrence.untilOffset === undefined ? null : recurrence.untilOffset : item.recurrenceUntilOffset,
      item.recurrenceCount || recurrence.count || null
    ];
  }

  async function insertAndGetId(tx, sql, params) {
    if (adapter.pgDatabase) {
      const row = await tx.queryOne(`${sql} RETURNING id`, params);
      return Number(row.id);
    }
    const result = await tx.execute(sql, params);
    return Number(result.insertId);
  }

  async function insertItem(tx, scheduleId, item) {
    return insertAndGetId(tx,
      `INSERT INTO calendar_schedule_items
       (schedule_id,name,description,color,sort_order,highlighted,enabled,date_mode,start_offset_days,end_offset_days,selected_offsets_json,duration_days,start_time,end_time,recurrence_unit,recurrence_interval,weekdays_json,month_day,recurrence_end_type,recurrence_until_offset,recurrence_count,updated_at)
       VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP(3))`,
      itemParams(scheduleId, item));
  }

  async function createDefinition(value, meta) {
    const id = await adapter.runInTransaction(async (tx) => {
      const definitionId = await insertAndGetId(tx,
        `INSERT INTO calendar_schedule_definitions
         (legacy_original_id,category_id,name,schedule_type,composite_layout,start_date,end_date,legacy_dates_json,start_time,end_time,color,description,sort_order,font_bold,enabled,recurrence_unit,recurrence_interval,weekdays_json,month_day,recurrence_end_type,recurrence_until,recurrence_count,created_by,updated_at)
         VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP(3))`,
        definitionParams(value, meta && meta.actorId));
      for (const item of value.items || []) await insertItem(tx, definitionId, item);
      return definitionId;
    });
    return getDefinition(id);
  }

  async function getDefinition(id) {
    const definitions = await listDefinitions(true);
    return definitions.find((definition) => definition.id === Number(id)) || null;
  }

  async function getDefinitionByLegacyId(legacyId) {
    const castType = adapter.pgDatabase ? 'TEXT' : 'CHAR';
    const row = await adapter.queryOne(`SELECT id FROM calendar_schedule_definitions WHERE legacy_original_id = ? OR CAST(id AS ${castType}) = ? LIMIT 1`, [legacyId, legacyId]);
    return row ? getDefinition(Number(row.id)) : null;
  }

  async function replaceDefinition(id, value, meta) {
    const current = await getDefinition(id);
    if (!current) return null;
    const existingIds = new Set((current.items || []).map((item) => item.id));
    for (const item of value.items || []) {
      if (item.id && !existingIds.has(Number(item.id))) return { error: 'BAD_ITEM_ID' };
    }
    await adapter.runInTransaction(async (tx) => {
      if (meta && meta.clearExceptions) await tx.execute('DELETE FROM calendar_schedule_exceptions WHERE schedule_id=?', [id]);
      const params = definitionParams({ ...value, legacyOriginalId: value.legacyOriginalId || current.legacyOriginalId }, meta && meta.actorId);
      await tx.execute(
        `UPDATE calendar_schedule_definitions SET
         legacy_original_id=?,category_id=?,name=?,schedule_type=?,composite_layout=?,start_date=?,end_date=?,legacy_dates_json=?,start_time=?,end_time=?,color=?,description=?,sort_order=?,font_bold=?,enabled=?,recurrence_unit=?,recurrence_interval=?,weekdays_json=?,month_day=?,recurrence_end_type=?,recurrence_until=?,recurrence_count=?,created_by=?,updated_at=CURRENT_TIMESTAMP(3)
         WHERE id=?`,
        [...params, id]);
      const submittedIds = new Set();
      for (const item of value.items || []) {
        if (item.id) {
          submittedIds.add(Number(item.id));
          await tx.execute(
            `UPDATE calendar_schedule_items SET name=?,description=?,color=?,sort_order=?,highlighted=?,enabled=?,date_mode=?,start_offset_days=?,end_offset_days=?,selected_offsets_json=?,duration_days=?,start_time=?,end_time=?,recurrence_unit=?,recurrence_interval=?,weekdays_json=?,month_day=?,recurrence_end_type=?,recurrence_until_offset=?,recurrence_count=?,updated_at=CURRENT_TIMESTAMP(3) WHERE id=? AND schedule_id=?`,
            [...itemParams(id, item).slice(1), Number(item.id), id]);
        } else {
          await insertItem(tx, id, item);
        }
      }
      const removed = [...existingIds].filter((itemId) => !submittedIds.has(itemId));
      if (removed.length) await tx.execute(`DELETE FROM calendar_schedule_items WHERE schedule_id=? AND id IN (${removed.map(() => '?').join(',')})`, [id, ...removed]);
    });
    return getDefinition(id);
  }

  async function copyDefinition(id, meta) {
    const current = await getDefinition(id);
    if (!current) return null;
    return createDefinition({
      ...current,
      id: undefined,
      legacyOriginalId: null,
      name: `${current.name}副本`,
      enabled: false,
      items: current.items.map((item) => ({ ...item, id: null }))
    }, meta);
  }

  async function setDefinitionStatus(id, enabled) {
    const result = await adapter.execute('UPDATE calendar_schedule_definitions SET enabled=?,updated_at=CURRENT_TIMESTAMP(3) WHERE id=?', [adapter.pgDatabase ? !!enabled : enabled ? 1 : 0, id]);
    if (!Number(result.affectedRows === undefined ? 1 : result.affectedRows)) return null;
    return getDefinition(id);
  }

  async function reorderDefinitions(items) {
    const list = Array.isArray(items) ? items.map((item) => ({ id: Number(item.id), sortOrder: Number(item.sortOrder) })) : [];
    if (!list.length || list.some((item) => !Number.isInteger(item.id) || !Number.isInteger(item.sortOrder)) || new Set(list.map((item) => item.id)).size !== list.length) return { error: 'BAD_SCHEDULE_ORDER' };
    const known = new Set((await listDefinitions(true)).map((item) => item.id));
    if (list.some((item) => !known.has(item.id))) return { error: 'BAD_SCHEDULE_ORDER' };
    await adapter.runInTransaction(async (tx) => {
      for (const item of list) await tx.execute('UPDATE calendar_schedule_definitions SET sort_order=?,updated_at=CURRENT_TIMESTAMP(3) WHERE id=?', [item.sortOrder, item.id]);
    });
    return listDefinitions(true);
  }

  async function upsertOccurrenceException(scheduleId, occurrenceDate, scope, values) {
    const params = [scheduleId, occurrenceDate, scope, values.name, values.color || null, adapter.pgDatabase ? values.fontBold === true : values.fontBold === true ? 1 : 0, adapter.pgDatabase ? values.enabled !== false : values.enabled === false ? 0 : 1];
    if (adapter.pgDatabase) {
      await adapter.execute(`INSERT INTO calendar_schedule_exceptions (schedule_id,occurrence_date,scope,name,color,font_bold,enabled,updated_at) VALUES (?,?,?,?,?,?,?,CURRENT_TIMESTAMP(3)) ON CONFLICT (schedule_id,occurrence_date,scope) DO UPDATE SET name=EXCLUDED.name,color=EXCLUDED.color,font_bold=EXCLUDED.font_bold,enabled=EXCLUDED.enabled,updated_at=CURRENT_TIMESTAMP(3)`, params);
    } else {
      await adapter.execute(`INSERT INTO calendar_schedule_exceptions (schedule_id,occurrence_date,scope,name,color,font_bold,enabled,updated_at) VALUES (?,?,?,?,?,?,?,CURRENT_TIMESTAMP(3)) ON DUPLICATE KEY UPDATE name=VALUES(name),color=VALUES(color),font_bold=VALUES(font_bold),enabled=VALUES(enabled),updated_at=CURRENT_TIMESTAMP(3)`, params);
    }
    return getDefinition(scheduleId);
  }

  async function deleteDefinition(id) {
    return adapter.runInTransaction(async (tx) => {
      await tx.execute('DELETE FROM calendar_schedule_items WHERE schedule_id=?', [id]);
      await tx.execute('DELETE FROM calendar_schedule_exceptions WHERE schedule_id=?', [id]);
      const result = await tx.execute('DELETE FROM calendar_schedule_definitions WHERE id=?', [id]);
      return Number(result.affectedRows === undefined ? 1 : result.affectedRows) > 0;
    });
  }

  return {
    listCategories,
    getCategoryById,
    getCategoryByCode,
    createCategory,
    updateCategory,
    reorderCategories,
    setCategoryStatus,
    listDefinitions,
    getDefinition,
    getDefinitionByLegacyId,
    createDefinition,
    replaceDefinition,
    copyDefinition,
    setDefinitionStatus,
    reorderDefinitions,
    upsertOccurrenceException,
    deleteDefinition
  };
}

module.exports = {
  PRESET_CATEGORIES,
  CALENDAR_DDL_MYSQL,
  CALENDAR_DDL_PG,
  createCustomCategoryCode,
  mapLegacyGroup,
  ensureCalendarSchema,
  migrateLegacyCalendarSchedules,
  createCalendarStore,
  mapCategoryRow,
  mapDefinitionRow,
  mapItemRow
};
