'use strict';

const fs = require('fs');
const path = require('path');

const VALID_CATEGORIES = new Set(['regular', 'special']);

const GIFT_PACKS_DDL_MYSQL = `
  CREATE TABLE IF NOT EXISTS gift_packs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    category VARCHAR(16) NOT NULL,
    name VARCHAR(200) NOT NULL,
    note TEXT NULL,
    sections_json JSON NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL,
    KEY idx_gift_packs_category_sort (category, sort_order),
    KEY idx_gift_packs_category_enabled (category, enabled)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
`;

const GIFT_PACKS_DDL_PG = `
  CREATE TABLE IF NOT EXISTS gift_packs (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category varchar(16) NOT NULL,
    name varchar(200) NOT NULL,
    note text NULL,
    sections_json jsonb NOT NULL,
    sort_order integer NOT NULL DEFAULT 0,
    enabled smallint NOT NULL DEFAULT 1,
    created_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at timestamptz(3) NOT NULL
  );
  CREATE INDEX IF NOT EXISTS idx_gift_packs_category_sort ON gift_packs (category, sort_order);
  CREATE INDEX IF NOT EXISTS idx_gift_packs_category_enabled ON gift_packs (category, enabled);
`;

function extractPacksArray(html) {
  const needle = 'const packs';
  const i = html.indexOf(needle);
  if (i < 0) throw new Error(`missing ${needle}`);
  const j = html.indexOf('=', i);
  const start = html.indexOf('[', j);
  let depth = 0;
  for (let k = start; k < html.length; k++) {
    const c = html[k];
    if (c === '[') depth++;
    else if (c === ']') {
      depth--;
      if (depth === 0) return JSON.parse(html.slice(start, k + 1));
    }
  }
  throw new Error('unclosed [ for packs array');
}

function normalizeGiftText(value) {
  return String(value || '')
    .toLowerCase()
    .replace(/[\s·•\-_.，。、；;：:（）()【】\[\]《》<>]/g, '');
}

function textOfPack(pack) {
  const base = [pack.name || '', pack.note || ''];
  for (const s of pack.sections || []) {
    base.push(s.title || '');
    for (const c of s.columns || []) base.push(c);
  }
  return normalizeGiftText(base.join(' '));
}

function buildSearchBlobs(packsByCategory) {
  const out = {};
  for (const [cat, packs] of Object.entries(packsByCategory || {})) {
    out[cat] = (packs || []).map((p) => ({ n: p.name || '', t: textOfPack(p) }));
  }
  return out;
}

function parseSectionsJson(raw) {
  if (Array.isArray(raw)) return raw;
  if (raw && typeof raw === 'object') return raw;
  try {
    return JSON.parse(String(raw || '[]'));
  } catch (_e) {
    return [];
  }
}

function mapRowToPublicPack(row) {
  return {
    id: Number(row.id),
    name: row.name,
    note: row.note || '',
    sections: parseSectionsJson(row.sections_json)
  };
}

function mapRowToAdminPack(row) {
  return {
    ...mapRowToPublicPack(row),
    category: row.category,
    sortOrder: Number(row.sort_order || 0),
    enabled: Boolean(Number(row.enabled ?? 1))
  };
}

function normalizeCell(value) {
  return String(value ?? '').trim();
}

function validateSections(sections) {
  if (!Array.isArray(sections) || !sections.length) return { error: 'BAD_SECTIONS' };
  const normalized = [];
  for (const section of sections) {
    const title = String(section?.title || '礼包内容').trim().slice(0, 120);
    const columns = Array.isArray(section?.columns)
      ? section.columns.map((c) => String(c || '').trim().slice(0, 80)).filter(Boolean)
      : [];
    if (!columns.length) return { error: 'BAD_COLUMNS' };
    const rows = Array.isArray(section?.rows) ? section.rows : [];
    if (!rows.length) return { error: 'BAD_ROWS' };
    const normRows = [];
    const expected = columns.length + 1;
    for (const row of rows) {
      if (!Array.isArray(row) || row.length !== expected) return { error: 'ROW_WIDTH' };
      normRows.push(row.map((cell) => normalizeCell(cell)));
    }
    normalized.push({ title, columns, rows: normRows });
  }
  return { value: normalized };
}

function validateGiftPackPayload(body, options) {
  const opts = options || {};
  const name = String(body?.name || '').trim();
  if (!name || name.length > 200) return { error: 'BAD_NAME' };
  const noteRaw = body?.note != null ? String(body.note).trim().slice(0, 2000) : '';
  const category = String(body?.category || '').trim().toLowerCase();
  if (opts.requireCategory && !VALID_CATEGORIES.has(category)) return { error: 'BAD_CATEGORY' };
  const sec = validateSections(body?.sections);
  if (sec.error) return { error: sec.error };
  const enabled = body?.enabled === false || body?.enabled === 0 ? 0 : 1;
  const sortOrder = Number.isFinite(Number(body?.sortOrder)) ? Number(body.sortOrder) : 0;
  return {
    value: {
      name,
      note: noteRaw || null,
      category: VALID_CATEGORIES.has(category) ? category : null,
      sections: sec.value,
      enabled,
      sortOrder
    }
  };
}

function readSeedPayload(rootDir) {
  const seedPath = path.join(rootDir, 'data', 'gift-packs-seed.json');
  if (fs.existsSync(seedPath)) {
    try {
      return JSON.parse(fs.readFileSync(seedPath, 'utf8'));
    } catch (_e) {
      return null;
    }
  }
  const out = {};
  for (const [category, fileName] of [
    ['regular', 'regular-gift-data.html'],
    ['special', 'special-gift-data.html']
  ]) {
    const filePath = path.join(rootDir, 'public', 'function', 'Zero', fileName);
    if (!fs.existsSync(filePath)) continue;
    const html = fs.readFileSync(filePath, 'utf8');
    if (!html.includes('const packs')) continue;
    try {
      out[category] = extractPacksArray(html);
    } catch (_e) {
      /* ignore */
    }
  }
  return Object.keys(out).length ? out : null;
}

async function seedGiftPacksIfEmpty(deps) {
  const { queryOne, execute, rootDir, pgDatabase } = deps;
  const row = await queryOne('SELECT COUNT(*) AS c FROM gift_packs', []);
  const count = Number(row?.c ?? row?.count ?? 0);
  if (count > 0) return { seeded: false, count: 0 };

  const payload = readSeedPayload(rootDir);
  if (!payload) return { seeded: false, count: 0 };

  let inserted = 0;
  for (const category of ['regular', 'special']) {
    const packs = Array.isArray(payload[category]) ? payload[category] : [];
    for (let i = 0; i < packs.length; i++) {
      const valid = validateGiftPackPayload({ ...packs[i], category }, { requireCategory: true });
      if (valid.error) continue;
      const pack = valid.value;
      const json = JSON.stringify(pack.sections);
      if (pgDatabase) {
        await execute(
          `
          INSERT INTO gift_packs (category,name,note,sections_json,sort_order,enabled,updated_at)
          VALUES (?,?,?,?::jsonb,?,?,CURRENT_TIMESTAMP(3))
          `,
          [category, pack.name, pack.note, json, i, pack.enabled]
        );
      } else {
        await execute(
          `
          INSERT INTO gift_packs (category,name,note,sections_json,sort_order,enabled,updated_at)
          VALUES (?,?,?,?,?,?,CURRENT_TIMESTAMP(3))
          `,
          [category, pack.name, pack.note, json, i, pack.enabled]
        );
      }
      inserted++;
    }
  }
  return { seeded: inserted > 0, count: inserted };
}

function mountGiftPackRoutes(deps) {
  const { app, queryRows, queryOne, execute, requireAdmin, auditAdminAction, pgDatabase } = deps;

  async function fetchPublicPacks(category) {
    const params = [];
    let where = 'enabled = 1';
    if (category) {
      where += ' AND category = ?';
      params.push(category);
    }
    const rows = await queryRows(
      `
      SELECT id,category,name,note,sections_json,sort_order
      FROM gift_packs
      WHERE ${where}
      ORDER BY category ASC, sort_order ASC, id ASC
      `,
      params
    );
    return rows.map(mapRowToPublicPack);
  }

  app.get('/api/gift-packs', async (req, res) => {
    try {
      const category = String(req.query.category || '').trim().toLowerCase();
      if (category && !VALID_CATEGORIES.has(category)) {
        return res.status(400).json({ error: 'BAD_CATEGORY' });
      }
      const packs = await fetchPublicPacks(category || null);
      res.set('Cache-Control', 'public, max-age=60');
      return res.json({ packs });
    } catch (err) {
      console.error('gift-packs get failed:', err);
      return res.status(500).json({ error: 'INTERNAL_ERROR' });
    }
  });

  app.get('/api/gift-packs/search-blobs', async (_req, res) => {
    try {
      const rows = await queryRows(
        `
        SELECT category,name,note,sections_json
        FROM gift_packs
        WHERE enabled = 1
        ORDER BY category ASC, sort_order ASC, id ASC
        `
      );
      const grouped = { regular: [], special: [] };
      for (const row of rows) {
        const cat = String(row.category || '').toLowerCase();
        if (!grouped[cat]) grouped[cat] = [];
        grouped[cat].push(mapRowToPublicPack(row));
      }
      res.set('Cache-Control', 'public, max-age=60');
      return res.json({ blobs: buildSearchBlobs(grouped) });
    } catch (err) {
      console.error('gift-packs search-blobs failed:', err);
      return res.status(500).json({ error: 'INTERNAL_ERROR' });
    }
  });

  app.get('/api/admin/gift-packs', async (req, res) => {
    try {
      const admin = await requireAdmin(req, res);
      if (!admin) return;
      const category = String(req.query.category || '').trim().toLowerCase();
      const params = [];
      let where = '1=1';
      if (category) {
        if (!VALID_CATEGORIES.has(category)) return res.status(400).json({ error: 'BAD_CATEGORY' });
        where += ' AND category = ?';
        params.push(category);
      }
      const rows = await queryRows(
        `
        SELECT id,category,name,note,sections_json,sort_order,enabled,updated_at
        FROM gift_packs
        WHERE ${where}
        ORDER BY category ASC, sort_order ASC, id ASC
        `,
        params
      );
      return res.json({ packs: rows.map(mapRowToAdminPack) });
    } catch (err) {
      console.error('admin gift-packs get failed:', err);
      return res.status(500).json({ error: 'INTERNAL_ERROR' });
    }
  });

  app.post('/api/admin/gift-packs', async (req, res) => {
    try {
      const admin = await requireAdmin(req, res);
      if (!admin) return;
      const valid = validateGiftPackPayload(req.body || {}, { requireCategory: true });
      if (valid.error) return res.status(400).json({ error: valid.error });
      const pack = valid.value;
      const json = JSON.stringify(pack.sections);
      let ret;
      if (pgDatabase) {
        ret = await execute(
          `
          INSERT INTO gift_packs (category,name,note,sections_json,sort_order,enabled,updated_at)
          VALUES (?,?,?,?::jsonb,?,?,CURRENT_TIMESTAMP(3))
          RETURNING id
          `,
          [pack.category, pack.name, pack.note, json, pack.sortOrder, pack.enabled]
        );
      } else {
        ret = await execute(
          `
          INSERT INTO gift_packs (category,name,note,sections_json,sort_order,enabled,updated_at)
          VALUES (?,?,?,?,?,?,CURRENT_TIMESTAMP(3))
          `,
          [pack.category, pack.name, pack.note, json, pack.sortOrder, pack.enabled]
        );
      }
      const id = Number(ret.insertId || ret.rows?.[0]?.id || 0);
      await auditAdminAction(req, {
        actor: admin,
        action: 'gift_pack.create',
        targetType: 'gift_pack',
        targetId: String(id),
        riskLevel: 'watch',
        summary: `创建礼包：${pack.name}`,
        metadata: { id, category: pack.category, name: pack.name }
      });
      return res.status(201).json({ ok: true, id });
    } catch (err) {
      console.error('admin gift-packs post failed:', err);
      return res.status(500).json({ error: 'INTERNAL_ERROR' });
    }
  });

  const handleAdminGiftPackUpdate = async (req, res) => {
    try {
      const admin = await requireAdmin(req, res);
      if (!admin) return;
      const id = Number(req.params.id);
      if (!Number.isFinite(id) || id <= 0) return res.status(400).json({ error: 'BAD_ID' });
      const exists = await queryOne('SELECT id,category,name FROM gift_packs WHERE id = ? LIMIT 1', [id]);
      if (!exists) return res.status(404).json({ error: 'NOT_FOUND' });
      const valid = validateGiftPackPayload(req.body || {}, { requireCategory: false });
      if (valid.error) return res.status(400).json({ error: valid.error });
      const pack = valid.value;
      const category = pack.category || exists.category;
      const json = JSON.stringify(pack.sections);
      if (pgDatabase) {
        await execute(
          `
          UPDATE gift_packs
          SET category = ?, name = ?, note = ?, sections_json = ?::jsonb,
              sort_order = ?, enabled = ?, updated_at = CURRENT_TIMESTAMP(3)
          WHERE id = ?
          `,
          [category, pack.name, pack.note, json, pack.sortOrder, pack.enabled, id]
        );
      } else {
        await execute(
          `
          UPDATE gift_packs
          SET category = ?, name = ?, note = ?, sections_json = ?,
              sort_order = ?, enabled = ?, updated_at = CURRENT_TIMESTAMP(3)
          WHERE id = ?
          `,
          [category, pack.name, pack.note, json, pack.sortOrder, pack.enabled, id]
        );
      }
      await auditAdminAction(req, {
        actor: admin,
        action: 'gift_pack.update',
        targetType: 'gift_pack',
        targetId: String(id),
        riskLevel: 'watch',
        summary: `更新礼包：${pack.name}`,
        metadata: { id, category, name: pack.name }
      });
      return res.json({ ok: true });
    } catch (err) {
      console.error('admin gift-packs update failed:', err);
      return res.status(500).json({ error: 'INTERNAL_ERROR' });
    }
  };

  app.patch('/api/admin/gift-packs/:id', handleAdminGiftPackUpdate);
  app.post('/api/admin/gift-packs/:id', handleAdminGiftPackUpdate);

  app.delete('/api/admin/gift-packs/:id', async (req, res) => {
    try {
      const admin = await requireAdmin(req, res);
      if (!admin) return;
      const id = Number(req.params.id);
      if (!Number.isFinite(id) || id <= 0) return res.status(400).json({ error: 'BAD_ID' });
      const exists = await queryOne('SELECT id,name FROM gift_packs WHERE id = ? LIMIT 1', [id]);
      if (!exists) return res.status(404).json({ error: 'NOT_FOUND' });
      await execute('DELETE FROM gift_packs WHERE id = ?', [id]);
      await auditAdminAction(req, {
        actor: admin,
        action: 'gift_pack.delete',
        targetType: 'gift_pack',
        targetId: String(id),
        riskLevel: 'danger',
        summary: `删除礼包：${exists.name}`,
        metadata: { id, name: exists.name }
      });
      return res.json({ ok: true });
    } catch (err) {
      console.error('admin gift-packs delete failed:', err);
      return res.status(500).json({ error: 'INTERNAL_ERROR' });
    }
  });

  app.post('/api/admin/gift-packs/reorder', async (req, res) => {
    try {
      const admin = await requireAdmin(req, res);
      if (!admin) return;
      const category = String(req.body?.category || '').trim().toLowerCase();
      if (!VALID_CATEGORIES.has(category)) return res.status(400).json({ error: 'BAD_CATEGORY' });
      const orderedIds = Array.isArray(req.body?.orderedIds)
        ? req.body.orderedIds.map((x) => Number(x)).filter((x) => Number.isFinite(x) && x > 0)
        : [];
      if (!orderedIds.length) return res.status(400).json({ error: 'BAD_ORDER' });
      for (let i = 0; i < orderedIds.length; i++) {
        await execute(
          'UPDATE gift_packs SET sort_order = ?, updated_at = CURRENT_TIMESTAMP(3) WHERE id = ? AND category = ?',
          [i, orderedIds[i], category]
        );
      }
      await auditAdminAction(req, {
        actor: admin,
        action: 'gift_pack.reorder',
        targetType: 'gift_pack',
        targetId: category,
        riskLevel: 'info',
        summary: `重排${category === 'regular' ? '常规' : '特惠'}礼包顺序`,
        metadata: { category, orderedIds }
      });
      return res.json({ ok: true });
    } catch (err) {
      console.error('admin gift-packs reorder failed:', err);
      return res.status(500).json({ error: 'INTERNAL_ERROR' });
    }
  });
}

module.exports = {
  VALID_CATEGORIES,
  GIFT_PACKS_DDL_MYSQL,
  GIFT_PACKS_DDL_PG,
  extractPacksArray,
  normalizeGiftText,
  textOfPack,
  buildSearchBlobs,
  validateGiftPackPayload,
  validateSections,
  mapRowToPublicPack,
  mapRowToAdminPack,
  seedGiftPacksIfEmpty,
  mountGiftPackRoutes
};
