'use strict';

const fs = require('fs');
const path = require('path');

const SKILL_KEYS = ['explore', 'expedition', 'weapon'];

const HERO_GENERATIONS_DDL_MYSQL = `
  CREATE TABLE IF NOT EXISTS hero_generations (
    id INT AUTO_INCREMENT PRIMARY KEY,
    slug VARCHAR(64) NOT NULL UNIQUE,
    generation_num INT NOT NULL,
    page_title VARCHAR(120) NOT NULL,
    hub_title VARCHAR(120) NOT NULL,
    hub_desc VARCHAR(500) NOT NULL,
    hub_tag VARCHAR(32) NOT NULL DEFAULT '已上线',
    heroes_json JSON NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL,
    KEY idx_hero_generations_sort (sort_order),
    KEY idx_hero_generations_enabled (enabled, sort_order)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
`;

const HERO_GENERATIONS_DDL_PG = `
  CREATE TABLE IF NOT EXISTS hero_generations (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug varchar(64) NOT NULL UNIQUE,
    generation_num integer NOT NULL,
    page_title varchar(120) NOT NULL,
    hub_title varchar(120) NOT NULL,
    hub_desc varchar(500) NOT NULL,
    hub_tag varchar(32) NOT NULL DEFAULT '已上线',
    heroes_json jsonb NOT NULL,
    sort_order integer NOT NULL DEFAULT 0,
    enabled smallint NOT NULL DEFAULT 1,
    created_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at timestamptz(3) NOT NULL
  );
  CREATE INDEX IF NOT EXISTS idx_hero_generations_sort ON hero_generations (sort_order);
  CREATE INDEX IF NOT EXISTS idx_hero_generations_enabled ON hero_generations (enabled, sort_order);
`;

function parseJsonArray(raw) {
  if (Array.isArray(raw)) return raw;
  try {
    const parsed = JSON.parse(String(raw || '[]'));
    return Array.isArray(parsed) ? parsed : [];
  } catch (_e) {
    return [];
  }
}

function parseHeroesJson(raw) {
  if (Array.isArray(raw)) return raw;
  if (raw && typeof raw === 'object') return Array.isArray(raw.heroes) ? raw.heroes : [];
  return parseJsonArray(raw);
}

function linesFromText(value) {
  return String(value || '')
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter(Boolean);
}

function normalizeSkillItems(items) {
  if (!Array.isArray(items)) return { error: 'BAD_SKILL_LIST' };
  const normalized = [];
  for (const item of items) {
    const name = String(item?.name || '').trim().slice(0, 80);
    if (!name) return { error: 'BAD_SKILL_NAME' };
    const lines = Array.isArray(item?.lines)
      ? item.lines.map((line) => String(line || '').trim()).filter(Boolean).slice(0, 20)
      : linesFromText(item?.linesText);
    if (!lines.length) return { error: 'BAD_SKILL_LINES' };
    normalized.push({
      name,
      lines: lines.map((line) => line.slice(0, 500))
    });
  }
  return { value: normalized };
}

function normalizeHero(hero) {
  const name = String(hero?.name || '').trim().slice(0, 80);
  if (!name) return { error: 'BAD_HERO_NAME' };
  const image = String(hero?.image || '').trim().slice(0, 300);
  const attr = String(hero?.attr || '').trim().slice(0, 80);
  const advice = String(hero?.advice || '').trim().slice(0, 500);
  const exploreStats = Array.isArray(hero?.exploreStats)
    ? hero.exploreStats.map((v) => String(v || '').trim()).filter(Boolean).slice(0, 12)
    : linesFromText(hero?.exploreStatsText).slice(0, 12);
  const expeditionStats = Array.isArray(hero?.expeditionStats)
    ? hero.expeditionStats.map((v) => String(v || '').trim()).filter(Boolean).slice(0, 20)
    : linesFromText(hero?.expeditionStatsText).slice(0, 20);
  const obtainWays = Array.isArray(hero?.obtainWays)
    ? hero.obtainWays.map((v) => String(v || '').trim()).filter(Boolean).slice(0, 20)
    : linesFromText(hero?.obtainWaysText).slice(0, 20);
  if (!exploreStats.length) return { error: 'BAD_EXPLORE_STATS' };
  if (!expeditionStats.length) return { error: 'BAD_EXPEDITION_STATS' };
  const skills = {};
  for (const key of SKILL_KEYS) {
    const sec = normalizeSkillItems(hero?.skills?.[key] || []);
    if (sec.error) return { error: sec.error };
    skills[key] = sec.value;
  }
  return {
    value: {
      name,
      image,
      attr,
      advice,
      exploreStats,
      expeditionStats,
      obtainWays,
      skills
    }
  };
}

function validateHeroGenerationPayload(body, options) {
  const opts = options || {};
  const slug = String(body?.slug || '').trim().toLowerCase();
  if (opts.requireSlug && (!slug || slug.length > 64 || !/^[a-z0-9-]+$/.test(slug))) {
    return { error: 'BAD_SLUG' };
  }
  const pageTitle = String(body?.pageTitle || '').trim().slice(0, 120);
  const hubTitle = String(body?.hubTitle || '').trim().slice(0, 120);
  const hubDesc = String(body?.hubDesc || '').trim().slice(0, 500);
  const hubTag = String(body?.hubTag || '已上线').trim().slice(0, 32) || '已上线';
  if (!pageTitle || !hubTitle || !hubDesc) return { error: 'BAD_META' };
  const generationNum = Number(body?.generationNum);
  if (opts.requireGenerationNum && (!Number.isFinite(generationNum) || generationNum < 1 || generationNum > 99)) {
    return { error: 'BAD_GENERATION_NUM' };
  }
  const heroesRaw = Array.isArray(body?.heroes) ? body.heroes : [];
  if (!heroesRaw.length) return { error: 'BAD_HEROES' };
  const heroes = [];
  for (const hero of heroesRaw) {
    const normalized = normalizeHero(hero);
    if (normalized.error) return { error: normalized.error };
    heroes.push(normalized.value);
  }
  const enabled = body?.enabled === false || body?.enabled === 0 ? 0 : 1;
  const sortOrder = Number.isFinite(Number(body?.sortOrder)) ? Number(body.sortOrder) : 0;
  return {
    value: {
      slug: slug || null,
      generationNum: Number.isFinite(generationNum) ? generationNum : null,
      pageTitle,
      hubTitle,
      hubDesc,
      hubTag,
      heroes,
      enabled,
      sortOrder
    }
  };
}

function mapRowToPublicGeneration(row, options) {
  const opts = options || {};
  const heroes = parseHeroesJson(row.heroes_json);
  const base = {
    id: Number(row.id),
    slug: row.slug,
    generationNum: Number(row.generation_num || 0),
    pageTitle: row.page_title,
    hubTitle: row.hub_title,
    hubDesc: row.hub_desc,
    hubTag: row.hub_tag || '已上线'
  };
  if (opts.includeHeroes) {
    base.heroes = heroes;
  } else {
    base.heroNames = heroes.map((h) => h.name).filter(Boolean);
  }
  return base;
}

function mapRowToAdminGeneration(row) {
  return {
    ...mapRowToPublicGeneration(row, { includeHeroes: true }),
    sortOrder: Number(row.sort_order || 0),
    enabled: Boolean(Number(row.enabled ?? 1))
  };
}

function readSeedPayload(rootDir) {
  const seedPath = path.join(rootDir, 'data', 'hero-generations-seed.json');
  if (!fs.existsSync(seedPath)) return null;
  try {
    const payload = JSON.parse(fs.readFileSync(seedPath, 'utf8'));
    return Array.isArray(payload?.generations) ? payload.generations : null;
  } catch (_e) {
    return null;
  }
}

async function seedHeroGenerationsIfEmpty(deps) {
  const { queryOne, execute, rootDir, pgDatabase } = deps;
  const row = await queryOne('SELECT COUNT(*) AS c FROM hero_generations', []);
  const count = Number(row?.c ?? row?.count ?? 0);
  if (count > 0) return { seeded: false, count: 0 };

  const generations = readSeedPayload(rootDir);
  if (!generations?.length) return { seeded: false, count: 0 };

  let inserted = 0;
  for (let i = 0; i < generations.length; i++) {
    const item = generations[i];
    const valid = validateHeroGenerationPayload(
      {
        ...item,
        sortOrder: item.sortOrder != null ? item.sortOrder : i
      },
      { requireSlug: true, requireGenerationNum: true }
    );
    if (valid.error) continue;
    const gen = valid.value;
    const json = JSON.stringify(gen.heroes);
    if (pgDatabase) {
      await execute(
        `
        INSERT INTO hero_generations
          (slug,generation_num,page_title,hub_title,hub_desc,hub_tag,heroes_json,sort_order,enabled,updated_at)
        VALUES (?,?,?,?,?,?,?::jsonb,?,?,CURRENT_TIMESTAMP(3))
        `,
        [
          gen.slug,
          gen.generationNum,
          gen.pageTitle,
          gen.hubTitle,
          gen.hubDesc,
          gen.hubTag,
          json,
          gen.sortOrder,
          gen.enabled
        ]
      );
    } else {
      await execute(
        `
        INSERT INTO hero_generations
          (slug,generation_num,page_title,hub_title,hub_desc,hub_tag,heroes_json,sort_order,enabled,updated_at)
        VALUES (?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP(3))
        `,
        [
          gen.slug,
          gen.generationNum,
          gen.pageTitle,
          gen.hubTitle,
          gen.hubDesc,
          gen.hubTag,
          json,
          gen.sortOrder,
          gen.enabled
        ]
      );
    }
    inserted++;
  }
  return { seeded: inserted > 0, count: inserted };
}

function mountHeroDataRoutes(deps) {
  const { app, queryRows, queryOne, execute, requireAdmin, auditAdminAction, pgDatabase } = deps;

  app.get('/api/hero-generations', async (_req, res) => {
    try {
      const rows = await queryRows(
        `
        SELECT id,slug,generation_num,page_title,hub_title,hub_desc,hub_tag,heroes_json,sort_order
        FROM hero_generations
        WHERE enabled = 1
        ORDER BY sort_order ASC, generation_num ASC, id ASC
        `
      );
      res.set('Cache-Control', 'public, max-age=60');
      return res.json({ generations: rows.map((row) => mapRowToPublicGeneration(row)) });
    } catch (err) {
      console.error('hero-generations list failed:', err);
      return res.status(500).json({ error: 'INTERNAL_ERROR' });
    }
  });

  app.get('/api/hero-generations/:slug', async (req, res) => {
    try {
      const slug = String(req.params.slug || '').trim().toLowerCase();
      if (!slug) return res.status(400).json({ error: 'BAD_SLUG' });
      const row = await queryOne(
        `
        SELECT id,slug,generation_num,page_title,hub_title,hub_desc,hub_tag,heroes_json,sort_order
        FROM hero_generations
        WHERE slug = ? AND enabled = 1
        LIMIT 1
        `,
        [slug]
      );
      if (!row) return res.status(404).json({ error: 'NOT_FOUND' });
      res.set('Cache-Control', 'public, max-age=60');
      return res.json({ generation: mapRowToPublicGeneration(row, { includeHeroes: true }) });
    } catch (err) {
      console.error('hero-generations get failed:', err);
      return res.status(500).json({ error: 'INTERNAL_ERROR' });
    }
  });

  app.get('/api/admin/hero-generations', async (req, res) => {
    try {
      const admin = await requireAdmin(req, res);
      if (!admin) return;
      const rows = await queryRows(
        `
        SELECT id,slug,generation_num,page_title,hub_title,hub_desc,hub_tag,heroes_json,sort_order,enabled,updated_at
        FROM hero_generations
        ORDER BY sort_order ASC, generation_num ASC, id ASC
        `
      );
      return res.json({ generations: rows.map(mapRowToAdminGeneration) });
    } catch (err) {
      console.error('admin hero-generations list failed:', err);
      return res.status(500).json({ error: 'INTERNAL_ERROR' });
    }
  });

  app.get('/api/admin/hero-generations/:id', async (req, res) => {
    try {
      const admin = await requireAdmin(req, res);
      if (!admin) return;
      const id = Number(req.params.id);
      if (!Number.isFinite(id) || id <= 0) return res.status(400).json({ error: 'BAD_ID' });
      const row = await queryOne(
        `
        SELECT id,slug,generation_num,page_title,hub_title,hub_desc,hub_tag,heroes_json,sort_order,enabled,updated_at
        FROM hero_generations
        WHERE id = ?
        LIMIT 1
        `,
        [id]
      );
      if (!row) return res.status(404).json({ error: 'NOT_FOUND' });
      return res.json({ generation: mapRowToAdminGeneration(row) });
    } catch (err) {
      console.error('admin hero-generations get failed:', err);
      return res.status(500).json({ error: 'INTERNAL_ERROR' });
    }
  });

  app.post('/api/admin/hero-generations', async (req, res) => {
    try {
      const admin = await requireAdmin(req, res);
      if (!admin) return;
      const valid = validateHeroGenerationPayload(req.body || {}, {
        requireSlug: true,
        requireGenerationNum: false
      });
      if (valid.error) return res.status(400).json({ error: valid.error });
      const gen = valid.value;
      const dup = await queryOne('SELECT id FROM hero_generations WHERE slug = ? LIMIT 1', [gen.slug]);
      if (dup) return res.status(400).json({ error: 'SLUG_TAKEN' });

      let generationNum = gen.generationNum;
      if (!Number.isFinite(generationNum) || generationNum < 1) {
        const maxRow = await queryOne(
          'SELECT COALESCE(MAX(generation_num), 0) AS m FROM hero_generations',
          []
        );
        generationNum = Number(maxRow?.m || 0) + 1;
      }

      let sortOrder = gen.sortOrder;
      if (!Number.isFinite(sortOrder)) {
        const sortRow = await queryOne(
          'SELECT COALESCE(MAX(sort_order), -1) AS m FROM hero_generations',
          []
        );
        sortOrder = Number(sortRow?.m ?? -1) + 1;
      }

      const json = JSON.stringify(gen.heroes);
      if (pgDatabase) {
        await execute(
          `
          INSERT INTO hero_generations
            (slug,generation_num,page_title,hub_title,hub_desc,hub_tag,heroes_json,sort_order,enabled,updated_at)
          VALUES (?,?,?,?,?,?,?::jsonb,?,?,CURRENT_TIMESTAMP(3))
          `,
          [
            gen.slug,
            generationNum,
            gen.pageTitle,
            gen.hubTitle,
            gen.hubDesc,
            gen.hubTag,
            json,
            sortOrder,
            gen.enabled
          ]
        );
      } else {
        await execute(
          `
          INSERT INTO hero_generations
            (slug,generation_num,page_title,hub_title,hub_desc,hub_tag,heroes_json,sort_order,enabled,updated_at)
          VALUES (?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP(3))
          `,
          [
            gen.slug,
            generationNum,
            gen.pageTitle,
            gen.hubTitle,
            gen.hubDesc,
            gen.hubTag,
            json,
            sortOrder,
            gen.enabled
          ]
        );
      }
      const created = await queryOne(
        'SELECT id FROM hero_generations WHERE slug = ? LIMIT 1',
        [gen.slug]
      );
      const newId = Number(created?.id || 0);
      await auditAdminAction(req, {
        action: 'hero_generation_create',
        targetType: 'hero_generation',
        targetId: String(newId || gen.slug),
        riskLevel: 'watch',
        summary: `新增英雄代数 ${gen.slug}（第 ${generationNum} 代，${gen.heroes.length} 名英雄）`
      });
      return res.json({ ok: true, id: newId });
    } catch (err) {
      console.error('admin hero-generations create failed:', err);
      return res.status(500).json({ error: 'INTERNAL_ERROR' });
    }
  });

  app.post('/api/admin/hero-generations/reorder', async (req, res) => {
    try {
      const admin = await requireAdmin(req, res);
      if (!admin) return;
      const orderedIds = Array.isArray(req.body?.orderedIds) ? req.body.orderedIds.map(Number).filter(Boolean) : [];
      if (!orderedIds.length) return res.status(400).json({ error: 'BAD_ORDER' });
      for (let i = 0; i < orderedIds.length; i++) {
        await execute('UPDATE hero_generations SET sort_order = ?, updated_at = CURRENT_TIMESTAMP(3) WHERE id = ?', [
          i,
          orderedIds[i]
        ]);
      }
      await auditAdminAction(req, {
        action: 'hero_generations_reorder',
        targetType: 'hero_generation',
        targetId: '',
        riskLevel: 'info',
        summary: `重排 ${orderedIds.length} 个英雄代数`
      });
      return res.json({ ok: true });
    } catch (err) {
      console.error('admin hero-generations reorder failed:', err);
      return res.status(500).json({ error: 'INTERNAL_ERROR' });
    }
  });

  app.post('/api/admin/hero-generations/:id', async (req, res) => {
    try {
      const admin = await requireAdmin(req, res);
      if (!admin) return;
      const id = Number(req.params.id);
      if (!Number.isFinite(id) || id <= 0) return res.status(400).json({ error: 'BAD_ID' });
      const existing = await queryOne('SELECT id, slug FROM hero_generations WHERE id = ? LIMIT 1', [id]);
      if (!existing) return res.status(404).json({ error: 'NOT_FOUND' });
      const valid = validateHeroGenerationPayload(req.body || {}, { requireSlug: false, requireGenerationNum: false });
      if (valid.error) return res.status(400).json({ error: valid.error });
      const gen = valid.value;
      const json = JSON.stringify(gen.heroes);
      if (pgDatabase) {
        await execute(
          `
          UPDATE hero_generations
          SET page_title = ?, hub_title = ?, hub_desc = ?, hub_tag = ?, heroes_json = ?::jsonb,
              sort_order = ?, enabled = ?, updated_at = CURRENT_TIMESTAMP(3)
          WHERE id = ?
          `,
          [
            gen.pageTitle,
            gen.hubTitle,
            gen.hubDesc,
            gen.hubTag,
            json,
            gen.sortOrder,
            gen.enabled,
            id
          ]
        );
      } else {
        await execute(
          `
          UPDATE hero_generations
          SET page_title = ?, hub_title = ?, hub_desc = ?, hub_tag = ?, heroes_json = ?,
              sort_order = ?, enabled = ?, updated_at = CURRENT_TIMESTAMP(3)
          WHERE id = ?
          `,
          [
            gen.pageTitle,
            gen.hubTitle,
            gen.hubDesc,
            gen.hubTag,
            json,
            gen.sortOrder,
            gen.enabled,
            id
          ]
        );
      }
      await auditAdminAction(req, {
        action: 'hero_generation_update',
        targetType: 'hero_generation',
        targetId: String(id),
        riskLevel: 'watch',
        summary: `更新英雄代数 ${existing.slug}（${gen.heroes.length} 名英雄）`
      });
      return res.json({ ok: true, id });
    } catch (err) {
      console.error('admin hero-generations update failed:', err);
      return res.status(500).json({ error: 'INTERNAL_ERROR' });
    }
  });

  app.delete('/api/admin/hero-generations/:id', async (req, res) => {
    try {
      const admin = await requireAdmin(req, res);
      if (!admin) return;
      const id = Number(req.params.id);
      if (!Number.isFinite(id) || id <= 0) return res.status(400).json({ error: 'BAD_ID' });
      const existing = await queryOne('SELECT id, slug FROM hero_generations WHERE id = ? LIMIT 1', [id]);
      if (!existing) return res.status(404).json({ error: 'NOT_FOUND' });
      await execute('DELETE FROM hero_generations WHERE id = ?', [id]);
      await auditAdminAction(req, {
        action: 'hero_generation_delete',
        targetType: 'hero_generation',
        targetId: String(id),
        riskLevel: 'danger',
        summary: `删除英雄代数 ${existing.slug}`
      });
      return res.json({ ok: true });
    } catch (err) {
      console.error('admin hero-generations delete failed:', err);
      return res.status(500).json({ error: 'INTERNAL_ERROR' });
    }
  });
}

module.exports = {
  HERO_GENERATIONS_DDL_MYSQL,
  HERO_GENERATIONS_DDL_PG,
  SKILL_KEYS,
  validateHeroGenerationPayload,
  normalizeHero,
  mountHeroDataRoutes,
  seedHeroGenerationsIfEmpty,
  mapRowToPublicGeneration
};
