'use strict';

const { createLudoManager } = require('./ludo-game');

const LUDO_DDL_MYSQL = `
  CREATE TABLE IF NOT EXISTS ludo_match_history (
    id INT AUTO_INCREMENT PRIMARY KEY,
    room_id VARCHAR(16) NOT NULL,
    room_name VARCHAR(80) NOT NULL DEFAULT '',
    host_user_id INT NOT NULL,
    takeoff_mode VARCHAR(16) NOT NULL DEFAULT 'six',
    winner_user_id INT NULL,
    player_count INT NOT NULL DEFAULT 0,
    peak_spectator_count INT NOT NULL DEFAULT 0,
    round_count INT NOT NULL DEFAULT 0,
    started_at DATETIME(3) NULL,
    finished_at DATETIME(3) NULL,
    duration_seconds INT NOT NULL DEFAULT 0,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    KEY idx_ludo_history_finished (finished_at),
    KEY idx_ludo_history_winner (winner_user_id)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

  CREATE TABLE IF NOT EXISTS ludo_match_players (
    id INT AUTO_INCREMENT PRIMARY KEY,
    match_id INT NOT NULL,
    user_id INT NOT NULL,
    username VARCHAR(64) NOT NULL DEFAULT '',
    seat INT NOT NULL,
    color VARCHAR(16) NOT NULL DEFAULT '',
    rank_num INT NULL,
    finished TINYINT(1) NOT NULL DEFAULT 0,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    KEY idx_ludo_players_user (user_id, created_at),
    KEY idx_ludo_players_match (match_id)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
`;

const LUDO_DDL_PG = `
  CREATE TABLE IF NOT EXISTS ludo_match_history (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id varchar(16) NOT NULL,
    room_name varchar(80) NOT NULL DEFAULT '',
    host_user_id integer NOT NULL,
    takeoff_mode varchar(16) NOT NULL DEFAULT 'six',
    winner_user_id integer NULL,
    player_count integer NOT NULL DEFAULT 0,
    peak_spectator_count integer NOT NULL DEFAULT 0,
    round_count integer NOT NULL DEFAULT 0,
    started_at timestamptz(3) NULL,
    finished_at timestamptz(3) NULL,
    duration_seconds integer NOT NULL DEFAULT 0,
    created_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
  );
  CREATE INDEX IF NOT EXISTS idx_ludo_history_finished ON ludo_match_history (finished_at);
  CREATE INDEX IF NOT EXISTS idx_ludo_history_winner ON ludo_match_history (winner_user_id);

  CREATE TABLE IF NOT EXISTS ludo_match_players (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id integer NOT NULL,
    user_id integer NOT NULL,
    username varchar(64) NOT NULL DEFAULT '',
    seat integer NOT NULL,
    color varchar(16) NOT NULL DEFAULT '',
    rank_num integer NULL,
    finished smallint NOT NULL DEFAULT 0,
    created_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
  );
  CREATE INDEX IF NOT EXISTS idx_ludo_players_user ON ludo_match_players (user_id, created_at);
  CREATE INDEX IF NOT EXISTS idx_ludo_players_match ON ludo_match_players (match_id);
`;

const ludoManager = createLudoManager();

function ludoStatus(code) {
  if (code === 'UNAUTHORIZED') return 401;
  if (code === 'ROOM_NOT_FOUND') return 404;
  if (code === 'BAD_PASSWORD') return 403;
  if (code === 'ROOM_FULL') return 409;
  if (code === 'NOT_HOST' || code === 'NOT_PLAYER' || code === 'SPECTATOR_ONLY') return 403;
  if (code === 'NOT_YOUR_TURN' || code === 'MOVE_REQUIRED' || code === 'INVALID_MOVE') return 409;
  return 400;
}

function sendLudoError(res, err) {
  const code = err && (err.code || err.message) ? String(err.code || err.message) : 'INTERNAL_ERROR';
  if (code === 'INTERNAL_ERROR') return res.status(500).json({ error: code });
  return res.status(ludoStatus(code)).json({ error: code });
}

function isParticipant(room, userId) {
  const uid = Number(userId);
  return room.players.some((player) => Number(player.userId) === uid)
    || room.spectators.some((spectator) => Number(spectator.userId) === uid);
}

function roomListDto(room) {
  return {
    id: room.id,
    name: room.name,
    hostUserId: room.hostUserId,
    status: room.status,
    takeoffMode: room.takeoffMode,
    hasPassword: !!room.hasPassword,
    playerCount: room.players.length,
    maxPlayers: 4,
    spectatorCount: room.spectators.length,
    peakSpectatorCount: room.peakSpectatorCount,
    createdAt: room.createdAt,
    startedAt: room.startedAt,
    updatedAt: room.updatedAt
  };
}

function fullRoomDto(room, viewerUserId) {
  return {
    ...roomListDto(room),
    viewer: {
      isPlayer: room.players.some((player) => Number(player.userId) === Number(viewerUserId)),
      isSpectator: room.spectators.some((spectator) => Number(spectator.userId) === Number(viewerUserId)),
      isHost: Number(room.hostUserId) === Number(viewerUserId)
    },
    players: room.players.map((player) => ({
      userId: player.userId,
      username: player.username,
      seat: player.seat,
      color: player.color,
      ready: !!player.ready,
      online: !!player.online,
      managedByAi: !!player.managedByAi,
      rank: player.rank || null
    })),
    spectators: room.spectators.map((spectator) => ({
      userId: spectator.userId,
      username: spectator.username
    })),
    game: room.game,
    log: room.log || [],
    historySnapshot: room.historySnapshot || null
  };
}

async function ensureLudoSchema(deps) {
  if (!deps || typeof deps.execute !== 'function') return;
  const ddl = deps.pgDatabase ? LUDO_DDL_PG : LUDO_DDL_MYSQL;
  const statements = ddl.split(';').map((item) => item.trim()).filter(Boolean);
  for (const statement of statements) {
    await deps.execute(statement);
  }
}

function maybeRunAi(room) {
  ludoManager.tick(Date.now());
  for (let i = 0; i < 12; i += 1) {
    const current = room.players.find((player) => room.game && Number(player.seat) === Number(room.game.turnSeat));
    if (!current || !current.managedByAi) break;
    const result = ludoManager.runAiTurn(room.id);
    if (!result) break;
    if (!room.game || room.status !== 'playing') break;
  }
}

function toSqlDate(formatSqlDateTime, value) {
  if (!value) return null;
  if (typeof formatSqlDateTime === 'function') return formatSqlDateTime(value);
  const date = value instanceof Date ? value : new Date(value);
  if (Number.isNaN(date.getTime())) return null;
  return date.toISOString().replace('T', ' ').replace('Z', '').slice(0, 23);
}

async function persistHistoryIfFinished(deps, room) {
  if (!room || room.status !== 'finished' || !room.historySnapshot || room.historySaved) return;
  const { execute, pgDatabase, formatSqlDateTime } = deps;
  const snapshot = room.historySnapshot;
  const started = snapshot.startedAt ? new Date(snapshot.startedAt).getTime() : NaN;
  const finished = snapshot.finishedAt ? new Date(snapshot.finishedAt).getTime() : NaN;
  const durationSeconds = Number.isFinite(started) && Number.isFinite(finished)
    ? Math.max(0, Math.round((finished - started) / 1000))
    : 0;
  const params = [
    snapshot.roomId,
    snapshot.roomName,
    Number(snapshot.hostUserId || 0),
    snapshot.takeoffMode,
    snapshot.winnerUserId == null ? null : Number(snapshot.winnerUserId),
    Number(snapshot.playerCount || 0),
    Number(snapshot.peakSpectatorCount || 0),
    Number(snapshot.roundCount || 0),
    toSqlDate(formatSqlDateTime, snapshot.startedAt),
    toSqlDate(formatSqlDateTime, snapshot.finishedAt),
    durationSeconds
  ];
  const insertSql = pgDatabase
    ? `
      INSERT INTO ludo_match_history
      (room_id, room_name, host_user_id, takeoff_mode, winner_user_id, player_count,
       peak_spectator_count, round_count, started_at, finished_at, duration_seconds)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
      RETURNING id
      `
    : `
      INSERT INTO ludo_match_history
      (room_id, room_name, host_user_id, takeoff_mode, winner_user_id, player_count,
       peak_spectator_count, round_count, started_at, finished_at, duration_seconds)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
      `;
  const result = await execute(insertSql, params);
  const matchId = Number(result && result.insertId);
  if (!Number.isFinite(matchId) || matchId <= 0) return;
  for (const player of snapshot.players || []) {
    await execute(
      `
      INSERT INTO ludo_match_players
      (match_id, user_id, username, seat, color, rank_num, finished)
      VALUES (?, ?, ?, ?, ?, ?, ?)
      `,
      [
        matchId,
        Number(player.userId || 0),
        String(player.username || '').slice(0, 64),
        Number(player.seat || 0),
        String(player.color || '').slice(0, 16),
        player.rank == null ? null : Number(player.rank),
        player.finished ? 1 : 0
      ]
    );
  }
  room.historySaved = true;
}

function mountLudoRoutes(deps) {
  const {
    app,
    queryRows,
    execute,
    requireAuth,
    formatSqlDateTime,
    pgDatabase
  } = deps;

  ensureLudoSchema({ execute, pgDatabase }).catch((err) => {
    console.error('ludo schema init failed:', err);
  });

  app.get('/api/ludo/rooms', async (req, res) => {
    try {
      const user = await requireAuth(req, res);
      if (!user) return;
      ludoManager.tick(Date.now());
      return res.json({ ok: true, rooms: ludoManager.listRooms().map(roomListDto) });
    } catch (err) {
      return sendLudoError(res, err);
    }
  });

  app.post('/api/ludo/rooms', async (req, res) => {
    try {
      const user = await requireAuth(req, res);
      if (!user) return;
      const room = ludoManager.createRoom(user, req.body || {});
      return res.status(201).json({ ok: true, room: fullRoomDto(room, user.id) });
    } catch (err) {
      return sendLudoError(res, err);
    }
  });

  app.post('/api/ludo/rooms/:id/join', async (req, res) => {
    try {
      const user = await requireAuth(req, res);
      if (!user) return;
      const room = ludoManager.joinRoom(req.params.id, user, req.body || {});
      return res.json({ ok: true, room: fullRoomDto(room, user.id) });
    } catch (err) {
      return sendLudoError(res, err);
    }
  });

  app.post('/api/ludo/rooms/:id/seat', async (req, res) => {
    try {
      const user = await requireAuth(req, res);
      if (!user) return;
      const room = ludoManager.setSeat(req.params.id, user, req.body?.joinAs || 'player');
      return res.json({ ok: true, room: fullRoomDto(room, user.id) });
    } catch (err) {
      return sendLudoError(res, err);
    }
  });

  app.get('/api/ludo/rooms/:id', async (req, res) => {
    try {
      const user = await requireAuth(req, res);
      if (!user) return;
      const room = ludoManager.getRoom(req.params.id);
      if (!isParticipant(room, user.id)) return res.status(403).json({ error: 'SPECTATOR_ONLY' });
      ludoManager.markHeartbeat(room.id, user, Date.now());
      maybeRunAi(room);
      await persistHistoryIfFinished({ execute, pgDatabase, formatSqlDateTime }, room);
      return res.json({ ok: true, room: fullRoomDto(room, user.id) });
    } catch (err) {
      return sendLudoError(res, err);
    }
  });

  app.post('/api/ludo/rooms/:id/ready', async (req, res) => {
    try {
      const user = await requireAuth(req, res);
      if (!user) return;
      const room = ludoManager.setReady(req.params.id, user, req.body?.ready !== false);
      return res.json({ ok: true, room: fullRoomDto(room, user.id) });
    } catch (err) {
      return sendLudoError(res, err);
    }
  });

  app.post('/api/ludo/rooms/:id/start', async (req, res) => {
    try {
      const user = await requireAuth(req, res);
      if (!user) return;
      const room = ludoManager.startGame(req.params.id, user);
      return res.json({ ok: true, room: fullRoomDto(room, user.id) });
    } catch (err) {
      return sendLudoError(res, err);
    }
  });

  app.post('/api/ludo/rooms/:id/heartbeat', async (req, res) => {
    try {
      const user = await requireAuth(req, res);
      if (!user) return;
      const room = ludoManager.markHeartbeat(req.params.id, user, Date.now());
      return res.json({ ok: true, room: fullRoomDto(room, user.id) });
    } catch (err) {
      return sendLudoError(res, err);
    }
  });

  app.post('/api/ludo/rooms/:id/roll', async (req, res) => {
    try {
      const user = await requireAuth(req, res);
      if (!user) return;
      const result = ludoManager.rollDice(req.params.id, user);
      const room = ludoManager.getRoom(req.params.id);
      return res.json({ ok: true, ...result, room: fullRoomDto(room, user.id) });
    } catch (err) {
      return sendLudoError(res, err);
    }
  });

  app.post('/api/ludo/rooms/:id/move', async (req, res) => {
    try {
      const user = await requireAuth(req, res);
      if (!user) return;
      const room = ludoManager.movePiece(req.params.id, user, req.body?.pieceIndex);
      await persistHistoryIfFinished({ execute, pgDatabase, formatSqlDateTime }, room);
      return res.json({ ok: true, room: fullRoomDto(room, user.id) });
    } catch (err) {
      return sendLudoError(res, err);
    }
  });

  app.post('/api/ludo/rooms/:id/leave', async (req, res) => {
    try {
      const user = await requireAuth(req, res);
      if (!user) return;
      const room = ludoManager.leaveRoom(req.params.id, user);
      return res.json({ ok: true, room: room ? fullRoomDto(room, user.id) : null });
    } catch (err) {
      return sendLudoError(res, err);
    }
  });

  app.post('/api/ludo/rooms/:id/surrender', async (req, res) => {
    try {
      const user = await requireAuth(req, res);
      if (!user) return;
      const room = ludoManager.surrender(req.params.id, user);
      await persistHistoryIfFinished({ execute, pgDatabase, formatSqlDateTime }, room);
      return res.json({ ok: true, room: fullRoomDto(room, user.id) });
    } catch (err) {
      return sendLudoError(res, err);
    }
  });

  app.get('/api/ludo/history', async (req, res) => {
    try {
      const user = await requireAuth(req, res);
      if (!user) return;
      const rows = await queryRows(
        `
        SELECT h.*, p.rank_num, p.color, p.finished
        FROM ludo_match_players p
        INNER JOIN ludo_match_history h ON h.id = p.match_id
        WHERE p.user_id = ?
        ORDER BY h.finished_at DESC, h.id DESC
        LIMIT 50
        `,
        [Number(user.id)]
      );
      return res.json({
        ok: true,
        history: rows.map((row) => ({
          id: Number(row.id),
          roomId: row.room_id,
          roomName: row.room_name,
          takeoffMode: row.takeoff_mode,
          winnerUserId: row.winner_user_id == null ? null : Number(row.winner_user_id),
          playerCount: Number(row.player_count || 0),
          peakSpectatorCount: Number(row.peak_spectator_count || 0),
          roundCount: Number(row.round_count || 0),
          rank: row.rank_num == null ? null : Number(row.rank_num),
          color: row.color,
          finished: Number(row.finished || 0) === 1,
          startedAt: row.started_at || null,
          finishedAt: row.finished_at || null
        }))
      });
    } catch (err) {
      return sendLudoError(res, err);
    }
  });

  return { manager: ludoManager };
}

module.exports = {
  LUDO_DDL_MYSQL,
  LUDO_DDL_PG,
  ensureLudoSchema,
  mountLudoRoutes
};
