const POSTGRES_SCHEMA_SQL = [
  `
  CREATE TABLE IF NOT EXISTS analytics_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type varchar(32) NOT NULL,
    occurred_at timestamptz(3) NOT NULL,
    page_path varchar(255) NULL,
    page_key varchar(128) NULL,
    scope_type varchar(32) NOT NULL,
    scope_key varchar(128) NOT NULL,
    user_id bigint NULL,
    visitor_id varchar(32) NULL,
    session_id varchar(64) NULL,
    referrer varchar(512) NULL,
    user_agent_hash char(64) NULL,
    ip_hash char(64) NULL,
    is_admin_area smallint NOT NULL DEFAULT 0,
    status_code integer NULL,
    duration_ms integer NULL,
    created_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
  )
  `,
  'CREATE INDEX IF NOT EXISTS idx_analytics_events_occurred_at ON analytics_events (occurred_at)',
  'CREATE INDEX IF NOT EXISTS idx_analytics_events_scope ON analytics_events (scope_type, scope_key, occurred_at)',
  'CREATE INDEX IF NOT EXISTS idx_analytics_events_identity ON analytics_events (user_id, visitor_id, occurred_at)',
  `
  CREATE TABLE IF NOT EXISTS analytics_hourly_aggregates (
    bucket_start timestamptz(3) NOT NULL,
    bucket_granularity varchar(16) NOT NULL DEFAULT 'hour',
    scope_type varchar(32) NOT NULL,
    scope_key varchar(128) NOT NULL,
    pv bigint NOT NULL DEFAULT 0,
    uv bigint NOT NULL DEFAULT 0,
    created_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (bucket_start, bucket_granularity, scope_type, scope_key)
  )
  `,
  'CREATE INDEX IF NOT EXISTS idx_analytics_hourly_scope ON analytics_hourly_aggregates (scope_type, scope_key, bucket_start)',
  `
  CREATE TABLE IF NOT EXISTS users (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login_id varchar(64) NOT NULL UNIQUE,
    username varchar(64) NOT NULL UNIQUE,
    password_hash varchar(255) NOT NULL,
    is_admin smallint NOT NULL DEFAULT 0,
    forum_publisher smallint NOT NULL DEFAULT 0,
    is_banned smallint NOT NULL DEFAULT 0,
    muted_until timestamptz(3) NULL,
    membership_status varchar(32) NOT NULL DEFAULT 'none',
    membership_expires_at timestamptz(3) NULL,
    title_text varchar(64) NOT NULL DEFAULT '',
    title_bg_color varchar(16) NULL,
    title_color varchar(16) NULL,
    bio varchar(255) NOT NULL DEFAULT '这个人很高冷，连个人介绍都不改！',
    username_change_remaining integer NOT NULL DEFAULT 2,
    username_change_next_at timestamptz(3) NULL,
    username_changed_at timestamptz(3) NULL,
    avatar_url text NULL,
    avatar_updated_at timestamptz(3) NULL,
    avatar_next_at timestamptz(3) NULL,
    gender varchar(16) NOT NULL DEFAULT 'unknown',
    birthday date NULL,
    birthday_public smallint NOT NULL DEFAULT 0,
    created_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
  )
  `,
  `
  CREATE TABLE IF NOT EXISTS forum_posts (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section varchar(32) NOT NULL,
    type varchar(16) NOT NULL DEFAULT 'article',
    title varchar(120) NOT NULL,
    contentText text NULL,
    contentHtml text NULL,
    coverImage text NULL,
    status varchar(16) NOT NULL DEFAULT 'approved',
    approved_at timestamptz(3) NULL,
    approved_by integer NULL,
    is_pinned smallint NOT NULL DEFAULT 0,
    author_id integer NOT NULL,
    created_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
  )
  `,
  `
  CREATE TABLE IF NOT EXISTS forum_comments (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id integer NOT NULL,
    author_id integer NOT NULL,
    content text NOT NULL,
    reply_to_comment_id integer NULL,
    is_pinned smallint NOT NULL DEFAULT 0,
    created_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
  )
  `,
  `
  CREATE TABLE IF NOT EXISTS forum_post_likes (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id integer NOT NULL,
    user_id integer NOT NULL,
    created_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uq_forum_post_like UNIQUE (post_id, user_id)
  )
  `,
  `
  CREATE TABLE IF NOT EXISTS forum_post_favorites (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id integer NOT NULL,
    user_id integer NOT NULL,
    created_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uq_forum_post_favorite UNIQUE (post_id, user_id)
  )
  `,
  `
  CREATE TABLE IF NOT EXISTS chat_messages (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id integer NOT NULL,
    receiver_id integer NOT NULL,
    content varchar(1000) NOT NULL,
    created_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
  )
  `,
  'CREATE INDEX IF NOT EXISTS idx_chat_sender_receiver_created ON chat_messages (sender_id, receiver_id, created_at)',
  'CREATE INDEX IF NOT EXISTS idx_chat_receiver_sender_created ON chat_messages (receiver_id, sender_id, created_at)',
  `
  CREATE TABLE IF NOT EXISTS chat_read_states (
    user_id integer NOT NULL,
    peer_id integer NOT NULL,
    read_at timestamptz(3) NOT NULL,
    PRIMARY KEY (user_id, peer_id)
  )
  `,
  'CREATE INDEX IF NOT EXISTS idx_chat_read_peer ON chat_read_states (peer_id, user_id)',
  `
  CREATE TABLE IF NOT EXISTS user_follows (
    follower_id integer NOT NULL,
    following_id integer NOT NULL,
    created_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (follower_id, following_id)
  )
  `,
  'CREATE INDEX IF NOT EXISTS idx_following_id ON user_follows (following_id)',
  `
  CREATE TABLE IF NOT EXISTS site_settings (
    key varchar(64) PRIMARY KEY,
    value text NOT NULL
  )
  `,
  `
  CREATE TABLE IF NOT EXISTS user_voices (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NULL,
    contact varchar(64) NOT NULL,
    content text NOT NULL,
    created_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
  )
  `,
  `
  CREATE TABLE IF NOT EXISTS calendar_schedules (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_id varchar(32) NOT NULL,
    name varchar(120) NOT NULL,
    date varchar(10) NOT NULL,
    start_time varchar(10) NULL,
    end_time varchar(10) NULL,
    color varchar(16) NULL,
    description text NULL,
    created_by integer NULL,
    created_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at timestamptz(3) NOT NULL
  )
  `,
  `
  CREATE TABLE IF NOT EXISTS gift_packs (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category varchar(16) NOT NULL,
    name varchar(200) NOT NULL,
    note text NULL,
    sections_json jsonb NOT NULL,
    sort_order integer NOT NULL DEFAULT 0,
    enabled smallint NOT NULL DEFAULT 1,
    created_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at timestamptz(3) NOT NULL
  )
  `,
  'CREATE INDEX IF NOT EXISTS idx_gift_packs_category_sort ON gift_packs (category, sort_order)',
  'CREATE INDEX IF NOT EXISTS idx_gift_packs_category_enabled ON gift_packs (category, enabled)',
  `
  CREATE TABLE IF NOT EXISTS bearpit_layouts (
    user_id integer PRIMARY KEY,
    data_json jsonb NOT NULL,
    updated_at timestamptz(3) NOT NULL
  )
  `,
  `
  CREATE TABLE IF NOT EXISTS bearpit_layout_backups (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL,
    title varchar(120) NOT NULL,
    data_json jsonb NOT NULL,
    item_count integer NOT NULL DEFAULT 0,
    created_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
  )
  `,
  'CREATE INDEX IF NOT EXISTS idx_bearpit_backups_user_created ON bearpit_layout_backups (user_id, created_at DESC)',
  `
  CREATE TABLE IF NOT EXISTS hero_generations (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug varchar(64) NOT NULL UNIQUE,
    generation_num integer NOT NULL,
    page_title varchar(120) NOT NULL,
    hub_title varchar(120) NOT NULL,
    hub_desc varchar(500) NOT NULL,
    hub_tag varchar(32) NOT NULL DEFAULT '已上线',
    heroes_json jsonb NOT NULL,
    sort_order integer NOT NULL DEFAULT 0,
    enabled smallint NOT NULL DEFAULT 1,
    created_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at timestamptz(3) NOT NULL
  )
  `,
  'CREATE INDEX IF NOT EXISTS idx_hero_generations_sort ON hero_generations (sort_order)',
  'CREATE INDEX IF NOT EXISTS idx_hero_generations_enabled ON hero_generations (enabled, sort_order)',
  `
  CREATE TABLE IF NOT EXISTS admin_user_delete_requests (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_user_id integer NOT NULL,
    target_login_id varchar(64) NOT NULL,
    target_username varchar(64) NOT NULL,
    source_post_id integer NULL,
    requested_by integer NOT NULL,
    status varchar(16) NOT NULL DEFAULT 'pending',
    review_note varchar(255) NULL,
    reviewed_by integer NULL,
    reviewed_at timestamptz(3) NULL,
    created_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
  )
  `,
  'CREATE INDEX IF NOT EXISTS idx_delete_requests_target ON admin_user_delete_requests (target_user_id)',
  'CREATE INDEX IF NOT EXISTS idx_delete_requests_status ON admin_user_delete_requests (status)',
  'CREATE INDEX IF NOT EXISTS idx_delete_requests_requested_by ON admin_user_delete_requests (requested_by)',
  `
  CREATE TABLE IF NOT EXISTS admin_audit_logs (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id integer NULL,
    actor_login_id varchar(64) NULL,
    actor_username varchar(64) NULL,
    action varchar(64) NOT NULL,
    target_type varchar(64) NOT NULL,
    target_id varchar(64) NULL,
    risk_level varchar(16) NOT NULL DEFAULT 'info',
    summary varchar(255) NOT NULL,
    metadata_json jsonb NULL,
    ip_hash varchar(64) NULL,
    user_agent_hash varchar(64) NULL,
    created_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
  )
  `,
  'CREATE INDEX IF NOT EXISTS idx_audit_created ON admin_audit_logs (created_at)',
  'CREATE INDEX IF NOT EXISTS idx_audit_actor ON admin_audit_logs (actor_id, created_at)',
  'CREATE INDEX IF NOT EXISTS idx_audit_action ON admin_audit_logs (action, created_at)',
  'CREATE INDEX IF NOT EXISTS idx_audit_target ON admin_audit_logs (target_type, target_id)',
  'CREATE INDEX IF NOT EXISTS idx_audit_risk ON admin_audit_logs (risk_level, created_at)',
  `
  CREATE TABLE IF NOT EXISTS admin_release_checks (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id integer NULL,
    status varchar(16) NOT NULL,
    risk_level varchar(16) NOT NULL,
    summary varchar(255) NOT NULL,
    items_json jsonb NOT NULL,
    created_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
  )
  `,
  'CREATE INDEX IF NOT EXISTS idx_release_checks_created ON admin_release_checks (created_at)',
  'CREATE INDEX IF NOT EXISTS idx_release_checks_actor ON admin_release_checks (actor_id, created_at)',
  'CREATE INDEX IF NOT EXISTS idx_release_checks_risk ON admin_release_checks (risk_level, created_at)'
];

module.exports = {
  POSTGRES_SCHEMA_SQL
};
