'use strict';

const { applyMembershipFromCode, getUserPoints } = require('./user-rewards');

const SHOP_ITEM_TYPES = new Set(['membership', 'points', 'combo']);

const SHOP_DDL_MYSQL = `
  CREATE TABLE IF NOT EXISTS shop_items (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(80) NOT NULL,
    description VARCHAR(500) NOT NULL DEFAULT '',
    item_type VARCHAR(16) NOT NULL DEFAULT 'membership',
    price_points INT NOT NULL DEFAULT 0,
    points_reward INT NULL,
    membership_days INT NULL,
    badge_text VARCHAR(24) NOT NULL DEFAULT '',
    stock_limit INT NULL,
    sold_count INT NOT NULL DEFAULT 0,
    sort_order INT NOT NULL DEFAULT 0,
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    KEY idx_shop_items_sort (enabled, sort_order, id)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

  CREATE TABLE IF NOT EXISTS shop_purchases (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    item_id INT NOT NULL,
    points_spent INT NOT NULL DEFAULT 0,
    purchased_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    KEY idx_shop_purchases_user (user_id, purchased_at),
    KEY idx_shop_purchases_item (item_id, purchased_at)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
`;

const SHOP_DDL_PG = `
  CREATE TABLE IF NOT EXISTS shop_items (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(80) NOT NULL,
    description varchar(500) NOT NULL DEFAULT '',
    item_type varchar(16) NOT NULL DEFAULT 'membership',
    price_points integer NOT NULL DEFAULT 0,
    points_reward integer NULL,
    membership_days integer NULL,
    badge_text varchar(24) NOT NULL DEFAULT '',
    stock_limit integer NULL,
    sold_count integer NOT NULL DEFAULT 0,
    sort_order integer NOT NULL DEFAULT 0,
    enabled smallint NOT NULL DEFAULT 1,
    created_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
  );
  CREATE INDEX IF NOT EXISTS idx_shop_items_sort ON shop_items (enabled, sort_order, id);

  CREATE TABLE IF NOT EXISTS shop_purchases (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL,
    item_id integer NOT NULL,
    points_spent integer NOT NULL DEFAULT 0,
    purchased_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
  );
  CREATE INDEX IF NOT EXISTS idx_shop_purchases_user ON shop_purchases (user_id, purchased_at);
  CREATE INDEX IF NOT EXISTS idx_shop_purchases_item ON shop_purchases (item_id, purchased_at);
`;

function normalizeShopItemPayload(raw, options) {
  const opts = options || {};
  const body = raw && typeof raw === 'object' ? raw : {};
  const name = String(body.name || '').trim().slice(0, 80);
  if (!name) return { error: 'BAD_NAME' };
  const description = String(body.description || '').trim().slice(0, 500);
  const itemType = String(body.itemType || body.item_type || 'membership').trim().toLowerCase();
  if (!SHOP_ITEM_TYPES.has(itemType)) return { error: 'BAD_ITEM_TYPE' };
  const pricePoints = Math.floor(Number(body.pricePoints ?? body.price_points));
  if (!Number.isFinite(pricePoints) || pricePoints < 0 || pricePoints > 1000000) {
    return { error: 'BAD_PRICE' };
  }
  const badgeText = String(body.badgeText || body.badge_text || '').trim().slice(0, 24);
  const sortOrder = Math.floor(Number(body.sortOrder ?? body.sort_order ?? 0));
  const enabled = body.enabled === false || body.enabled === 0 || body.enabled === '0' ? 0 : 1;
  let stockLimit = null;
  const stockRaw = body.stockLimit ?? body.stock_limit;
  if (stockRaw != null && stockRaw !== '') {
    const n = Math.floor(Number(stockRaw));
    if (!Number.isFinite(n) || n < 0) return { error: 'BAD_STOCK' };
    stockLimit = n;
  }

  let pointsReward = null;
  let membershipDays = null;
  if (itemType === 'points') {
    pointsReward = Math.floor(Number(body.pointsReward ?? body.points_reward));
    if (!Number.isFinite(pointsReward) || pointsReward < 1) return { error: 'BAD_POINTS_REWARD' };
  } else if (itemType === 'membership') {
    const daysRaw = body.membershipDays ?? body.membership_days;
    if (daysRaw === 0 || daysRaw === '0' || daysRaw === 'lifetime') membershipDays = 0;
    else {
      membershipDays = Math.floor(Number(daysRaw));
      if (!Number.isFinite(membershipDays) || membershipDays < 1 || membershipDays > 3650) {
        return { error: 'BAD_MEMBERSHIP_DAYS' };
      }
    }
  } else if (itemType === 'combo') {
    pointsReward = Math.floor(Number(body.pointsReward ?? body.points_reward ?? 0));
    if (!Number.isFinite(pointsReward) || pointsReward < 1) return { error: 'BAD_POINTS_REWARD' };
    const daysRaw = body.membershipDays ?? body.membership_days;
    if (daysRaw === 0 || daysRaw === '0' || daysRaw === 'lifetime') membershipDays = 0;
    else {
      membershipDays = Math.floor(Number(daysRaw));
      if (!Number.isFinite(membershipDays) || membershipDays < 1 || membershipDays > 3650) {
        return { error: 'BAD_MEMBERSHIP_DAYS' };
      }
    }
  }

  if (!opts.allowFree && pricePoints < 1 && !opts.isUpdate) return { error: 'BAD_PRICE' };

  return {
    name,
    description,
    itemType,
    pricePoints,
    pointsReward,
    membershipDays,
    badgeText,
    stockLimit,
    sortOrder: Number.isFinite(sortOrder) ? sortOrder : 0,
    enabled
  };
}

function mapShopItemRow(row) {
  if (!row) return null;
  const stockLimit = row.stock_limit == null ? null : Number(row.stock_limit);
  const soldCount = Number(row.sold_count || 0);
  return {
    id: Number(row.id),
    name: String(row.name || ''),
    description: String(row.description || ''),
    itemType: String(row.item_type || 'membership'),
    pricePoints: Number(row.price_points || 0),
    pointsReward: row.points_reward != null ? Number(row.points_reward) : null,
    membershipDays: row.membership_days != null ? Number(row.membership_days) : null,
    badgeText: String(row.badge_text || ''),
    stockLimit,
    soldCount,
    remainingStock: stockLimit == null ? null : Math.max(0, stockLimit - soldCount),
    sortOrder: Number(row.sort_order || 0),
    enabled: Number(row.enabled) === 1,
    createdAt: row.created_at || null,
    updatedAt: row.updated_at || null
  };
}

function shopRewardSummary(item) {
  if (!item) return '';
  if (item.itemType === 'points') return `+${item.pointsReward} 积分`;
  if (item.itemType === 'membership') {
    return item.membershipDays === 0 ? '永久会员' : `${item.membershipDays} 天会员`;
  }
  if (item.itemType === 'combo') {
    const mem = item.membershipDays === 0 ? '永久会员' : `${item.membershipDays} 天会员`;
    return `+${item.pointsReward} 积分 + ${mem}`;
  }
  return '';
}

function normalizeAdminRecordQuery(query) {
  const raw = query && typeof query === 'object' ? query : {};
  const q = String(raw.q || '').trim().slice(0, 80);
  const page = Math.max(1, Math.floor(Number(raw.page) || 1));
  const pageSize = Math.min(100, Math.max(10, Math.floor(Number(raw.pageSize ?? raw.page_size) || 20)));
  return {
    q,
    page,
    pageSize,
    offset: (page - 1) * pageSize
  };
}

function mapShopPurchaseRow(row) {
  if (!row) return null;
  return {
    id: Number(row.id),
    userId: Number(row.user_id),
    user: {
      id: Number(row.user_id),
      loginId: row.user_login_id || '',
      username: row.user_username || row.user_login_id || ''
    },
    itemId: row.item_id != null ? Number(row.item_id) : null,
    item: {
      id: row.item_id != null ? Number(row.item_id) : null,
      name: row.item_name || '',
      itemType: row.item_type || ''
    },
    pointsSpent: Number(row.points_spent || 0),
    purchasedAt: row.purchased_at || null
  };
}

async function applyShopItemToUser(deps, userId, item, helpers) {
  const user = await deps.queryOne(
    'SELECT id, points, membership_status, membership_expires_at FROM users WHERE id = ? LIMIT 1',
    [userId]
  );
  if (!user) return { error: 'USER_NOT_FOUND' };
  const now = helpers.now || new Date();
  let pointsAdded = 0;
  let membershipStatus = null;
  let membershipExpiresAt = null;

  if (item.itemType === 'points' || item.itemType === 'combo') {
    const amount = Math.max(0, Number(item.pointsReward || 0));
    if (amount > 0) {
      await deps.execute('UPDATE users SET points = COALESCE(points, 0) + ? WHERE id = ?', [amount, userId]);
      pointsAdded = amount;
    }
  }
  if (item.itemType === 'membership' || item.itemType === 'combo') {
    const days = item.membershipDays == null ? 0 : Number(item.membershipDays);
    const next = applyMembershipFromCode(user.membership_status, user.membership_expires_at, days, now);
    await deps.execute(
      'UPDATE users SET membership_status = ?, membership_expires_at = ? WHERE id = ?',
      [
        next.membershipStatus,
        next.membershipExpiresAt ? helpers.formatSqlDateTime(next.membershipExpiresAt) : null,
        userId
      ]
    );
    membershipStatus = next.membershipStatus;
    membershipExpiresAt = next.membershipExpiresAt;
  }

  return {
    pointsAdded,
    membershipStatus,
    membershipExpiresAt,
    points: await getUserPoints(deps, userId)
  };
}

async function purchaseShopItem(deps, userId, itemId, helpers) {
  const itemRow = await deps.queryOne('SELECT * FROM shop_items WHERE id = ? LIMIT 1', [itemId]);
  if (!itemRow || Number(itemRow.enabled) !== 1) return { error: 'ITEM_NOT_AVAILABLE' };
  const item = mapShopItemRow(itemRow);
  if (item.stockLimit != null && item.soldCount >= item.stockLimit) return { error: 'ITEM_SOLD_OUT' };

  const user = await deps.queryOne(
    'SELECT id, points, membership_status, membership_expires_at FROM users WHERE id = ? LIMIT 1',
    [userId]
  );
  if (!user) return { error: 'USER_NOT_FOUND' };
  const balance = Math.max(0, Number(user.points || 0));
  if (balance < item.pricePoints) return { error: 'INSUFFICIENT_POINTS' };

  await deps.execute('UPDATE users SET points = COALESCE(points, 0) - ? WHERE id = ?', [
    item.pricePoints,
    userId
  ]);
  await deps.execute('UPDATE shop_items SET sold_count = sold_count + 1, updated_at = CURRENT_TIMESTAMP(3) WHERE id = ?', [
    itemId
  ]);
  await deps.execute(
    'INSERT INTO shop_purchases (user_id, item_id, points_spent) VALUES (?, ?, ?)',
    [userId, itemId, item.pricePoints]
  );

  const reward = await applyShopItemToUser(deps, userId, item, helpers);
  if (reward.error) return reward;
  return {
    item,
    pointsSpent: item.pricePoints,
    ...reward
  };
}

function mountShopRoutes(deps) {
  const {
    app,
    queryRows,
    queryOne,
    execute,
    requireAuth,
    requireAdmin,
    auditAdminAction,
    formatSqlDateTime,
    toUserPayload,
    attachFollowCountsToUserPayload
  } = deps;

  app.get('/api/shop/items', async (_req, res) => {
    try {
      const rows = await queryRows(
        `
        SELECT id, name, description, item_type, price_points, points_reward, membership_days,
               badge_text, stock_limit, sold_count, sort_order, enabled
        FROM shop_items
        WHERE enabled = 1
        ORDER BY sort_order ASC, id ASC
        `
      );
      return res.json({
        items: rows.map(mapShopItemRow).filter((item) => {
          if (item.stockLimit == null) return true;
          return item.soldCount < item.stockLimit;
        })
      });
    } catch (err) {
      console.error('shop items get failed:', err);
      return res.status(500).json({ error: 'INTERNAL_ERROR' });
    }
  });

  app.post('/api/shop/purchase', async (req, res) => {
    try {
      const user = await requireAuth(req, res);
      if (!user) return;
      const itemId = Math.floor(Number(req.body?.itemId ?? req.body?.item_id));
      if (!Number.isFinite(itemId) || itemId <= 0) return res.status(400).json({ error: 'BAD_ITEM_ID' });
      const result = await purchaseShopItem(
        { queryOne, execute },
        user.id,
        itemId,
        { formatSqlDateTime, now: new Date() }
      );
      if (result.error) {
        const status =
          result.error === 'ITEM_NOT_AVAILABLE' || result.error === 'ITEM_SOLD_OUT'
            ? 404
            : result.error === 'INSUFFICIENT_POINTS'
              ? 409
              : 400;
        return res.status(status).json({ error: result.error });
      }
      const freshUser = await queryOne('SELECT * FROM users WHERE id = ? LIMIT 1', [user.id]);
      const payload = freshUser
        ? await attachFollowCountsToUserPayload(toUserPayload(freshUser))
        : null;
      return res.json({ ok: true, purchase: result, user: payload });
    } catch (err) {
      console.error('shop purchase failed:', err);
      return res.status(500).json({ error: 'INTERNAL_ERROR' });
    }
  });

  app.get('/api/admin/shop/items', async (req, res) => {
    try {
      const admin = await requireAdmin(req, res);
      if (!admin) return;
      const rows = await queryRows(
        `
        SELECT id, name, description, item_type, price_points, points_reward, membership_days,
               badge_text, stock_limit, sold_count, sort_order, enabled, created_at, updated_at
        FROM shop_items
        ORDER BY sort_order ASC, id DESC
        LIMIT 500
        `
      );
      return res.json({ items: rows.map(mapShopItemRow) });
    } catch (err) {
      console.error('admin shop items get failed:', err);
      return res.status(500).json({ error: 'INTERNAL_ERROR' });
    }
  });

  app.get('/api/admin/shop/purchases', async (req, res) => {
    try {
      const admin = await requireAdmin(req, res);
      if (!admin) return;
      const pageInfo = normalizeAdminRecordQuery(req.query || {});
      const params = [];
      let where = '';
      if (pageInfo.q) {
        where = `
          WHERE i.name LIKE ? OR u.login_id LIKE ? OR u.username LIKE ?
             OR CAST(u.id AS CHAR) LIKE ? OR CAST(p.id AS CHAR) LIKE ?
        `;
        const token = `%${pageInfo.q}%`;
        params.push(token, token, token, token, token);
      }
      const countRow = await queryOne(
        `
        SELECT COUNT(*) AS total
        FROM shop_purchases p
        LEFT JOIN users u ON u.id = p.user_id
        LEFT JOIN shop_items i ON i.id = p.item_id
        ${where}
        `,
        params
      );
      const rows = await queryRows(
        `
        SELECT p.id, p.user_id, p.item_id, p.points_spent, p.purchased_at,
               u.login_id AS user_login_id, u.username AS user_username,
               i.name AS item_name, i.item_type
        FROM shop_purchases p
        LEFT JOIN users u ON u.id = p.user_id
        LEFT JOIN shop_items i ON i.id = p.item_id
        ${where}
        ORDER BY p.purchased_at DESC, p.id DESC
        LIMIT ? OFFSET ?
        `,
        params.concat([pageInfo.pageSize, pageInfo.offset])
      );
      const total = Math.max(0, Number(countRow?.total || 0));
      return res.json({
        purchases: rows.map(mapShopPurchaseRow),
        page: pageInfo.page,
        pageSize: pageInfo.pageSize,
        total,
        totalPages: Math.max(1, Math.ceil(total / pageInfo.pageSize))
      });
    } catch (err) {
      console.error('admin shop purchases get failed:', err);
      return res.status(500).json({ error: 'INTERNAL_ERROR' });
    }
  });

  app.post('/api/admin/shop/items', async (req, res) => {
    try {
      const admin = await requireAdmin(req, res);
      if (!admin) return;
      const parsed = normalizeShopItemPayload(req.body || {});
      if (parsed.error) return res.status(400).json({ error: parsed.error });
      await execute(
        `
        INSERT INTO shop_items
          (name, description, item_type, price_points, points_reward, membership_days, badge_text, stock_limit, sort_order, enabled, updated_at)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP(3))
        `,
        [
          parsed.name,
          parsed.description,
          parsed.itemType,
          parsed.pricePoints,
          parsed.pointsReward,
          parsed.membershipDays,
          parsed.badgeText,
          parsed.stockLimit,
          parsed.sortOrder,
          parsed.enabled
        ]
      );
      const row = await queryOne('SELECT * FROM shop_items WHERE name = ? ORDER BY id DESC LIMIT 1', [parsed.name]);
      if (auditAdminAction) {
        await auditAdminAction(req, {
          action: 'shop_item_create',
          targetType: 'shop_item',
          targetId: String(row?.id || ''),
          riskLevel: 'info',
          summary: `上架商城道具：${parsed.name}`
        });
      }
      return res.status(201).json({ item: mapShopItemRow(row) });
    } catch (err) {
      console.error('admin shop item create failed:', err);
      return res.status(500).json({ error: 'INTERNAL_ERROR' });
    }
  });

  app.post('/api/admin/shop/items/:id', async (req, res) => {
    try {
      const admin = await requireAdmin(req, res);
      if (!admin) return;
      const id = Number(req.params.id);
      if (!Number.isFinite(id) || id <= 0) return res.status(400).json({ error: 'BAD_ID' });
      const existing = await queryOne('SELECT id FROM shop_items WHERE id = ? LIMIT 1', [id]);
      if (!existing) return res.status(404).json({ error: 'NOT_FOUND' });
      const parsed = normalizeShopItemPayload(req.body || {}, { isUpdate: true, allowFree: true });
      if (parsed.error) return res.status(400).json({ error: parsed.error });
      await execute(
        `
        UPDATE shop_items
        SET name = ?, description = ?, item_type = ?, price_points = ?, points_reward = ?, membership_days = ?,
            badge_text = ?, stock_limit = ?, sort_order = ?, enabled = ?, updated_at = CURRENT_TIMESTAMP(3)
        WHERE id = ?
        `,
        [
          parsed.name,
          parsed.description,
          parsed.itemType,
          parsed.pricePoints,
          parsed.pointsReward,
          parsed.membershipDays,
          parsed.badgeText,
          parsed.stockLimit,
          parsed.sortOrder,
          parsed.enabled,
          id
        ]
      );
      const row = await queryOne('SELECT * FROM shop_items WHERE id = ? LIMIT 1', [id]);
      if (auditAdminAction) {
        await auditAdminAction(req, {
          action: 'shop_item_update',
          targetType: 'shop_item',
          targetId: String(id),
          riskLevel: 'info',
          summary: `更新商城道具：${parsed.name}`
        });
      }
      return res.json({ item: mapShopItemRow(row) });
    } catch (err) {
      console.error('admin shop item update failed:', err);
      return res.status(500).json({ error: 'INTERNAL_ERROR' });
    }
  });

  app.delete('/api/admin/shop/items/:id', async (req, res) => {
    try {
      const admin = await requireAdmin(req, res);
      if (!admin) return;
      const id = Number(req.params.id);
      if (!Number.isFinite(id) || id <= 0) return res.status(400).json({ error: 'BAD_ID' });
      const existing = await queryOne('SELECT id, name FROM shop_items WHERE id = ? LIMIT 1', [id]);
      if (!existing) return res.status(404).json({ error: 'NOT_FOUND' });
      await execute('DELETE FROM shop_items WHERE id = ?', [id]);
      if (auditAdminAction) {
        await auditAdminAction(req, {
          action: 'shop_item_delete',
          targetType: 'shop_item',
          targetId: String(id),
          riskLevel: 'watch',
          summary: `删除商城道具：${existing.name}`
        });
      }
      return res.json({ ok: true });
    } catch (err) {
      console.error('admin shop item delete failed:', err);
      return res.status(500).json({ error: 'INTERNAL_ERROR' });
    }
  });
}

async function ensureShopSchema(deps) {
  const { execute, pgDatabase } = deps;
  const ddl = pgDatabase ? SHOP_DDL_PG : SHOP_DDL_MYSQL;
  const parts = ddl.split(';').map((s) => s.trim()).filter(Boolean);
  for (const sql of parts) {
    await execute(sql);
  }
}

module.exports = {
  SHOP_DDL_MYSQL,
  SHOP_DDL_PG,
  SHOP_ITEM_TYPES,
  normalizeShopItemPayload,
  mapShopItemRow,
  shopRewardSummary,
  normalizeAdminRecordQuery,
  mapShopPurchaseRow,
  applyShopItemToUser,
  purchaseShopItem,
  ensureShopSchema,
  mountShopRoutes
};
