'use strict';

const crypto = require('crypto');

const DAILY_CHECKIN_POINTS = 2;
const STREAK_BONUS_POINTS = 5;
const STREAK_BONUS_DAYS = 7;
const SITE_TZ_OFFSET_MS = 8 * 60 * 60 * 1000;

const ACTIVATION_CODE_TYPES = new Set(['points', 'membership']);
const CODE_ALPHABET = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';

const USER_REWARDS_DDL_MYSQL = `
  CREATE TABLE IF NOT EXISTS user_check_ins (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    check_in_date DATE NOT NULL,
    streak_day INT NOT NULL DEFAULT 1,
    points_earned INT NOT NULL DEFAULT 0,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    UNIQUE KEY uq_user_check_in_day (user_id, check_in_date),
    KEY idx_user_check_ins_user (user_id, check_in_date)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

  CREATE TABLE IF NOT EXISTS activation_codes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    code VARCHAR(32) NOT NULL UNIQUE,
    type VARCHAR(16) NOT NULL,
    points_amount INT NULL,
    membership_days INT NULL,
    max_uses INT NOT NULL DEFAULT 1,
    use_count INT NOT NULL DEFAULT 0,
    expires_at DATETIME(3) NULL,
    note VARCHAR(120) NOT NULL DEFAULT '',
    created_by INT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    KEY idx_activation_codes_type (type, created_at)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

  CREATE TABLE IF NOT EXISTS activation_code_redemptions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    code_id INT NOT NULL,
    user_id INT NOT NULL,
    redeemed_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    UNIQUE KEY uq_activation_code_user (code_id, user_id),
    KEY idx_activation_redemptions_user (user_id, redeemed_at)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
`;

const USER_REWARDS_DDL_PG = `
  CREATE TABLE IF NOT EXISTS user_check_ins (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL,
    check_in_date date NOT NULL,
    streak_day integer NOT NULL DEFAULT 1,
    points_earned integer NOT NULL DEFAULT 0,
    created_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uq_user_check_in_day UNIQUE (user_id, check_in_date)
  );
  CREATE INDEX IF NOT EXISTS idx_user_check_ins_user ON user_check_ins (user_id, check_in_date);

  CREATE TABLE IF NOT EXISTS activation_codes (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(32) NOT NULL UNIQUE,
    type varchar(16) NOT NULL,
    points_amount integer NULL,
    membership_days integer NULL,
    max_uses integer NOT NULL DEFAULT 1,
    use_count integer NOT NULL DEFAULT 0,
    expires_at timestamptz(3) NULL,
    note varchar(120) NOT NULL DEFAULT '',
    created_by integer NULL,
    created_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
  );
  CREATE INDEX IF NOT EXISTS idx_activation_codes_type ON activation_codes (type, created_at);

  CREATE TABLE IF NOT EXISTS activation_code_redemptions (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_id integer NOT NULL,
    user_id integer NOT NULL,
    redeemed_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uq_activation_code_user UNIQUE (code_id, user_id)
  );
  CREATE INDEX IF NOT EXISTS idx_activation_redemptions_user ON activation_code_redemptions (user_id, redeemed_at);
`;

function getSiteDateKey(date) {
  const now = date instanceof Date ? date : new Date();
  const local = new Date(now.getTime() + SITE_TZ_OFFSET_MS);
  const y = local.getUTCFullYear();
  const m = String(local.getUTCMonth() + 1).padStart(2, '0');
  const d = String(local.getUTCDate()).padStart(2, '0');
  return `${y}-${m}-${d}`;
}

function getPreviousSiteDateKey(dateKey) {
  const base = new Date(`${dateKey}T12:00:00+08:00`);
  base.setUTCDate(base.getUTCDate() - 1);
  return getSiteDateKey(base);
}

function normalizeActivationCodeInput(raw) {
  const body = raw && typeof raw === 'object' ? raw : {};
  const type = String(body.type || '').trim().toLowerCase();
  if (!ACTIVATION_CODE_TYPES.has(type)) return { error: 'BAD_TYPE' };
  const maxUses = Math.min(100000, Math.max(1, Math.floor(Number(body.maxUses) || 1)));
  const note = String(body.note || '').trim().slice(0, 120);
  let expiresAt = null;
  if (body.expiresAt) {
    const ts = new Date(String(body.expiresAt)).getTime();
    if (!Number.isFinite(ts)) return { error: 'BAD_EXPIRES_AT' };
    expiresAt = new Date(ts);
  }
  if (type === 'points') {
    const pointsAmount = Math.floor(Number(body.pointsAmount));
    if (!Number.isFinite(pointsAmount) || pointsAmount < 1 || pointsAmount > 1000000) {
      return { error: 'BAD_POINTS_AMOUNT' };
    }
    return { type, pointsAmount, membershipDays: null, maxUses, expiresAt, note };
  }
  const membershipDaysRaw = body.membershipDays;
  let membershipDays = null;
  if (membershipDaysRaw === 0 || membershipDaysRaw === '0' || membershipDaysRaw === 'lifetime') {
    membershipDays = 0;
  } else {
    membershipDays = Math.floor(Number(membershipDaysRaw));
    if (!Number.isFinite(membershipDays) || membershipDays < 1 || membershipDays > 3650) {
      return { error: 'BAD_MEMBERSHIP_DAYS' };
    }
  }
  return { type, pointsAmount: null, membershipDays, maxUses, expiresAt, note };
}

function normalizeRedeemCodeInput(raw) {
  const code = String((raw && raw.code) || '').trim().toUpperCase().replace(/\s+/g, '');
  if (!code || code.length < 6 || code.length > 32) return { error: 'BAD_CODE' };
  if (!/^[A-Z0-9_-]+$/.test(code)) return { error: 'BAD_CODE' };
  return { code };
}

function generateActivationCode(length) {
  const size = Math.max(8, Math.min(24, Number(length) || 12));
  let out = '';
  for (let i = 0; i < size; i += 1) {
    const idx = crypto.randomInt(0, CODE_ALPHABET.length);
    out += CODE_ALPHABET.charAt(idx);
  }
  return out;
}

function mapActivationCodeRow(row) {
  if (!row) return null;
  return {
    id: Number(row.id),
    code: String(row.code || ''),
    type: String(row.type || ''),
    pointsAmount: row.points_amount != null ? Number(row.points_amount) : null,
    membershipDays: row.membership_days != null ? Number(row.membership_days) : null,
    maxUses: Number(row.max_uses || 0),
    useCount: Number(row.use_count || 0),
    expiresAt: row.expires_at || null,
    note: String(row.note || ''),
    createdBy: row.created_by != null ? Number(row.created_by) : null,
    createdAt: row.created_at || null,
    remainingUses: Math.max(0, Number(row.max_uses || 0) - Number(row.use_count || 0))
  };
}

function computeNextStreakDay(lastRow, todayKey) {
  if (!lastRow) return 1;
  const lastDate = String(lastRow.check_in_date || '').slice(0, 10);
  if (lastDate === todayKey) return Number(lastRow.streak_day || 1);
  const yesterday = getPreviousSiteDateKey(todayKey);
  if (lastDate === yesterday) {
    const prev = Number(lastRow.streak_day || 1);
    if (prev >= STREAK_BONUS_DAYS) return 1;
    return prev + 1;
  }
  return 1;
}

function computeCheckinReward(streakDay) {
  const base = DAILY_CHECKIN_POINTS;
  const bonus = streakDay === STREAK_BONUS_DAYS ? STREAK_BONUS_POINTS : 0;
  return { pointsEarned: base + bonus, streakDay, bonusAwarded: bonus > 0 };
}

function applyMembershipFromCode(currentStatus, currentExpiresAt, membershipDays, now) {
  const tsNow = now.getTime();
  if (membershipDays === 0) {
    return { membershipStatus: 'lifetime', membershipExpiresAt: null };
  }
  let base = tsNow;
  const status = String(currentStatus || 'none');
  if (status === 'active' && currentExpiresAt) {
    const expTs = new Date(currentExpiresAt).getTime();
    if (Number.isFinite(expTs) && expTs > tsNow) base = expTs;
  }
  const next = new Date(base + membershipDays * 24 * 60 * 60 * 1000);
  return { membershipStatus: 'active', membershipExpiresAt: next };
}

async function getUserPoints(deps, userId) {
  const row = await deps.queryOne('SELECT points FROM users WHERE id = ? LIMIT 1', [userId]);
  return Math.max(0, Number(row?.points || 0));
}

async function getCheckinStatus(deps, userId, now) {
  const todayKey = getSiteDateKey(now);
  const last = await deps.queryOne(
    `
    SELECT check_in_date, streak_day, points_earned, created_at
    FROM user_check_ins
    WHERE user_id = ?
    ORDER BY check_in_date DESC
    LIMIT 1
    `,
    [userId]
  );
  const todayRow = await deps.queryOne(
    'SELECT check_in_date, streak_day, points_earned FROM user_check_ins WHERE user_id = ? AND check_in_date = ? LIMIT 1',
    [userId, todayKey]
  );
  const checkedToday = !!todayRow;
  let currentStreak = 0;
  if (checkedToday) {
    currentStreak = Number(todayRow.streak_day || 0);
  } else if (last) {
    const lastDate = String(last.check_in_date || '').slice(0, 10);
    const yesterday = getPreviousSiteDateKey(todayKey);
    if (lastDate === yesterday) currentStreak = Number(last.streak_day || 0);
  }
  const nextStreakDay = checkedToday ? currentStreak : computeNextStreakDay(last, todayKey);
  const nextReward = computeCheckinReward(nextStreakDay);
  return {
    points: await getUserPoints(deps, userId),
    checkedToday,
    currentStreak,
    nextStreakDay,
    nextRewardPoints: nextReward.pointsEarned,
    streakBonusAtDay: STREAK_BONUS_DAYS,
    streakBonusPoints: STREAK_BONUS_POINTS,
    dailyPoints: DAILY_CHECKIN_POINTS,
    lastCheckInAt: last?.created_at || null,
    todayPointsEarned: checkedToday ? Number(todayRow.points_earned || 0) : 0
  };
}

async function performCheckin(deps, userId, now) {
  const todayKey = getSiteDateKey(now);
  const existing = await deps.queryOne(
    'SELECT id FROM user_check_ins WHERE user_id = ? AND check_in_date = ? LIMIT 1',
    [userId, todayKey]
  );
  if (existing) return { error: 'ALREADY_CHECKED_IN' };

  const last = await deps.queryOne(
    `
    SELECT check_in_date, streak_day
    FROM user_check_ins
    WHERE user_id = ?
    ORDER BY check_in_date DESC
    LIMIT 1
    `,
    [userId]
  );
  const streakDay = computeNextStreakDay(last, todayKey);
  const reward = computeCheckinReward(streakDay);

  await deps.execute(
    `
    INSERT INTO user_check_ins (user_id, check_in_date, streak_day, points_earned)
    VALUES (?, ?, ?, ?)
    `,
    [userId, todayKey, streakDay, reward.pointsEarned]
  );
  await deps.execute('UPDATE users SET points = COALESCE(points, 0) + ? WHERE id = ?', [
    reward.pointsEarned,
    userId
  ]);

  return {
    pointsEarned: reward.pointsEarned,
    streakDay,
    bonusAwarded: reward.bonusAwarded,
    points: await getUserPoints(deps, userId)
  };
}

async function redeemActivationCode(deps, userId, codeText, now, helpers) {
  const code = String(codeText || '').trim().toUpperCase();
  const row = await deps.queryOne('SELECT * FROM activation_codes WHERE code = ? LIMIT 1', [code]);
  if (!row) return { error: 'CODE_NOT_FOUND' };
  if (row.expires_at) {
    const expTs = new Date(row.expires_at).getTime();
    if (Number.isFinite(expTs) && expTs < now.getTime()) return { error: 'CODE_EXPIRED' };
  }
  if (Number(row.use_count || 0) >= Number(row.max_uses || 0)) return { error: 'CODE_EXHAUSTED' };

  const redeemed = await deps.queryOne(
    'SELECT id FROM activation_code_redemptions WHERE code_id = ? AND user_id = ? LIMIT 1',
    [row.id, userId]
  );
  if (redeemed) return { error: 'CODE_ALREADY_USED' };

  const user = await deps.queryOne(
    'SELECT id, points, membership_status, membership_expires_at FROM users WHERE id = ? LIMIT 1',
    [userId]
  );
  if (!user) return { error: 'USER_NOT_FOUND' };

  const type = String(row.type || '');
  let result = { type, pointsAdded: 0, membershipStatus: null, membershipExpiresAt: null };

  if (type === 'points') {
    const amount = Math.max(0, Number(row.points_amount || 0));
    if (amount < 1) return { error: 'CODE_INVALID' };
    await deps.execute('UPDATE users SET points = COALESCE(points, 0) + ? WHERE id = ?', [amount, userId]);
    result.pointsAdded = amount;
  } else if (type === 'membership') {
    const membershipDays = row.membership_days == null ? 0 : Number(row.membership_days);
    const next = applyMembershipFromCode(
      user.membership_status,
      user.membership_expires_at,
      membershipDays,
      now
    );
    await deps.execute(
      'UPDATE users SET membership_status = ?, membership_expires_at = ? WHERE id = ?',
      [
        next.membershipStatus,
        next.membershipExpiresAt ? helpers.formatSqlDateTime(next.membershipExpiresAt) : null,
        userId
      ]
    );
    result.membershipStatus = next.membershipStatus;
    result.membershipExpiresAt = next.membershipExpiresAt;
  } else {
    return { error: 'CODE_INVALID' };
  }

  await deps.execute(
    'INSERT INTO activation_code_redemptions (code_id, user_id) VALUES (?, ?)',
    [row.id, userId]
  );
  await deps.execute('UPDATE activation_codes SET use_count = use_count + 1 WHERE id = ?', [row.id]);

  result.points = await getUserPoints(deps, userId);
  return result;
}

function mountUserRewardsRoutes(deps) {
  const {
    app,
    queryRows,
    queryOne,
    execute,
    requireAuth,
    requireAdmin,
    auditAdminAction,
    formatSqlDateTime,
    toUserPayload,
    attachFollowCountsToUserPayload,
    pgDatabase
  } = deps;

  app.get('/api/me/rewards', async (req, res) => {
    try {
      const user = await requireAuth(req, res);
      if (!user) return;
      const status = await getCheckinStatus({ queryOne, execute }, user.id, new Date());
      return res.json({ rewards: status });
    } catch (err) {
      console.error('me rewards get failed:', err);
      return res.status(500).json({ error: 'INTERNAL_ERROR' });
    }
  });

  app.post('/api/me/check-in', async (req, res) => {
    try {
      const user = await requireAuth(req, res);
      if (!user) return;
      const result = await performCheckin({ queryOne, execute }, user.id, new Date());
      if (result.error === 'ALREADY_CHECKED_IN') {
        return res.status(409).json({ error: result.error });
      }
      const rewards = await getCheckinStatus({ queryOne, execute }, user.id, new Date());
      return res.json({ ok: true, checkIn: result, rewards });
    } catch (err) {
      console.error('me check-in failed:', err);
      return res.status(500).json({ error: 'INTERNAL_ERROR' });
    }
  });

  app.post('/api/me/redeem-code', async (req, res) => {
    try {
      const user = await requireAuth(req, res);
      if (!user) return;
      const parsed = normalizeRedeemCodeInput(req.body || {});
      if (parsed.error) return res.status(400).json({ error: parsed.error });
      const result = await redeemActivationCode(
        { queryOne, execute },
        user.id,
        parsed.code,
        new Date(),
        { formatSqlDateTime }
      );
      if (result.error) {
        const status =
          result.error === 'CODE_NOT_FOUND'
            ? 404
            : result.error === 'CODE_ALREADY_USED' || result.error === 'CODE_EXHAUSTED'
              ? 409
              : 400;
        return res.status(status).json({ error: result.error });
      }
      let freshUser = await queryOne('SELECT * FROM users WHERE id = ? LIMIT 1', [user.id]);
      const payload = freshUser
        ? await attachFollowCountsToUserPayload(toUserPayload(freshUser))
        : null;
      const rewards = await getCheckinStatus({ queryOne, execute }, user.id, new Date());
      return res.json({ ok: true, redemption: result, user: payload, rewards });
    } catch (err) {
      console.error('me redeem-code failed:', err);
      return res.status(500).json({ error: 'INTERNAL_ERROR' });
    }
  });

  app.get('/api/admin/activation-codes', async (req, res) => {
    try {
      const admin = await requireAdmin(req, res);
      if (!admin) return;
      const rows = await queryRows(
        `
        SELECT id, code, type, points_amount, membership_days, max_uses, use_count, expires_at, note, created_by, created_at
        FROM activation_codes
        ORDER BY created_at DESC, id DESC
        LIMIT 500
        `
      );
      return res.json({ codes: rows.map(mapActivationCodeRow) });
    } catch (err) {
      console.error('admin activation-codes get failed:', err);
      return res.status(500).json({ error: 'INTERNAL_ERROR' });
    }
  });

  app.post('/api/admin/activation-codes', async (req, res) => {
    try {
      const admin = await requireAdmin(req, res);
      if (!admin) return;
      const parsed = normalizeActivationCodeInput(req.body || {});
      if (parsed.error) return res.status(400).json({ error: parsed.error });

      let code = String((req.body && req.body.code) || '')
        .trim()
        .toUpperCase()
        .replace(/\s+/g, '');
      if (!code) code = generateActivationCode(12);
      if (code.length < 6 || code.length > 32 || !/^[A-Z0-9_-]+$/.test(code)) {
        return res.status(400).json({ error: 'BAD_CODE' });
      }

      const exists = await queryOne('SELECT id FROM activation_codes WHERE code = ? LIMIT 1', [code]);
      if (exists) return res.status(409).json({ error: 'CODE_TAKEN' });

      const expiresValue = parsed.expiresAt ? formatSqlDateTime(parsed.expiresAt) : null;
      await execute(
        `
        INSERT INTO activation_codes
          (code, type, points_amount, membership_days, max_uses, expires_at, note, created_by)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?)
        `,
        [
          code,
          parsed.type,
          parsed.pointsAmount,
          parsed.membershipDays,
          parsed.maxUses,
          expiresValue,
          parsed.note,
          admin.id
        ]
      );
      const row = await queryOne('SELECT * FROM activation_codes WHERE code = ? LIMIT 1', [code]);
      if (auditAdminAction) {
        await auditAdminAction(req, {
          action: 'activation_code_create',
          targetType: 'activation_code',
          targetId: String(row?.id || code),
          riskLevel: 'info',
          summary: `创建${parsed.type === 'points' ? '积分' : '会员'}激活码 ${code}`
        });
      }
      return res.status(201).json({ code: mapActivationCodeRow(row) });
    } catch (err) {
      console.error('admin activation-codes create failed:', err);
      return res.status(500).json({ error: 'INTERNAL_ERROR' });
    }
  });
}

async function ensureUserRewardsSchema(deps) {
  const { execute, pgDatabase, addColumnIfMissing } = deps;
  const ddl = pgDatabase ? USER_REWARDS_DDL_PG : USER_REWARDS_DDL_MYSQL;
  const parts = ddl.split(';').map((s) => s.trim()).filter(Boolean);
  for (const sql of parts) {
    await execute(sql);
  }
  if (addColumnIfMissing) {
    const pointsDdl = pgDatabase
      ? 'points integer NOT NULL DEFAULT 0'
      : 'points INT NOT NULL DEFAULT 0';
    await addColumnIfMissing('users', 'points', pointsDdl);
  }
}

module.exports = {
  USER_REWARDS_DDL_MYSQL,
  USER_REWARDS_DDL_PG,
  DAILY_CHECKIN_POINTS,
  STREAK_BONUS_POINTS,
  STREAK_BONUS_DAYS,
  getSiteDateKey,
  getPreviousSiteDateKey,
  computeNextStreakDay,
  computeCheckinReward,
  normalizeActivationCodeInput,
  normalizeRedeemCodeInput,
  generateActivationCode,
  mapActivationCodeRow,
  applyMembershipFromCode,
  ensureUserRewardsSchema,
  mountUserRewardsRoutes
};
