'use strict';

const crypto = require('crypto');

const DAILY_CHECKIN_POINTS = 2;
const STREAK_BONUS_POINTS = 5;
const STREAK_BONUS_DAYS = 7;
const SITE_TZ_OFFSET_MS = 8 * 60 * 60 * 1000;

const ACTIVATION_CODE_TYPES = new Set(['points', 'membership', 'combo', 'shop_item']);
const CODE_ALPHABET = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';

const USER_REWARDS_DDL_MYSQL = `
  CREATE TABLE IF NOT EXISTS user_check_ins (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    check_in_date DATE NOT NULL,
    streak_day INT NOT NULL DEFAULT 1,
    points_earned INT NOT NULL DEFAULT 0,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    UNIQUE KEY uq_user_check_in_day (user_id, check_in_date),
    KEY idx_user_check_ins_user (user_id, check_in_date)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

  CREATE TABLE IF NOT EXISTS activation_codes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    code VARCHAR(48) NOT NULL UNIQUE,
    type VARCHAR(16) NOT NULL,
    points_amount INT NULL,
    membership_days INT NULL,
    shop_item_id INT NULL,
    max_uses INT NOT NULL DEFAULT 1,
    per_user_limit INT NOT NULL DEFAULT 1,
    use_count INT NOT NULL DEFAULT 0,
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    starts_at DATETIME(3) NULL,
    expires_at DATETIME(3) NULL,
    note VARCHAR(200) NOT NULL DEFAULT '',
    batch_label VARCHAR(64) NOT NULL DEFAULT '',
    created_by INT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    KEY idx_activation_codes_type (type, created_at)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

  CREATE TABLE IF NOT EXISTS activation_code_redemptions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    code_id INT NOT NULL,
    user_id INT NOT NULL,
    redeemed_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    KEY idx_activation_redemptions_code_user (code_id, user_id),
    KEY idx_activation_redemptions_user (user_id, redeemed_at)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
`;

const USER_REWARDS_DDL_PG = `
  CREATE TABLE IF NOT EXISTS user_check_ins (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL,
    check_in_date date NOT NULL,
    streak_day integer NOT NULL DEFAULT 1,
    points_earned integer NOT NULL DEFAULT 0,
    created_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uq_user_check_in_day UNIQUE (user_id, check_in_date)
  );
  CREATE INDEX IF NOT EXISTS idx_user_check_ins_user ON user_check_ins (user_id, check_in_date);

  CREATE TABLE IF NOT EXISTS activation_codes (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(48) NOT NULL UNIQUE,
    type varchar(16) NOT NULL,
    points_amount integer NULL,
    membership_days integer NULL,
    shop_item_id integer NULL,
    max_uses integer NOT NULL DEFAULT 1,
    per_user_limit integer NOT NULL DEFAULT 1,
    use_count integer NOT NULL DEFAULT 0,
    enabled smallint NOT NULL DEFAULT 1,
    starts_at timestamptz(3) NULL,
    expires_at timestamptz(3) NULL,
    note varchar(200) NOT NULL DEFAULT '',
    batch_label varchar(64) NOT NULL DEFAULT '',
    created_by integer NULL,
    created_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
  );
  CREATE INDEX IF NOT EXISTS idx_activation_codes_type ON activation_codes (type, created_at);

  CREATE TABLE IF NOT EXISTS activation_code_redemptions (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_id integer NOT NULL,
    user_id integer NOT NULL,
    redeemed_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
  );
  CREATE INDEX IF NOT EXISTS idx_activation_redemptions_code_user ON activation_code_redemptions (code_id, user_id);
  CREATE INDEX IF NOT EXISTS idx_activation_redemptions_user ON activation_code_redemptions (user_id, redeemed_at);
`;

function getSiteDateKey(date) {
  const now = date instanceof Date ? date : new Date();
  const local = new Date(now.getTime() + SITE_TZ_OFFSET_MS);
  const y = local.getUTCFullYear();
  const m = String(local.getUTCMonth() + 1).padStart(2, '0');
  const d = String(local.getUTCDate()).padStart(2, '0');
  return `${y}-${m}-${d}`;
}

function getPreviousSiteDateKey(dateKey) {
  const base = new Date(`${dateKey}T12:00:00+08:00`);
  base.setUTCDate(base.getUTCDate() - 1);
  return getSiteDateKey(base);
}

function normalizeCodeText(raw) {
  const code = String(raw || '').trim().toUpperCase().replace(/\s+/g, '');
  if (!code || code.length < 4 || code.length > 48) return { error: 'BAD_CODE' };
  if (!/^[A-Z0-9_-]+$/.test(code)) return { error: 'BAD_CODE' };
  return { code };
}

function parseDateField(value, fieldName) {
  if (value == null || value === '') return { value: null };
  const ts = new Date(String(value)).getTime();
  if (!Number.isFinite(ts)) return { error: fieldName === 'startsAt' ? 'BAD_STARTS_AT' : 'BAD_EXPIRES_AT' };
  return { value: new Date(ts) };
}

function normalizeActivationCodeInput(raw) {
  const body = raw && typeof raw === 'object' ? raw : {};
  const type = String(body.type || '').trim().toLowerCase();
  if (!ACTIVATION_CODE_TYPES.has(type)) return { error: 'BAD_TYPE' };

  const maxUsesRaw = body.maxUses ?? body.max_uses;
  let maxUses = 1;
  if (maxUsesRaw === 0 || maxUsesRaw === '0' || maxUsesRaw === 'unlimited') {
    maxUses = 0;
  } else if (maxUsesRaw != null && maxUsesRaw !== '') {
    maxUses = Math.floor(Number(maxUsesRaw));
    if (!Number.isFinite(maxUses) || maxUses < 0 || maxUses > 1000000) return { error: 'BAD_MAX_USES' };
  }

  const perUserLimit = Math.min(1000, Math.max(1, Math.floor(Number(body.perUserLimit ?? body.per_user_limit) || 1)));
  const note = String(body.note || '').trim().slice(0, 200);
  const batchLabel = String(body.batchLabel || body.batch_label || '').trim().slice(0, 64);
  const enabled = body.enabled === false || body.enabled === 0 || body.enabled === '0' ? 0 : 1;

  const starts = parseDateField(body.startsAt ?? body.starts_at, 'startsAt');
  if (starts.error) return { error: starts.error };
  const expires = parseDateField(body.expiresAt ?? body.expires_at, 'expiresAt');
  if (expires.error) return { error: expires.error };

  const base = {
    type,
    maxUses,
    perUserLimit,
    startsAt: starts.value,
    expiresAt: expires.value,
    note,
    batchLabel,
    enabled,
    pointsAmount: null,
    membershipDays: null,
    shopItemId: null
  };

  if (type === 'shop_item') {
    const shopItemId = Math.floor(Number(body.shopItemId ?? body.shop_item_id));
    if (!Number.isFinite(shopItemId) || shopItemId <= 0) return { error: 'BAD_SHOP_ITEM' };
    return { ...base, shopItemId };
  }

  if (type === 'points' || type === 'combo') {
    const pointsAmount = Math.floor(Number(body.pointsAmount ?? body.points_amount));
    if (!Number.isFinite(pointsAmount) || pointsAmount < 1 || pointsAmount > 1000000) {
      return { error: 'BAD_POINTS_AMOUNT' };
    }
    base.pointsAmount = pointsAmount;
  }

  if (type === 'membership' || type === 'combo') {
    const membershipDaysRaw = body.membershipDays ?? body.membership_days;
    if (membershipDaysRaw === 0 || membershipDaysRaw === '0' || membershipDaysRaw === 'lifetime') {
      base.membershipDays = 0;
    } else {
      const membershipDays = Math.floor(Number(membershipDaysRaw));
      if (!Number.isFinite(membershipDays) || membershipDays < 1 || membershipDays > 3650) {
        return { error: 'BAD_MEMBERSHIP_DAYS' };
      }
      base.membershipDays = membershipDays;
    }
  }

  return base;
}

function normalizeRedeemCodeInput(raw) {
  return normalizeCodeText((raw && raw.code) || '');
}

function normalizeBatchActivationInput(raw) {
  const body = raw && typeof raw === 'object' ? raw : {};
  const count = Math.min(500, Math.max(1, Math.floor(Number(body.count) || 1)));
  const codeLength = Math.min(24, Math.max(6, Math.floor(Number(body.codeLength ?? body.code_length) || 12)));
  const prefix = String(body.prefix || '').trim().toUpperCase().replace(/[^A-Z0-9_-]/g, '').slice(0, 16);
  const template = normalizeActivationCodeInput(body);
  if (template.error) return template;
  return { count, codeLength, prefix, template };
}

function generateActivationCode(length, prefix) {
  const pre = String(prefix || '').trim().toUpperCase();
  const remain = Math.max(4, Number(length) || 12) - pre.length;
  let out = pre;
  for (let i = 0; i < remain; i += 1) {
    out += CODE_ALPHABET.charAt(crypto.randomInt(0, CODE_ALPHABET.length));
  }
  return out.slice(0, 48);
}

function mapActivationCodeRow(row) {
  if (!row) return null;
  const maxUses = Number(row.max_uses || 0);
  const useCount = Number(row.use_count || 0);
  return {
    id: Number(row.id),
    code: String(row.code || ''),
    type: String(row.type || ''),
    pointsAmount: row.points_amount != null ? Number(row.points_amount) : null,
    membershipDays: row.membership_days != null ? Number(row.membership_days) : null,
    shopItemId: row.shop_item_id != null ? Number(row.shop_item_id) : null,
    maxUses,
    perUserLimit: Number(row.per_user_limit || 1),
    useCount,
    enabled: Number(row.enabled) !== 0,
    startsAt: row.starts_at || null,
    expiresAt: row.expires_at || null,
    note: String(row.note || ''),
    batchLabel: String(row.batch_label || ''),
    createdBy: row.created_by != null ? Number(row.created_by) : null,
    createdAt: row.created_at || null,
    remainingUses: maxUses === 0 ? null : Math.max(0, maxUses - useCount),
    unlimitedUses: maxUses === 0
  };
}

function activationValueLabel(row) {
  if (!row) return '';
  if (row.type === 'shop_item') return `商城道具 #${row.shopItemId || '?'}`;
  if (row.type === 'points') return `${row.pointsAmount || 0} 积分`;
  if (row.type === 'membership') {
    return row.membershipDays === 0 ? '永久会员' : `${row.membershipDays} 天会员`;
  }
  if (row.type === 'combo') {
    const mem = row.membershipDays === 0 ? '永久会员' : `${row.membershipDays} 天会员`;
    return `${row.pointsAmount || 0} 积分 + ${mem}`;
  }
  return '';
}

function computeNextStreakDay(lastRow, todayKey) {
  if (!lastRow) return 1;
  const lastDate = String(lastRow.check_in_date || '').slice(0, 10);
  if (lastDate === todayKey) return Number(lastRow.streak_day || 1);
  const yesterday = getPreviousSiteDateKey(todayKey);
  if (lastDate === yesterday) {
    const prev = Number(lastRow.streak_day || 1);
    if (prev >= STREAK_BONUS_DAYS) return 1;
    return prev + 1;
  }
  return 1;
}

function computeCheckinReward(streakDay) {
  const base = DAILY_CHECKIN_POINTS;
  const bonus = streakDay === STREAK_BONUS_DAYS ? STREAK_BONUS_POINTS : 0;
  return { pointsEarned: base + bonus, streakDay, bonusAwarded: bonus > 0 };
}

function applyMembershipFromCode(currentStatus, currentExpiresAt, membershipDays, now) {
  const tsNow = now.getTime();
  if (membershipDays === 0) {
    return { membershipStatus: 'lifetime', membershipExpiresAt: null };
  }
  let base = tsNow;
  const status = String(currentStatus || 'none');
  if (status === 'active' && currentExpiresAt) {
    const expTs = new Date(currentExpiresAt).getTime();
    if (Number.isFinite(expTs) && expTs > tsNow) base = expTs;
  }
  const next = new Date(base + membershipDays * 24 * 60 * 60 * 1000);
  return { membershipStatus: 'active', membershipExpiresAt: next };
}

async function getUserPoints(deps, userId) {
  const row = await deps.queryOne('SELECT points FROM users WHERE id = ? LIMIT 1', [userId]);
  return Math.max(0, Number(row?.points || 0));
}

async function getCheckinStatus(deps, userId, now) {
  const todayKey = getSiteDateKey(now);
  const last = await deps.queryOne(
    `
    SELECT check_in_date, streak_day, points_earned, created_at
    FROM user_check_ins
    WHERE user_id = ?
    ORDER BY check_in_date DESC
    LIMIT 1
    `,
    [userId]
  );
  const todayRow = await deps.queryOne(
    'SELECT check_in_date, streak_day, points_earned FROM user_check_ins WHERE user_id = ? AND check_in_date = ? LIMIT 1',
    [userId, todayKey]
  );
  const checkedToday = !!todayRow;
  let currentStreak = 0;
  if (checkedToday) {
    currentStreak = Number(todayRow.streak_day || 0);
  } else if (last) {
    const lastDate = String(last.check_in_date || '').slice(0, 10);
    const yesterday = getPreviousSiteDateKey(todayKey);
    if (lastDate === yesterday) currentStreak = Number(last.streak_day || 0);
  }
  const nextStreakDay = checkedToday ? currentStreak : computeNextStreakDay(last, todayKey);
  const nextReward = computeCheckinReward(nextStreakDay);
  return {
    points: await getUserPoints(deps, userId),
    checkedToday,
    currentStreak,
    nextStreakDay,
    nextRewardPoints: nextReward.pointsEarned,
    streakBonusAtDay: STREAK_BONUS_DAYS,
    streakBonusPoints: STREAK_BONUS_POINTS,
    dailyPoints: DAILY_CHECKIN_POINTS,
    lastCheckInAt: last?.created_at || null,
    todayPointsEarned: checkedToday ? Number(todayRow.points_earned || 0) : 0
  };
}

async function performCheckin(deps, userId, now) {
  const todayKey = getSiteDateKey(now);
  const existing = await deps.queryOne(
    'SELECT id FROM user_check_ins WHERE user_id = ? AND check_in_date = ? LIMIT 1',
    [userId, todayKey]
  );
  if (existing) return { error: 'ALREADY_CHECKED_IN' };

  const last = await deps.queryOne(
    `
    SELECT check_in_date, streak_day
    FROM user_check_ins
    WHERE user_id = ?
    ORDER BY check_in_date DESC
    LIMIT 1
    `,
    [userId]
  );
  const streakDay = computeNextStreakDay(last, todayKey);
  const reward = computeCheckinReward(streakDay);

  await deps.execute(
    `
    INSERT INTO user_check_ins (user_id, check_in_date, streak_day, points_earned)
    VALUES (?, ?, ?, ?)
    `,
    [userId, todayKey, streakDay, reward.pointsEarned]
  );
  await deps.execute('UPDATE users SET points = COALESCE(points, 0) + ? WHERE id = ?', [
    reward.pointsEarned,
    userId
  ]);

  return {
    pointsEarned: reward.pointsEarned,
    streakDay,
    bonusAwarded: reward.bonusAwarded,
    points: await getUserPoints(deps, userId)
  };
}

async function applyCodeRewards(deps, user, row, helpers) {
  const type = String(row.type || '');
  const now = helpers.now || new Date();
  let result = {
    type,
    pointsAdded: 0,
    membershipStatus: null,
    membershipExpiresAt: null,
    shopItemId: null,
    shopItemName: null
  };

  if (type === 'shop_item') {
    if (!helpers.applyShopItemToUser || !helpers.mapShopItemRow) return { error: 'CODE_INVALID' };
    const itemRow = await deps.queryOne('SELECT * FROM shop_items WHERE id = ? LIMIT 1', [row.shop_item_id]);
    if (!itemRow) return { error: 'SHOP_ITEM_NOT_FOUND' };
    const item = helpers.mapShopItemRow(itemRow);
    const applied = await helpers.applyShopItemToUser(deps, user.id, item, helpers);
    if (applied.error) return applied;
    result.shopItemId = item.id;
    result.shopItemName = item.name;
    result.pointsAdded = applied.pointsAdded || 0;
    result.membershipStatus = applied.membershipStatus;
    result.membershipExpiresAt = applied.membershipExpiresAt;
    result.points = applied.points;
    return result;
  }

  if (type === 'points' || type === 'combo') {
    const amount = Math.max(0, Number(row.points_amount || 0));
    if (amount < 1) return { error: 'CODE_INVALID' };
    await deps.execute('UPDATE users SET points = COALESCE(points, 0) + ? WHERE id = ?', [amount, user.id]);
    result.pointsAdded = amount;
  }

  if (type === 'membership' || type === 'combo') {
    const membershipDays = row.membership_days == null ? 0 : Number(row.membership_days);
    const next = applyMembershipFromCode(user.membership_status, user.membership_expires_at, membershipDays, now);
    await deps.execute(
      'UPDATE users SET membership_status = ?, membership_expires_at = ? WHERE id = ?',
      [
        next.membershipStatus,
        next.membershipExpiresAt ? helpers.formatSqlDateTime(next.membershipExpiresAt) : null,
        user.id
      ]
    );
    result.membershipStatus = next.membershipStatus;
    result.membershipExpiresAt = next.membershipExpiresAt;
  }

  if (type !== 'shop_item') {
    result.points = await getUserPoints(deps, user.id);
  }
  return result;
}

function validateActivationCodeAvailability(row, now) {
  if (Number(row.enabled) === 0) return { error: 'CODE_DISABLED' };
  if (row.starts_at) {
    const startTs = new Date(row.starts_at).getTime();
    if (Number.isFinite(startTs) && startTs > now.getTime()) return { error: 'CODE_NOT_STARTED' };
  }
  if (row.expires_at) {
    const expTs = new Date(row.expires_at).getTime();
    if (Number.isFinite(expTs) && expTs < now.getTime()) return { error: 'CODE_EXPIRED' };
  }
  const maxUses = Number(row.max_uses || 0);
  if (maxUses > 0 && Number(row.use_count || 0) >= maxUses) return { error: 'CODE_EXHAUSTED' };
  return null;
}

async function redeemActivationCode(deps, userId, codeText, now, helpers) {
  const code = String(codeText || '').trim().toUpperCase();
  const row = await deps.queryOne('SELECT * FROM activation_codes WHERE code = ? LIMIT 1', [code]);
  if (!row) return { error: 'CODE_NOT_FOUND' };

  const availability = validateActivationCodeAvailability(row, now);
  if (availability) return availability;

  const usedByUser = await deps.queryOne(
    'SELECT COUNT(*) AS c FROM activation_code_redemptions WHERE code_id = ? AND user_id = ?',
    [row.id, userId]
  );
  const userUseCount = Number(usedByUser?.c || 0);
  const perUserLimit = Math.max(1, Number(row.per_user_limit || 1));
  if (userUseCount >= perUserLimit) return { error: 'CODE_ALREADY_USED' };

  const user = await deps.queryOne(
    'SELECT id, points, membership_status, membership_expires_at FROM users WHERE id = ? LIMIT 1',
    [userId]
  );
  if (!user) return { error: 'USER_NOT_FOUND' };

  const result = await applyCodeRewards(deps, user, row, { ...helpers, now });
  if (result.error) return result;

  await deps.execute(
    'INSERT INTO activation_code_redemptions (code_id, user_id) VALUES (?, ?)',
    [row.id, userId]
  );
  await deps.execute('UPDATE activation_codes SET use_count = use_count + 1 WHERE id = ?', [row.id]);

  return result;
}

async function insertActivationCode(deps, adminId, parsed, codeText, formatSqlDateTime) {
  const codeParsed = normalizeCodeText(codeText);
  if (codeParsed.error) return codeParsed;
  const exists = await deps.queryOne('SELECT id FROM activation_codes WHERE code = ? LIMIT 1', [codeParsed.code]);
  if (exists) return { error: 'CODE_TAKEN' };

  await deps.execute(
    `
    INSERT INTO activation_codes
      (code, type, points_amount, membership_days, shop_item_id, max_uses, per_user_limit, enabled,
       starts_at, expires_at, note, batch_label, created_by)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    `,
    [
      codeParsed.code,
      parsed.type,
      parsed.pointsAmount,
      parsed.membershipDays,
      parsed.shopItemId,
      parsed.maxUses,
      parsed.perUserLimit,
      parsed.enabled,
      parsed.startsAt ? formatSqlDateTime(parsed.startsAt) : null,
      parsed.expiresAt ? formatSqlDateTime(parsed.expiresAt) : null,
      parsed.note,
      parsed.batchLabel,
      adminId
    ]
  );
  const row = await deps.queryOne('SELECT * FROM activation_codes WHERE code = ? LIMIT 1', [codeParsed.code]);
  return { code: mapActivationCodeRow(row) };
}

function mountUserRewardsRoutes(deps) {
  const {
    app,
    queryRows,
    queryOne,
    execute,
    requireAuth,
    requireAdmin,
    auditAdminAction,
    formatSqlDateTime,
    toUserPayload,
    attachFollowCountsToUserPayload,
    applyShopItemToUser,
    mapShopItemRow
  } = deps;

  const shopHelpers = { formatSqlDateTime, applyShopItemToUser, mapShopItemRow, now: new Date() };

  app.get('/api/me/rewards', async (req, res) => {
    try {
      const user = await requireAuth(req, res);
      if (!user) return;
      const status = await getCheckinStatus({ queryOne, execute }, user.id, new Date());
      return res.json({ rewards: status });
    } catch (err) {
      console.error('me rewards get failed:', err);
      return res.status(500).json({ error: 'INTERNAL_ERROR' });
    }
  });

  app.post('/api/me/check-in', async (req, res) => {
    try {
      const user = await requireAuth(req, res);
      if (!user) return;
      const result = await performCheckin({ queryOne, execute }, user.id, new Date());
      if (result.error === 'ALREADY_CHECKED_IN') {
        return res.status(409).json({ error: result.error });
      }
      const rewards = await getCheckinStatus({ queryOne, execute }, user.id, new Date());
      return res.json({ ok: true, checkIn: result, rewards });
    } catch (err) {
      console.error('me check-in failed:', err);
      return res.status(500).json({ error: 'INTERNAL_ERROR' });
    }
  });

  app.post('/api/me/redeem-code', async (req, res) => {
    try {
      const user = await requireAuth(req, res);
      if (!user) return;
      const parsed = normalizeRedeemCodeInput(req.body || {});
      if (parsed.error) return res.status(400).json({ error: parsed.error });
      const result = await redeemActivationCode(
        { queryOne, execute },
        user.id,
        parsed.code,
        new Date(),
        shopHelpers
      );
      if (result.error) {
        const status =
          result.error === 'CODE_NOT_FOUND' || result.error === 'SHOP_ITEM_NOT_FOUND'
            ? 404
            : result.error === 'CODE_ALREADY_USED' || result.error === 'CODE_EXHAUSTED'
              ? 409
              : 400;
        return res.status(status).json({ error: result.error });
      }
      const freshUser = await queryOne('SELECT * FROM users WHERE id = ? LIMIT 1', [user.id]);
      const payload = freshUser
        ? await attachFollowCountsToUserPayload(toUserPayload(freshUser))
        : null;
      const rewards = await getCheckinStatus({ queryOne, execute }, user.id, new Date());
      return res.json({ ok: true, redemption: result, user: payload, rewards });
    } catch (err) {
      console.error('me redeem-code failed:', err);
      return res.status(500).json({ error: 'INTERNAL_ERROR' });
    }
  });

  app.get('/api/admin/activation-codes', async (req, res) => {
    try {
      const admin = await requireAdmin(req, res);
      if (!admin) return;
      const q = String(req.query.q || '').trim();
      const params = [];
      let where = '';
      if (q) {
        where = 'WHERE code LIKE ? OR note LIKE ? OR batch_label LIKE ?';
        const token = `%${q}%`;
        params.push(token, token, token);
      }
      const rows = await queryRows(
        `
        SELECT id, code, type, points_amount, membership_days, shop_item_id, max_uses, per_user_limit,
               use_count, enabled, starts_at, expires_at, note, batch_label, created_by, created_at
        FROM activation_codes
        ${where}
        ORDER BY created_at DESC, id DESC
        LIMIT 500
        `,
        params
      );
      return res.json({ codes: rows.map(mapActivationCodeRow) });
    } catch (err) {
      console.error('admin activation-codes get failed:', err);
      return res.status(500).json({ error: 'INTERNAL_ERROR' });
    }
  });

  app.get('/api/admin/activation-codes/shop-options', async (req, res) => {
    try {
      const admin = await requireAdmin(req, res);
      if (!admin) return;
      const rows = await queryRows(
        'SELECT id, name, item_type, price_points, points_reward, membership_days, enabled FROM shop_items ORDER BY sort_order ASC, id ASC LIMIT 500'
      );
      return res.json({
        items: rows.map((row) => ({
          id: Number(row.id),
          name: String(row.name || ''),
          itemType: String(row.item_type || ''),
          enabled: Number(row.enabled) === 1
        }))
      });
    } catch (err) {
      console.error('admin activation shop-options failed:', err);
      return res.status(500).json({ error: 'INTERNAL_ERROR' });
    }
  });

  app.post('/api/admin/activation-codes', async (req, res) => {
    try {
      const admin = await requireAdmin(req, res);
      if (!admin) return;
      const parsed = normalizeActivationCodeInput(req.body || {});
      if (parsed.error) return res.status(400).json({ error: parsed.error });

      let code = String((req.body && req.body.code) || '').trim();
      if (!code) code = generateActivationCode(Number(req.body?.codeLength) || 12, req.body?.prefix || '');
      const created = await insertActivationCode(
        { queryOne, execute },
        admin.id,
        parsed,
        code,
        formatSqlDateTime
      );
      if (created.error) return res.status(created.error === 'CODE_TAKEN' ? 409 : 400).json({ error: created.error });

      if (auditAdminAction) {
        await auditAdminAction(req, {
          action: 'activation_code_create',
          targetType: 'activation_code',
          targetId: String(created.code?.id || code),
          riskLevel: 'info',
          summary: `创建激活码 ${created.code?.code || code}（${parsed.type}）`
        });
      }
      return res.status(201).json(created);
    } catch (err) {
      console.error('admin activation-codes create failed:', err);
      return res.status(500).json({ error: 'INTERNAL_ERROR' });
    }
  });

  app.post('/api/admin/activation-codes/batch', async (req, res) => {
    try {
      const admin = await requireAdmin(req, res);
      if (!admin) return;
      const batch = normalizeBatchActivationInput(req.body || {});
      if (batch.error) return res.status(400).json({ error: batch.error });

      const created = [];
      const maxAttempts = batch.count * 20;
      let attempts = 0;
      while (created.length < batch.count && attempts < maxAttempts) {
        attempts += 1;
        const code = generateActivationCode(batch.codeLength, batch.prefix);
        const result = await insertActivationCode(
          { queryOne, execute },
          admin.id,
          batch.template,
          code,
          formatSqlDateTime
        );
        if (!result.error && result.code) created.push(result.code);
      }
      if (!created.length) return res.status(500).json({ error: 'BATCH_CREATE_FAILED' });

      if (auditAdminAction) {
        await auditAdminAction(req, {
          action: 'activation_code_batch_create',
          targetType: 'activation_code',
          targetId: batch.template.batchLabel || 'batch',
          riskLevel: 'info',
          summary: `批量创建 ${created.length} 个激活码（${batch.template.type}）`
        });
      }
      return res.status(201).json({ codes: created, count: created.length });
    } catch (err) {
      console.error('admin activation-codes batch failed:', err);
      return res.status(500).json({ error: 'INTERNAL_ERROR' });
    }
  });

  app.post('/api/admin/activation-codes/:id', async (req, res) => {
    try {
      const admin = await requireAdmin(req, res);
      if (!admin) return;
      const id = Number(req.params.id);
      if (!Number.isFinite(id) || id <= 0) return res.status(400).json({ error: 'BAD_ID' });
      const existing = await queryOne('SELECT id FROM activation_codes WHERE id = ? LIMIT 1', [id]);
      if (!existing) return res.status(404).json({ error: 'NOT_FOUND' });

      const updates = [];
      const params = [];
      if (Object.prototype.hasOwnProperty.call(req.body || {}, 'enabled')) {
        const enabled = req.body.enabled === false || req.body.enabled === 0 ? 0 : 1;
        updates.push('enabled = ?');
        params.push(enabled);
      }
      if (Object.prototype.hasOwnProperty.call(req.body || {}, 'note')) {
        updates.push('note = ?');
        params.push(String(req.body.note || '').trim().slice(0, 200));
      }
      if (Object.prototype.hasOwnProperty.call(req.body || {}, 'expiresAt')) {
        const exp = parseDateField(req.body.expiresAt, 'expiresAt');
        if (exp.error) return res.status(400).json({ error: exp.error });
        updates.push('expires_at = ?');
        params.push(exp.value ? formatSqlDateTime(exp.value) : null);
      }
      if (!updates.length) return res.status(400).json({ error: 'NO_UPDATES' });
      params.push(id);
      await execute(`UPDATE activation_codes SET ${updates.join(', ')} WHERE id = ?`, params);
      const row = await queryOne('SELECT * FROM activation_codes WHERE id = ? LIMIT 1', [id]);
      return res.json({ code: mapActivationCodeRow(row) });
    } catch (err) {
      console.error('admin activation-codes patch failed:', err);
      return res.status(500).json({ error: 'INTERNAL_ERROR' });
    }
  });
}

async function migrateActivationCodesSchema(deps) {
  const { execute, pgDatabase, addColumnIfMissing } = deps;
  if (!addColumnIfMissing) return;

  const cols = pgDatabase
    ? [
        ['shop_item_id', 'shop_item_id integer NULL'],
        ['per_user_limit', 'per_user_limit integer NOT NULL DEFAULT 1'],
        ['enabled', 'enabled smallint NOT NULL DEFAULT 1'],
        ['starts_at', 'starts_at timestamptz(3) NULL'],
        ['batch_label', 'batch_label varchar(64) NOT NULL DEFAULT \'\'']
      ]
    : [
        ['shop_item_id', 'shop_item_id INT NULL'],
        ['per_user_limit', 'per_user_limit INT NOT NULL DEFAULT 1'],
        ['enabled', 'enabled TINYINT(1) NOT NULL DEFAULT 1'],
        ['starts_at', 'starts_at DATETIME(3) NULL'],
        ['batch_label', 'batch_label VARCHAR(64) NOT NULL DEFAULT \'\'']
      ];

  for (const [name, ddl] of cols) {
    await addColumnIfMissing('activation_codes', name, ddl);
  }

  try {
    if (pgDatabase) {
      await execute('ALTER TABLE activation_codes ALTER COLUMN code TYPE varchar(48)');
      await execute('ALTER TABLE activation_codes ALTER COLUMN note TYPE varchar(200)');
      await execute('ALTER TABLE activation_code_redemptions DROP CONSTRAINT IF EXISTS uq_activation_code_user');
    } else {
      try {
        await execute('ALTER TABLE activation_codes MODIFY COLUMN code VARCHAR(48) NOT NULL');
      } catch (_e) {}
      try {
        await execute('ALTER TABLE activation_codes MODIFY COLUMN note VARCHAR(200) NOT NULL');
      } catch (_e) {}
      try {
        await execute('ALTER TABLE activation_code_redemptions DROP INDEX uq_activation_code_user');
      } catch (_e) {}
    }
  } catch (_e) {}
}

async function ensureUserRewardsSchema(deps) {
  const { execute, pgDatabase, addColumnIfMissing } = deps;
  const ddl = pgDatabase ? USER_REWARDS_DDL_PG : USER_REWARDS_DDL_MYSQL;
  const parts = ddl.split(';').map((s) => s.trim()).filter(Boolean);
  for (const sql of parts) {
    await execute(sql);
  }
  if (addColumnIfMissing) {
    const pointsDdl = pgDatabase
      ? 'points integer NOT NULL DEFAULT 0'
      : 'points INT NOT NULL DEFAULT 0';
    await addColumnIfMissing('users', 'points', pointsDdl);
  }
  await migrateActivationCodesSchema(deps);
}

module.exports = {
  USER_REWARDS_DDL_MYSQL,
  USER_REWARDS_DDL_PG,
  DAILY_CHECKIN_POINTS,
  STREAK_BONUS_POINTS,
  STREAK_BONUS_DAYS,
  ACTIVATION_CODE_TYPES,
  getSiteDateKey,
  getPreviousSiteDateKey,
  computeNextStreakDay,
  computeCheckinReward,
  normalizeActivationCodeInput,
  normalizeBatchActivationInput,
  normalizeRedeemCodeInput,
  normalizeCodeText,
  generateActivationCode,
  mapActivationCodeRow,
  activationValueLabel,
  applyMembershipFromCode,
  applyCodeRewards,
  validateActivationCodeAvailability,
  ensureUserRewardsSchema,
  mountUserRewardsRoutes
};
