/**
 * Stage 24 稳定内核审计清单。这里只记录可验证的不变量和证据入口，
 * 不引入任何新的游戏机制或计算分支。
 */
export const CORE_MODEL_AUDIT_CHECKS = [
  { id: "base-formula", evidence: "baseDamage.test.ts + coreModelAudit.test.ts" },
  { id: "total-count-square-root-cap", evidence: "baseDamage.test.ts + coreModelAudit.test.ts" },
  { id: "troop-coefficients", evidence: "baseDamage.test.ts" },
  { id: "troop-level-catalog", evidence: "baseDamage.test.ts + coreModelAudit.test.ts" },
  { id: "percentage-conversion", evidence: "baseDamage.test.ts + coreModelAudit.test.ts" },
  { id: "total-N-versus-troop-n", evidence: "baseDamage.test.ts + coreModelAudit.test.ts" },
  { id: "three-troop-sum", evidence: "baseDamage.test.ts" },
  { id: "no-intermediate-rounding", evidence: "coreModelAudit.test.ts + source audit" },
  { id: "multiplier-zones", evidence: "skillMultipliers.test.ts" },
  { id: "defense-reduction", evidence: "skillMultipliers.test.ts + coreModelAudit.test.ts" },
  { id: "bear-context", evidence: "bearBattle.test.ts" },
  { id: "ten-round-no-skill", evidence: "completeBearBattleSimulation.test.ts" },
  { id: "probability-mass", evidence: "probabilityEngine.test.ts + coreModelAudit.test.ts" },
  { id: "canonical-state-merge", evidence: "probabilityEngine.test.ts + coreModelAudit.test.ts" },
  { id: "duration-boundaries", evidence: "durationProbabilityEffects.test.ts" },
  { id: "periodic-schedule", evidence: "periodicStackingEffects.test.ts" },
  { id: "stacking-cap", evidence: "periodicStackingEffects.test.ts" },
  { id: "decay-precision", evidence: "periodicStackingEffects.test.ts" },
  { id: "extra-damage-separation", evidence: "extraDamage.test.ts" },
  { id: "extra-attack-events", evidence: "extraAttack.test.ts" },
  { id: "trigger-chain-lineage-cycle", evidence: "triggerChain.test.ts" },
  { id: "pending-safety", evidence: "skillDataAudit.test.ts + coreModelAudit.test.ts" },
  { id: "unsupported-safety", evidence: "coreModelAudit.test.ts" },
  { id: "real-skill-status-report", evidence: "skillDataAudit.test.ts + coreModelAudit.test.ts" },
  { id: "body-rules", evidence: "optimizeBodyHeroes.test.ts" },
  { id: "head-rules", evidence: "headHeroSystem.test.ts" },
  { id: "head-exclusivity", evidence: "optimizeFullBattleSetup.test.ts" },
  { id: "fire-crystal-safety", evidence: "optimizeFullBattleSetup.test.ts + skillDataAudit.test.ts" },
  { id: "optimizer-exactness", evidence: "tenRoundOptimizerScoring.test.ts + coreModelAudit.test.ts" },
  { id: "no-implicit-heuristic", evidence: "source audit + full-setup-optimizer.md" },
  { id: "top-k-determinism", evidence: "optimizer tests + coreModelAudit.test.ts" },
  { id: "largest-remainder-conservation", evidence: "optimizeTroopRatio.test.ts + coreModelAudit.test.ts" },
  { id: "ratio-boundaries", evidence: "tenRoundOptimizerScoring.test.ts" },
  { id: "cache-equivalence", evidence: "coreModelAudit.test.ts" },
  { id: "cache-key-separation", evidence: "coreModelAudit.test.ts" },
  { id: "ratio-benchmark", evidence: "benchmark-optimization.mjs" },
  { id: "body-benchmark", evidence: "benchmark-optimization.mjs" },
  { id: "joint-benchmark", evidence: "benchmark-optimization.mjs" },
  { id: "full-setup-benchmark", evidence: "benchmark-optimization.mjs" },
  { id: "repeatable-benchmark-command", evidence: "package.json" },
  { id: "numeric-stability", evidence: "coreModelAudit.test.ts" },
  { id: "input-validation", evidence: "coreModelAudit.test.ts + existing validation tests" },
  { id: "performance-warning", evidence: "optimizeFullBattleSetup.test.ts" },
] as const;

export const CORE_MODEL_AUDIT_CHECK_COUNT = CORE_MODEL_AUDIT_CHECKS.length;
