name: 功能建议
description: 建议增加或调整一项功能
title: "[建议] "
labels:
  - enhancement
body:
  - type: textarea
    id: need
    attributes:
      label: 想解决什么问题
    validations:
      required: true
  - type: textarea
    id: idea
    attributes:
      label: 你的建议
    validations:
      required: true
