from __future__ import annotations

import json
import re
from pathlib import Path

# Prefer scripts/build-gift-pack-search-blobs.mjs when Python is unavailable.
REPO_ROOT = Path(__file__).resolve().parents[1]
REGULAR_HTML = REPO_ROOT / "public" / "function" / "Zero" / "regular-gift-data.html"
SPECIAL_HTML = REPO_ROOT / "public" / "function" / "Zero" / "special-gift-data.html"
OUTPUT_JS = REPO_ROOT / "public" / "function" / "Zero" / "gift-pack-search-blobs.js"


def extract_packs_json_array(html: str) -> list:
    needle = "const packs"
    i = html.find(needle)
    if i < 0:
        raise ValueError(f"missing `{needle}` in source")
    j = html.find("=", i)
    if j < 0:
        raise ValueError("missing `=` after const packs")
    start = html.find("[", j)
    if start < 0:
        raise ValueError("missing `[` opening packs array")
    depth = 0
    k = start
    while k < len(html):
        c = html[k]
        if c == "[":
            depth += 1
        elif c == "]":
            depth -= 1
            if depth == 0:
                raw = html[start : k + 1].strip()
                return json.loads(raw)
        k += 1
    raise ValueError("unclosed `[` for packs array")


def normalize_text(value: object) -> str:
    """Keep in sync with normalizeText() in regular-gift-data / special-gift-data."""
    return re.sub(
        r"[\s·•\-_.，。、；;：:（）()【】\[\]《》<>]",
        "",
        str(value or "").lower(),
    )


def text_of_pack(pack: dict) -> str:
    base: list[str] = [pack.get("name") or "", pack.get("note") or ""]
    for s in pack.get("sections") or []:
        base.append(s.get("title") or "")
        for c in s.get("columns") or []:
            base.append(c)
    return normalize_text(" ".join(base))


def main() -> None:
    blobs: dict[str, list[dict[str, str]]] = {}
    paths = {"regular": REGULAR_HTML, "special": SPECIAL_HTML}
    for key, path in paths.items():
        html = path.read_text(encoding="utf-8")
        packs = extract_packs_json_array(html)
        blobs[key] = [{"n": p.get("name") or "", "t": text_of_pack(p)} for p in packs]

    out = OUTPUT_JS.read_text(encoding="utf-8") if OUTPUT_JS.exists() else ""
    header = "// AUTO-GENERATED by scripts/build-gift-pack-search-blobs.py — do not edit by hand.\n"
    payload = json.dumps(blobs, ensure_ascii=False, separators=(",", ":"))
    OUTPUT_JS.write_text(
        header + "(function(){window.__giftPackSearchBlobs=" + payload + ";})();\n",
        encoding="utf-8",
        newline="\n",
    )
    counts = ", ".join(f"{k}:{len(v)}" for k, v in blobs.items())
    print(f"wrote {OUTPUT_JS} ({counts})")


if __name__ == "__main__":
    main()
